//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.OpenAPI
{
    using Newtonsoft.Json;
    using Speakeasy.OpenAPI.Utils;

    public class Aloof
    {
        [JsonProperty("bool", Required = Newtonsoft.Json.Required.DisallowNull)]
        public bool? Bool { get; set; }

        [JsonProperty("int", Required = Newtonsoft.Json.Required.DisallowNull)]
        public long? Int { get; set; }
    }
}