//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.OpenAPI
{
    using Newtonsoft.Json;
    using Speakeasy.OpenAPI.Utils;

    public class GetFullyFlattenedRequestRequestBody
    {
        [JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        public string Name { get; set; } = default!;

        [JsonProperty("emoji", Required = Newtonsoft.Json.Required.DisallowNull)]
        public Emoji? Emoji { get; set; }

        [JsonProperty("gif", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Gif { get; set; }

        [JsonProperty("reply", Required = Newtonsoft.Json.Required.DisallowNull)]
        public bool? Reply { get; set; }

        [JsonProperty("private", Required = Newtonsoft.Json.Required.DisallowNull)]
        public bool? Private { get; set; }
    }
}