//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.OpenAPI
{
    using Newtonsoft.Json;
    using Speakeasy.OpenAPI;
    using Speakeasy.OpenAPI.Utils;

    public class GetNamedPrimitiveUnionResponse
    {
        [JsonIgnore]
        public HTTPMetadata HttpMeta { get; set; } = new();

        /// <summary>
        /// OK.
        /// </summary>
        public SomeUnion? SomeUnion { get; set; }
    }
}