//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.OpenAPI
{
    using Newtonsoft.Json;
    using Speakeasy.OpenAPI.Utils;

    /// <summary>
    /// An image record.
    /// </summary>
    public class ImageRecord
    {
        /// <summary>
        /// Record type discriminator.
        /// </summary>
        [JsonProperty("type", Required = Newtonsoft.Json.Required.Always)]
        public string Type { get; set; } = default!;

        [JsonProperty("imageId", Required = Newtonsoft.Json.Required.Always)]
        public string ImageId { get; set; } = default!;

        [JsonProperty("caption", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? Caption { get; set; }
    }
}