//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.OpenAPI
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Speakeasy.OpenAPI.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class OneOfWithFactoredOutPropertiesType
    {
        private OneOfWithFactoredOutPropertiesType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static OneOfWithFactoredOutPropertiesType OneOfWithFactoredOutPropertiesExhaustiveObject
        {
            get {
                return new OneOfWithFactoredOutPropertiesType("OneOfWithFactoredOutProperties_ExhaustiveObject");
            }
        }

        public static OneOfWithFactoredOutPropertiesType OneOfWithFactoredOutPropertiesSimpleObject
        {
            get {
                return new OneOfWithFactoredOutPropertiesType("OneOfWithFactoredOutProperties_SimpleObject");
            }
        }

        public static OneOfWithFactoredOutPropertiesType Unknown
        {
            get {
                return new OneOfWithFactoredOutPropertiesType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(OneOfWithFactoredOutPropertiesType v)
        {
            return v.Value;
        }
        public static OneOfWithFactoredOutPropertiesType FromString(string v)
        {
            switch (v)
            {
                case "OneOfWithFactoredOutProperties_ExhaustiveObject":
                    return OneOfWithFactoredOutPropertiesExhaustiveObject;
                case "OneOfWithFactoredOutProperties_SimpleObject":
                    return OneOfWithFactoredOutPropertiesSimpleObject;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for OneOfWithFactoredOutPropertiesType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((OneOfWithFactoredOutPropertiesType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// A union of two types with factored out properties.
    /// </summary>
    [JsonConverter(typeof(OneOfWithFactoredOutProperties.OneOfWithFactoredOutPropertiesConverter))]
    public class OneOfWithFactoredOutProperties : Speakeasy.OpenAPI.Utils.IOpenUnion
    {
        public OneOfWithFactoredOutProperties(OneOfWithFactoredOutPropertiesType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public OneOfWithFactoredOutPropertiesExhaustiveObject? OneOfWithFactoredOutPropertiesExhaustiveObject { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public OneOfWithFactoredOutPropertiesSimpleObject? OneOfWithFactoredOutPropertiesSimpleObject { get; set; }

        public OneOfWithFactoredOutPropertiesType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static OneOfWithFactoredOutProperties CreateUnknown(JToken raw)
        {
            return new OneOfWithFactoredOutProperties(OneOfWithFactoredOutPropertiesType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(OneOfWithFactoredOutPropertiesType.Unknown);
        }

        bool Speakeasy.OpenAPI.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static OneOfWithFactoredOutProperties CreateOneOfWithFactoredOutPropertiesExhaustiveObject(OneOfWithFactoredOutPropertiesExhaustiveObject oneOfWithFactoredOutPropertiesExhaustiveObject)
        {
            OneOfWithFactoredOutPropertiesType typ = OneOfWithFactoredOutPropertiesType.OneOfWithFactoredOutPropertiesExhaustiveObject;

            OneOfWithFactoredOutProperties res = new OneOfWithFactoredOutProperties(typ);
            res.OneOfWithFactoredOutPropertiesExhaustiveObject = oneOfWithFactoredOutPropertiesExhaustiveObject;
            return res;
        }
        public static OneOfWithFactoredOutProperties CreateOneOfWithFactoredOutPropertiesSimpleObject(OneOfWithFactoredOutPropertiesSimpleObject oneOfWithFactoredOutPropertiesSimpleObject)
        {
            OneOfWithFactoredOutPropertiesType typ = OneOfWithFactoredOutPropertiesType.OneOfWithFactoredOutPropertiesSimpleObject;

            OneOfWithFactoredOutProperties res = new OneOfWithFactoredOutProperties(typ);
            res.OneOfWithFactoredOutPropertiesSimpleObject = oneOfWithFactoredOutPropertiesSimpleObject;
            return res;
        }

        public class OneOfWithFactoredOutPropertiesConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(OneOfWithFactoredOutProperties);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }

                JToken jt = JToken.Load(reader);
                var unionCandidates = new UnionCandidatePool<OneOfWithFactoredOutPropertiesType>();
                unionCandidates.Add<OneOfWithFactoredOutPropertiesExhaustiveObject>("OneOfWithFactoredOutPropertiesExhaustiveObject", 0, OneOfWithFactoredOutPropertiesType.OneOfWithFactoredOutPropertiesExhaustiveObject);
                unionCandidates.Add<OneOfWithFactoredOutPropertiesSimpleObject>("OneOfWithFactoredOutPropertiesSimpleObject", 1, OneOfWithFactoredOutPropertiesType.OneOfWithFactoredOutPropertiesSimpleObject);

                var (winner, winnerValue) = unionCandidates.PickBest(
                    jt,
                    Utilities.GetDefaultJsonDeserializerSettings()
                );
                if (winner is null || winnerValue is null)
                {
                    return CreateUnknown(jt);
                }

                var result = new OneOfWithFactoredOutProperties(winner.TypeName);
                typeof(OneOfWithFactoredOutProperties).GetProperty(winner.PropertyName)!.SetValue(result, winnerValue);
                return result;
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                OneOfWithFactoredOutProperties res = (OneOfWithFactoredOutProperties)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.OneOfWithFactoredOutPropertiesExhaustiveObject != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OneOfWithFactoredOutPropertiesExhaustiveObject));
                    return;
                }

                if (res.OneOfWithFactoredOutPropertiesSimpleObject != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.OneOfWithFactoredOutPropertiesSimpleObject));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}