//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.OpenAPI
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Speakeasy.OpenAPI.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class SomeUnionType
    {
        private SomeUnionType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static SomeUnionType MyString
        {
            get {
                return new SomeUnionType("myString");
            }
        }

        public static SomeUnionType MyObject
        {
            get {
                return new SomeUnionType("myObject");
            }
        }

        public static SomeUnionType Foo
        {
            get {
                return new SomeUnionType("foo");
            }
        }

        public static SomeUnionType Unknown
        {
            get {
                return new SomeUnionType("UNKNOWN");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(SomeUnionType v)
        {
            return v.Value;
        }
        public static SomeUnionType FromString(string v)
        {
            switch (v)
            {
                case "myString":
                    return MyString;
                case "myObject":
                    return MyObject;
                case "foo":
                    return Foo;
                case "UNKNOWN":
                    return Unknown;
                default:
                    throw new ArgumentException("Invalid value for SomeUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((SomeUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// A union demonstrating title and x-speakeasy-name-override on primitive types.
    /// </summary>
    [JsonConverter(typeof(SomeUnion.SomeUnionConverter))]
    public class SomeUnion : Speakeasy.OpenAPI.Utils.IOpenUnion
    {
        public SomeUnion(SomeUnionType type)
        {
            Type = type;
        }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public string? MyString { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public MyObject? MyObject { get; set; }

        [UnionVariant]
        [SpeakeasyMetadata("form:explode=true")]
        public bool? Foo { get; set; }

        public SomeUnionType Type { get; set; }

        [JsonIgnore]
        public JToken? UnknownRaw { get; private set; }

        public static SomeUnion CreateUnknown(JToken raw)
        {
            return new SomeUnion(SomeUnionType.Unknown) { UnknownRaw = raw };
        }

        public bool IsUnknown()
        {
            return Type.Equals(SomeUnionType.Unknown);
        }

        bool Speakeasy.OpenAPI.Utils.IOpenUnion.IsUnknown() => IsUnknown();

        public static SomeUnion CreateMyString(string myString)
        {
            SomeUnionType typ = SomeUnionType.MyString;

            SomeUnion res = new SomeUnion(typ);
            res.MyString = myString;
            return res;
        }
        public static SomeUnion CreateMyObject(MyObject myObject)
        {
            SomeUnionType typ = SomeUnionType.MyObject;

            SomeUnion res = new SomeUnion(typ);
            res.MyObject = myObject;
            return res;
        }
        public static SomeUnion CreateFoo(bool foo)
        {
            SomeUnionType typ = SomeUnionType.Foo;

            SomeUnion res = new SomeUnion(typ);
            res.Foo = foo;
            return res;
        }

        public class SomeUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(SomeUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return CreateUnknown(JValue.CreateNull());
                }

                JToken jt = JToken.Load(reader);
                var unionCandidates = new UnionCandidatePool<SomeUnionType>();
                unionCandidates.Add<string>("MyString", 0, SomeUnionType.MyString);
                unionCandidates.Add<MyObject>("MyObject", 1, SomeUnionType.MyObject);
                unionCandidates.Add<bool>("Foo", 2, SomeUnionType.Foo);

                var (winner, winnerValue) = unionCandidates.PickBest(
                    jt,
                    Utilities.GetDefaultJsonDeserializerSettings()
                );
                if (winner is null || winnerValue is null)
                {
                    return CreateUnknown(jt);
                }

                var result = new SomeUnion(winner.TypeName);
                typeof(SomeUnion).GetProperty(winner.PropertyName)!.SetValue(result, winnerValue);
                return result;
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                SomeUnion res = (SomeUnion)value;

                if (res.IsUnknown())
                {
                    if (res.UnknownRaw != null)
                    {
                        res.UnknownRaw.WriteTo(writer);
                        return;
                    }
                    throw new InvalidOperationException("Unknown union value has no raw payload; construct via CreateUnknown(JToken).");
                }

                if (res.MyString != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MyString));
                    return;
                }

                if (res.MyObject != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MyObject));
                    return;
                }

                if (res.Foo != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Foo));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}