//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.OpenAPI
{
    using Newtonsoft.Json;
    using Speakeasy.OpenAPI.Utils;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class User
    {
        [JsonProperty("id", Required = Newtonsoft.Json.Required.Always)]
        public string Id { get; set; } = default!;

        [JsonProperty("email", Required = Newtonsoft.Json.Required.Always)]
        public string Email { get; set; } = default!;

        [JsonProperty("first_name", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? FirstName { get; set; }

        [JsonProperty("last_name", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? LastName { get; set; }

        [JsonProperty("age", Required = Newtonsoft.Json.Required.DisallowNull)]
        public double? Age { get; set; }

        [JsonProperty("postal_code", Required = Newtonsoft.Json.Required.DisallowNull)]
        public string? PostalCode { get; set; }

        [JsonProperty("gender", Required = Newtonsoft.Json.Required.DisallowNull)]
        public Gender? Gender { get; set; }

        [JsonProperty("associatedIds", Required = Newtonsoft.Json.Required.DisallowNull)]
        public List<string>? AssociatedIds { get; set; }

        [JsonProperty("metadata", Required = Newtonsoft.Json.Required.DisallowNull)]
        public Metadata? Metadata { get; set; }

        /// <summary>
        /// A metadata object with additionalProperties true (any type) - should be flattened.
        /// </summary>
        [JsonProperty("metadataAny", Required = Newtonsoft.Json.Required.DisallowNull)]
        public MetadataAny? MetadataAny { get; set; }
    }
}