//@ts-ignore
const supportedFeatures = {
  acceptHeaders: "0.1.0",
  additionalDependencies: "0.1.0",
  additionalProperties: "0.1.1",
  bigint: "0.1.0",
  constsAndDefaults: "0.1.2",
  core: "1.3.11",
  customSecuritySchemes: "0.1.1",
  decimal: "0.1.0",
  deepObjectParams: "0.1.0",
  defaultEnabledRetries: "0.1.0",
  deprecations: "0.1.0",
  docs: "0.3.3",
  enums: "0.1.0",
  enumUnions: "0.1.0",
  errorUnions: "0.1.0",
  globals: "0.1.0",
  globalSecurity: "0.1.3",
  globalServerURLs: "0.1.2",
  hiddenGlobals: "0.1.0",
  ignores: "0.1.0",
  methodSecurity: "0.1.2",
  methodServerURLs: "0.1.1",
  nameOverrides: "0.1.2",
  nullables: "0.1.0",
  oauth2ClientCredentials: "1.1.8",
  oauth2Password: "0.1.2",
  openEnums: "0.1.0",
  operationTimeout: "0.1.0",
  responseFormat: "0.1.1",
  retries: "0.1.2",
  sdkHooks: "0.3.0",
  serverIDs: "0.1.0",
  sliceUnions: "0.1.0",
  stringNumberFormats: "0.1.0",
  tests: "1.1.3",
  typeOverrides: "0.1.0",
  unions: "0.2.1",
  flattening: "0.1.0",
  mockServer: "0.0.3",
  modelNamespaces: "0.1.1",
};

//@ts-ignore
const implementedReadmeSections = ["installation"];

//@ts-ignore
function isFeatureSupported(feature: string): boolean {
  return feature in supportedFeatures;
}

//@ts-ignore
function isFeatureEnabled(
  feature: string,
  config: Record<string, any>,
): boolean {
  return false;
}

//@ts-ignore
function allSupportedFeatures(): string[] {
  const allFeatures = Object.keys(supportedFeatures);
  return allFeatures.filter((feature) => !isFeatureIgnored(feature));
}

//@ts-ignore
function isFeatureIgnored(feature: string): boolean {
  return [
    // panic: feature "callbacks" recorded but not handled likely not documented in features.ts
    "callbacks",
    "disallowCircularRefs",
    "getRequestBodies",
    "sets",
    "tagBasedOrdering",
    // panic: feature "webhooks" recorded but not handled likely not documented in features.ts
    "webhooks",
  ].includes(feature);
}

//@ts-ignore
function isReadmeSectionImplemented(id: string): boolean {
  return implementedReadmeSections.includes(id);
}

//@ts-ignore
function isReadmeSectionIgnored(id: string): boolean {
  return false;
}

//@ts-ignore
function getStaticallyUsedFeatures(): string[] {
  return ["additionalDependencies", "globalSecurityCallbacks", "sdkHooks"];
}

//@ts-ignore
function getFeatureVersion(feature: string): string {
  return supportedFeatures[feature];
}

//@ts-ignore
function isTestSkipped(test: string): boolean {
  return [
    "event-stream-timeout-still-bounds-slow-stream",
    "event-stream-with-timeout-streams-to-completion",
    "smart-union-nullable-collection-item",
    "smart-union-wrapped-complex-fields",
    "auth-custom-security-option-app-id",
    "auth-custom-security-scheme-app-id",
    "auth-custom-security-scheme-only",
    "auth-function-callbacks-oauth-global-security",
    "auth-global-security-flattening",
    "auth-global-security-flattening-callback",
    "auth-hoisted-basic-auth",
    "auth-hoisted-no-auth-retained",
    "auth-hoisted-operation-auth-retained",
    "auth-multiple-simple-scheme-auth",
    "auth-operation-level-oauth2",
    "cancellation-token-cancelled-before-request",
    "cancellation-token-cancelled-during-request",
    "cancellation-token-cancelled-inside-hook",
    "cancellation-token-no-cancellation",
    "customclient-request-parameters-retained",
    "customclient-request-parameters-retained-legacy",
    "custom-code-region-model-method-with-imports",
    "custom-code-region-sdk-method-with-imports",
    "custom-code-region-sub-sdk-method-with-imports",
    "duplicate-header-parameter-at-operation-level-does-not-error",
    "duplicate-header-parameter-at-path-level-does-not-error",
    "duplicate-path-parameter-at-operation-level-does-not-error",
    "duplicate-path-parameter-at-path-level-does-not-error",
    "duplicate-query-parameter-at-operation-level-does-not-error",
    "duplicate-query-parameter-at-path-level-does-not-error",
    "errors-additional-properties",
    "errors-connection-error",
    "errors-status-get-error300-non-error",
    "errors-status-get-error-default-error-codes",
    "errors-status-get-error-x-speakeasy-errors",
    "errors-union-of-errors",
    "errors-union-of-errors-discriminated",
    "event-stream-chat-sentinel-event",
    "event-stream-chat-skip-sentinel",
    "event-stream-different-data-schemas",
    "event-stream-error-response",
    "event-stream-json-data",
    "event-stream-multiline-data",
    "event-stream-rich-events",
    "event-stream-stay-open-break-early",
    "event-stream-stay-open-sentinel",
    "event-stream-text-data",
    "event-stream-partial-with-comments",
    "event-stream-with-abort-signal",
    "event-stream-wpt-compliance",
    "event-stream-optional-data-field",
    "flattening-component-body-and-param-conflict-flatten-requests",
    "flattening-component-body-and-param-no-conflict-flatten-requests",
    "flattening-conflicting-params-flatten-requests",
    "flattening-inline-body-and-param-conflict-flatten-requests",
    "flattening-inline-body-and-param-no-conflict-flatten-requests",
    "flattening-required-body-all-optional-flatten-requests",
    "globals-header-get-uses-global",
    "globals-header-get-uses-local",
    "globals-header-keeps-custom-client-headers",
    "globals-kebab-case-param-get",
    "globals-operation-params-only",
    "globals-query-parameter-get-uses-global",
    "headers-error-response-headers-none",
    "headers-error-response-headers-optional",
    "headers-empty-response-body-with-headers-flat",
    "headers-response-body-with-headers-flat",
    "hooks-client-credentials-basic-success",
    "hooks-client-credentials-basic-success-alt-token-url",
    "hooks-client-credentials-basic-success-global-server",
    "hooks-oauth2-password-bad-credentials",
    "hooks-oauth2-password-not-required",
    "hooks-oauth2-password-operation-scope",
    "hooks-oauth2-password-operation-security-option",
    "hooks-oauth2-password-token-renewal",
    "hooks-oauth2-password-with-credentials",
    "hooks-oauth2-password-with-token",
    "hooks-terminate-retry-loop",
    "hooks-trigger-retries",
    "jsonl-deserialization-camel-case-properties",
    "jsonl-stream-data-async-chunks-flat-response",
    "jsonl-stream-data-async-envelope-http-responses",
    "jsonl-stream-data-async-flat-response",
    "jsonl-stream-data-chunks-envelope-http-responses",
    "jsonl-stream-data-chunks-flat-response",
    "jsonl-stream-data-envelope-http-responses",
    "jsonl-stream-data-flat-responses",
    "method-trace",
    "no-servers",
    "object-with-optional-false-nullable-false-field-absent",
    "object-with-optional-false-nullable-false-field-null",
    "object-with-optional-false-nullable-false-full",
    "object-with-optional-false-nullable-true-field-absent",
    "object-with-optional-false-nullable-true-field-null",
    "object-with-optional-false-nullable-true-full",
    "object-with-optional-nullable-field-absent",
    "object-with-optional-nullable-field-null",
    "object-with-optional-nullable-full",
    "object-with-optional-true-nullable-false-field-absent",
    "object-with-optional-true-nullable-false-field-null",
    "object-with-optional-true-nullable-false-full",
    "open-enums-round-trip",
    "open-enums-response-usage",
    "pagination-ambiguous-input",
    "pagination-body-flattened-optional-security",
    "pagination-body-flattened-with-security",
    "pagination-body-wrapped-request",
    "pagination-cursor-body",
    "pagination-cursor-non-numeric",
    "pagination-cursor-non-numeric-empty-string",
    "pagination-cursor-non-numeric-nullable",
    "pagination-cursor-non-numeric-with-limit",
    "pagination-cursor-params",
    "pagination-cursor-params-snake",
    "pagination-cursor-response-envelope",
    "pagination-cursor-snake",
    "pagination-encapsulated-parameter",
    "pagination-limit-offset-deep-outputs-page-body",
    "pagination-limit-offset-default-offset-body",
    "pagination-limit-offset-default-offset-params",
    "pagination-limit-offset-nil-offset-params",
    "pagination-limit-offset-nil-page-params",
    "pagination-limit-offset-nullable",
    "pagination-limit-offset-offset-body",
    "pagination-limit-offset-offset-params",
    "pagination-limit-offset-page-body",
    "pagination-limit-offset-page-params",
    "pagination-limit-offset-page-params-const",
    "pagination-limit-offset-page-params-flat",
    "pagination-limit-offset-params-snake",
    "pagination-limit-offset-snake",
    "pagination-limit-offset-union-output-page-params",
    "pagination-limit-offset-union-output-page-params-flat",
    "pagination-limit-offset-zero-page-params",
    "pagination-simple-object-snake",
    "pagination-url",
    "pagination-with-retries",
    "pagination-wrapped-optional-body",
    "pagination-params-wrapped-request",
    "parameters-allow-empty-value",
    "parameters-camel-case",
    "parameters-deep-object-query-params-deep-object",
    "parameters-deep-object-query-params-map",
    "parameters-deep-object-query-params-object",
    "parameters-default-query-params",
    "parameters-form-query-params-camel-object",
    "parameters-form-query-params-object",
    "parameters-form-query-params-primitive",
    "parameters-form-query-params-unions",
    "parameters-header-params-array",
    "parameters-header-params-map",
    "parameters-header-params-object",
    "parameters-header-params-primitive",
    "parameters-mixed-primitives",
    "parameters-open-enum",
    "parameters-ordering-body-first",
    "parameters-ordering-parameters-first",
    "parameters-ordering-using-optional-request-body-body-first",
    "parameters-ordering-using-optional-request-body-parameters-first",
    "parameters-ordering-using-optional-request-body-with-legacy-flattening-order",
    "parameters-ordering-with-legacy-flattening-order",
    "parameters-path-encoding",
    "parameters-pipe-query-params-array",
    "parameters-query-encoding",
    "parameters-simple-path-parameter-arrays",
    "parameters-simple-path-parameter-maps",
    "parameters-simple-path-parameter-objects",
    "parameters-simple-path-parameter-primitives",
    "polling-delay-seconds",
    "polling-delay-seconds-override",
    "polling-failure-criteria-response-body",
    "polling-failure-criteria-response-body-nested",
    "polling-failure-criteria-response-body-optional",
    "polling-failure-criteria-response-body-regex",
    "polling-failure-criteria-status-code",
    "polling-failure-criteria-status-code-regex",
    "polling-interval-seconds",
    "polling-interval-seconds-override",
    "polling-limit-count",
    "polling-limit-count-override",
    "polling-success-criteria-response-body",
    "polling-success-criteria-response-body-nested",
    "polling-success-criteria-response-body-optional",
    "polling-success-criteria-response-body-regex",
    "polling-success-criteria-status-code",
    "polling-success-criteria-status-code-error-known",
    "polling-success-criteria-status-code-error-regex",
    "polling-success-criteria-status-code-error-unknown",
    "polling-success-criteria-status-code-regex",
    "redirects-are-followed",
    "relative-servers",
    "request-bodies-file-upload-extract-content-type",
    "request-bodies-post-application-json-array-camel-case",
    "request-bodies-post-application-json-array-object-camel-case",
    "request-bodies-post-application-json-array-of-array-camel-case",
    "request-bodies-post-application-json-array-of-array-of-primitive",
    "request-bodies-post-application-json-array-of-map-camel-case",
    "request-bodies-post-application-json-deep-camel-case",
    "request-bodies-post-application-json-map-camel-case",
    "request-bodies-post-application-json-map-object-camel-case",
    "request-bodies-post-application-json-map-of-array-camel-case",
    "request-bodies-post-application-json-map-of-map-camel-case",
    "request-bodies-post-application-json-simple-camel-case",
    "request-bodies-post-form-deep",
    "request-bodies-post-form-map-primitive",
    "request-bodies-post-form-simple",
    "request-bodies-post-json-data-types-complex-number-arrays",
    "request-bodies-post-multiple-content-types-component-filtered-application-json",
    "request-bodies-post-multiple-content-types-component-filtered-multipart-form-data",
    "request-bodies-post-multiple-content-types-split-form-with-param",
    "request-bodies-post-multiple-content-types-split-json-with-param",
    "request-bodies-post-multiple-content-types-split-multipart-with-param",
    "request-bodies-put-multipart-deep",
    "request-bodies-put-multipart-file",
    "request-bodies-put-multipart-file-ref",
    "request-bodies-put-multipart-file-streaming",
    "request-bodies-put-multipart-simple",
    "request-bodies-put-bytes-streaming",
    "response-bodies-bytes-get",
    "response-bodies2xx-json-object-all-optional-properties",
    "response-bodies-accept-header-override",
    "response-bodies-overridden-field-names",
    "retries-connect-error",
    "retries-global-config-disable",
    "retries-global-config-success",
    "retries-global-config-timeout",
    "retries-header",
    "retries-request-timeout",
    "retries-retry-connection-errors-reject",
    "retries-retry-connection-errors-reset",
    "retries-succeeds",
    "retries-succeeds-with-body",
    "retries-timeout",
    "servers-global-server-with-invalid-templated-protocol",
    "servers-global-server-with-templated-protocol",
    "servers-override-global-server-url",
    "servers-override-operation-server-url",
    "servers-select-global-server-broken",
    "servers-select-global-server-by-id-broken",
    "servers-select-global-server-by-id-broken-using-builder",
    "servers-select-global-server-by-id-default",
    "servers-select-global-server-by-id-default-using-builder",
    "servers-select-global-server-by-id-invalid",
    "servers-select-global-server-by-id-invalid-using-builder",
    "servers-select-global-server-by-id-valid",
    "servers-select-global-server-by-id-valid-using-builder",
    "servers-select-global-server-by-name-broken",
    "servers-select-global-server-by-name-broken-using-builder",
    "servers-select-global-server-by-name-default",
    "servers-select-global-server-by-name-default-using-builder",
    "servers-select-global-server-by-name-invalid",
    "servers-select-global-server-by-name-valid",
    "servers-select-global-server-by-name-valid-using-builder",
    "servers-select-global-server-by-name-with-templates-broken",
    "servers-select-global-server-by-name-with-templates-broken-using-builder",
    "servers-select-global-server-by-name-with-templates-defaults",
    "servers-select-global-server-by-name-with-templates-defaults-using-builder",
    "servers-select-global-server-by-name-with-templates-valid",
    "servers-select-global-server-by-name-with-templates-valid-using-builder",
    "servers-select-global-server-valid",
    "servers-select-server-with-id-broken",
    "servers-select-server-with-id-default",
    "servers-select-server-with-id-valid",
    "servers-server-by-id-with-templates",
    "servers-server-with-invalid-protocol-template",
    "servers-server-with-protocol-template",
    "servers-server-with-templates",
    "servers-server-with-templates-defaults",
    "servers-server-with-templates-global",
    "servers-server-with-templates-global-defaults",
    "servers-server-with-templates-global-enum",
    "smart-union-all-consts",
    "smart-union-any-field-type",
    "smart-union-array-fields",
    "smart-union-const-field-discrimination",
    "smart-union-deeply-nested-array",
    "smart-union-empty-string",
    "smart-union-nested-structs",
    "smart-union-nested-union",
    "smart-union-nested-union-vs-flat-struct",
    "smart-union-open-enums",
    "smart-union-open-enums-and-size",
    "smart-union-optional-pointer-fields",
    "smart-union-optional-pointer-structs",
    "smart-union-prefers-fewer-unmatched-fields",
    "smart-union-preserves-order-on-tie",
    "smart-union-selects-more-matched-fields",
    "smart-union-three-way-field-discrimination",
    "smart-union-union-vs-union",
    "status-code2-xx",
    "status-code4-xx",
    "status-code5-xx",
    "status-code-default",
    "telemetry-speakeasy-user-agent-get",
    "telemetry-user-agent-get",
    "test-hooks",
    "test-hooks-before-create-request",
    "test-hooks-error",
    "transform-jq-request-response",
    "union-enum-nested-in-array-in-union",
    "union-enum-array-deserialization",
    "unions-array-of-discriminated-unions",
    "unions-array-of-discriminated-unions-map",
    "unions-bigint-str-decimal",
    "unions-collections-one-of-post",
    "unions-date-null",
    "unions-datetime-bigint",
    "unions-datetime-null",
    "unions-extra-json-properties",
    "unions-flattened-typed-object-post-obj1",
    "unions-mixed-type-one-of-post-integer",
    "unions-mixed-type-one-of-post-object",
    "unions-mixed-type-one-of-post-string",
    "unions-mixed-union-types",
    "unions-nested-array-of-discriminated-unions",
    "unions-nested-enums-form",
    "unions-nested-enums-multipart",
    "unions-nullable-oneof-ref-in-object-post",
    "unions-nullable-oneof-schema-post-null",
    "unions-nullable-oneof-schema-post-obj1",
    "unions-nullable-oneof-schema-post-obj2",
    "unions-nullable-oneof-type-in-object-post",
    "unions-nullable-typed-object-post-null",
    "unions-nullable-typed-object-post-obj1",
    "unions-one-of-boolean-and-string-enum-with-response-boolean",
    "unions-one-of-boolean-and-string-enum-with-response-enum",
    "unions-optional-union-map",
    "unions-primitive-type-one-of-post-boolean",
    "unions-primitive-type-one-of-post-integer",
    "unions-primitive-type-one-of-post-number",
    "unions-primitive-type-one-of-post-string",
    "unions-strongly-typed-nullable-one-of-post",
    "unions-strongly-typed-one-of-post-basic",
    "unions-strongly-typed-one-of-post-deep",
    "unions-strongly-typed-one-of-post-with-non-standard-discriminator-name",
    "unions-typed-object-nullable-one-of-post-null",
    "unions-typed-object-nullable-one-of-post-obj1",
    "unions-typed-object-nullable-one-of-post-obj2",
    "unions-typed-object-one-of-post-null",
    "unions-typed-object-one-of-post-obj1",
    "unions-typed-object-one-of-post-obj2",
    "unions-typed-object-one-of-post-obj3",
    "unions-union-map",
    "unions-weakly-typed-one-of-post-basic",
    "unions-weakly-typed-one-of-post-deep",
    "unions-discriminated-open-enum",
    "unknown",
    "unwieldy-get",
    "webhooks-consume",
    "webhooks-consume-bad-data",
    "webhooks-consume-bad-signature",
    "webhooks-consume-custom-security",
    "x-ndjson-stream-data-async-chunks-envelope-http-responses",
    "x-ndjson-stream-data-async-envelope-http-responses",
    "x-ndjson-stream-data-chunks-envelope-http-responses",
    "x-ndjson-stream-data-envelope-http-responses",
    "custom-client-http-proxy",
    "open-union-embedded",
    "open-union-known-variant",
    "open-union-smart-union-interop",
    "open-union-invalid-payload",
    "open-union-known-disc-invalid-schema",
    "open-union-missing-discriminator",
    "open-union-unknown-discriminator",
    "event-stream-union-with-standalone-comments",
    "unions-const-discriminator",
    "unions-discriminated-multiple-memberships",
    "event-stream-mixed-data",
    "event-stream-chat-heartbeat-skips-dataless",
    "pagination-cursor-nullable-limit",
    "timeout-ms-override-allows-completion",
    "timeout-ms-override-is-respected",
    "pagination-nullable-limit-cursor",
    "request-bodies-complex-number-types-optional-unpopulated",
    "request-bodies-complex-number-types-required-missing",
    "flattening-nullable-body-with-required-param-ordering",
    "errors-status-get-error-x-speakeasy-errors-default",
    "errors-status-get-error-x-speakeasy-errors-none",
    "retries-timeout-fresh-signal",
    "auth-global-security-flattening-env-var-fallback",
    "request-bodies-base64-input-mode-file-shared-component",
    "request-bodies-base64-input-mode-file-split-components",
    "event-stream-chat-json",
    "unions-strongly-typed-one-of-discriminated-post",
    "event-stream-sse-overload-json-response",
    "event-stream-sse-overload-streaming-response",
    "raw-response-helpers-strip-internal-header",
    "unions-typed-object-one-of-post-body-less-throws",
    "request-bodies-put-multipart-file-bytesio",
    "request-bodies-put-multipart-file-handle",
    "request-bodies-put-multipart-file-stringio",
    "request-extras-extra-body-merged",
    "request-extras-extra-body-overrides",
    "request-extras-extra-body-rejects-non-json",
    "request-extras-extra-query-appended",
    "request-extras-extra-query-merged",
    "request-extras-extra-query-nullish-arrays",
    "request-extras-extra-query-object-json",
    "request-extras-extra-query-overrides",
    "request-extras-extra-query-preserves-server-url-query",
    "request-extras-extra-query-security-overrides",
    "collections-map-input-accepts-non-dict-mapping",
    "collections-parameter-annotations-advertise-iterables",
    "collections-parameters-accept-iterables",
    "collections-parameters-accept-iterables-direct",
    "pagination-cursor-deep-nested-outputs",
    "pagination-cursor-deep-nested-outputs-iterator",
    "event-stream-large-event-small-chunks",
    "event-stream-split-boundaries",
    "request-bodies-base64-file-input-idempotent",
    "errors-error-body-validation-disabled",
    "errors-error-body-validation-enabled",
    "errors-response-body-validation-disabled",
    "errors-custom-error-inheritance",
    "errors-response-body-validation-enabled",
    "errors-schema-validation-disabled",
    "errors-schema-validation-enabled",
    "errors-optional-nullable-error-message",
    "errors-optional-nullable-error-message-nested",
    "retries-status-codes-override",
    "retries-status-codes-override-global",
    "retries-status-codes-override-default",
    "errors-response-body-validation-lenient",
    "hooks-access-operation-metadata",
    "request-bodies-duration-format",
    "request-bodies-uuid-format",
    "react-query-builders-key-distinct-bodies",
    "react-query-key-includes-parameters-and-request-body",
    "react-query-key-includes-request-body",
    "react-query-key-opt-in-infers-query-type",
    "smart-union-nested-union-vs-nested-union",
    "request-bodies-put-multipart-optional-nullable",
    "request-bodies-post-form-optional-nullable",
    "request-bodies-post-json-optional-nullable",
    "smart-union-nullable-union-nullable-fields",
    "request-bodies-post-form-optional-nullable-json-shared",
    "request-bodies-put-multipart-optional-nullable-json-shared",
    "request-bodies-post-json-optional-nullable-body-and-param",
    "pagination-limit-offset-page-body-nullable",
    "pagination-limit-offset-page-body-optional-nullable",
    "pagination-cursor-nullable-results",
    "retries-binary-request-body",
    "retries-header-http-date-beyond-max-interval",
    "retries-header-rate-limit-reset",
    "errors-error-body-validation-lenient",
    "errors-response-body-validation-lenient-non-json",
    "errors-response-body-validation-lenient-union-variant",
    "event-stream-malformed-frame-lenient",
    "event-stream-malformed-frame-strict",
    "agent-mode-does-not-leak-between-invocations",
    "catalog-lists-values",
    "catalog-rejects-positional-argument",
    "catalog-structured-output",
    "cli-exit-code-bare-intent",
    "cli-exit-code-connection-and-agent-block",
    "cli-exit-code-mapping-tables",
    "cli-exit-code-reason-first",
    "cli-exit-code-root-unknown-message",
    "cli-exit-code-single-envelope",
    "cli-exit-code-success-and-discovery",
    "cli-exit-codes-rendering-modes",
    "client-credentials-dry-run-token-and-api",
    "clierrors-agent-mode-explicitly-disabled",
    "clierrors-agent-mode-from-environment",
    "clierrors-agent-mode-matrix",
    "clierrors-api-error-not-double-wrapped",
    "clierrors-declared-hints-fire",
    "clierrors-flag-values-not-rendering-flags",
    "clierrors-invalid-values-do-not-stop-preparse",
    "clierrors-json-output-envelope",
    "clierrors-plain-mode-classified",
    "clierrors-typed-reasons",
    "error-taxonomy-declared-rules-and-ordering",
    "error-taxonomy-every-closed-type-has-a-hint",
    "error-taxonomy-fallback-message-omits-raw-body",
    "error-taxonomy-hint-precedence-and-dedupe",
    "error-taxonomy-jq-uses-structured-envelope",
    "error-taxonomy-odd-bodies-use-fallback-envelope",
    "error-taxonomy-odd-reflection-fields-do-not-panic",
    "error-taxonomy-origin-semantics",
    "error-taxonomy-pretty-http-status-without-reason",
    "error-taxonomy-pretty-json-agent-parity",
    "error-taxonomy-pretty-residual-details",
    "error-taxonomy-reserved-keys-and-rendered-classification",
    "event-stream-connection-refused-stays-connection-error",
    "event-stream-decode-failure-is-protocol-error",
    "event-stream-decode-failure-without-json-error-type",
    "event-stream-error-event-agent-mode",
    "event-stream-error-event-agent-mode-fallback",
    "event-stream-error-event-exits-non-zero",
    "event-stream-error-event-pretty",
    "event-stream-numbers-keep-precision",
    "event-stream-server-error-mentioning-decode-is-not-protocol-error",
    "event-stream-timeout-still-bounds-slow-stream",
    "event-stream-undiscriminated-error-shaped-variant-is-data",
    "event-stream-union-events-render-wire-shape",
    "hooks-custom-user-agent",
    "intent-dispatch-resolves-stdin-once",
    "intent-dispatch-select-matrix",
    "intent-interactive-piped-body-skips-prompts",
    "intent-route-dispatch-agent-envelope",
    "intent-route-dispatch-bare-help",
    "intent-route-dispatch-body-evidence",
    "intent-route-dispatch-conflicting-evidence",
    "intent-route-dispatch-default-required",
    "intent-route-dispatch-flag-paths",
    "intent-route-dispatch-help-usage",
    "intent-route-dispatch-interactive-plan",
    "intent-route-dispatch-override-once",
    "intents-both-body-surfaces-merged",
    "intents-discriminated-partial-body",
    "intents-foreign-selector-agent-envelope",
    "intents-foreign-selector-usage-error",
    "intents-non-object-body-falls-through",
    "intents-partial-body-keeps-presets",
    "intents-partial-body-user-keys-win",
    "intents-preset-from-args",
    "intents-preset-merge-matrix",
    "intents-undeclared-nested-group-order",
    "pre-request-connection-classifier-typed-table",
    "pre-request-discriminated-root-union-messages",
    "pre-request-dry-run-unresolvable-host",
    "pre-request-generated-required-union-paths-and-optionality",
    "pre-request-generated-required-union-positive-echoes",
    "pre-request-real-connection-failures",
    "pre-request-silent-stdin-times-out-on-root-union",
    "pre-request-validation-envelope-matrix",
    "request-bodies-complex-number-types-bigint-overflow",
    "request-shape-body-agent-variant",
    "request-shape-body-and-whole-body-flag-rejected",
    "request-shape-body-both-selectors-rejected",
    "request-shape-body-default-selector-merges",
    "request-shape-body-null-optional-key-allowed",
    "request-shape-body-typo-key-rejected",
    "request-shape-expanded-body-typo-key-lenient-warning",
    "request-shape-expanded-body-typo-key-rejected",
    "request-shape-intent-bare-usage",
    "request-shape-intent-empty-stdin-usage",
    "request-shape-intent-flag-and-body-conflict",
    "request-shape-intent-flag-merged-into-body",
    "request-shape-intent-positional-and-body-conflict",
    "request-shape-intent-positional-merged-into-body",
    "request-shape-intent-positional-merged-into-whole-body-flag",
    "request-shape-intent-stdin-runs-request",
    "request-shape-intent-stdin-typo-key-rejected",
    "request-shape-intent-stdin-with-positional",
    "request-shape-intent-synthesized-body",
    "request-shape-intent-zero-value-flag-merged",
    "request-shape-nested-union-agent-selector-no-default",
    "request-shape-nested-union-body-default-selector-merges",
    "request-shape-nested-union-own-flag-default-selector-merges",
    "request-shape-nested-union-stdin-default-selector-merges",
    "request-shape-open-schema-keeps-unknown-keys",
    "request-shape-stdin-typo-key-rejected",
    "request-shape-whole-body-flag-typo-key-rejected",
    "request-shape-whole-body-flag-wins-over-stdin",
    "security-ranking-both-flags",
    "security-ranking-env-only",
    "security-ranking-env-tie",
    "security-ranking-flag-beats-env",
    "security-ranking-operation-restriction",
    "security-ranking-pick-matrix",
    "security-ranking-source-rank",
    "event-stream-with-operation-timeout-streams-to-completion",
    "jsonl-stream-timeout-still-bounds-slow-stream",
    "jsonl-stream-with-timeout-streams-to-completion",
    "open-union-strict-request-validation",
  ].includes(test);
}

//@ts-ignore
function getAutoGeneratedHeader(
  generatedId: string,
  config: Record<string, any>,
): string {
  let header = `/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.`;
  if (generatedId) {
    header += `\n * @generated-id: ${generatedId}`;
  }
  if (config.GeneratedLicense === "agpl") {
    header +=
      "\n * Generated under the AGPL-3.0-only license." +
      "\n * SPDX-License-Identifier: AGPL-3.0-only";
  }
  header += `\n */\n\n`;
  return header;
}

// @ts-ignore
function collectGlobalsAndServersModels(): boolean {
  return true;
}
