# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Components

    class MyApiKey
      extend T::Sig
      include Crystalline::MetadataFields

      field(
        :my_api_key,
        ::String,
        {'security': {'scheme': true, 'type': "apiKey", 'sub_type': "header", 'field_name': "api_key"}}
      )

      sig { params(my_api_key: ::String).void }
      def initialize(my_api_key:)
        @my_api_key = my_api_key
      end

      sig { params(other: T.untyped).returns(T::Boolean) }
      def ==(other)
        return false unless other.is_a?(self.class)
        return false unless @my_api_key == other.my_api_key
        true
      end
    end
  end
end
