/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;
import static org.openapis.openapi.operations.Operations.AsyncRequestlessOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.foo.Pet;
import org.openapis.openapi.models.operations.async.CreateNamespaceConflictRequestBuilder;
import org.openapis.openapi.models.operations.async.CreateNamespaceConflictResponse;
import org.openapis.openapi.models.operations.async.GetNamespaceConflictRequestBuilder;
import org.openapis.openapi.models.operations.async.GetNamespaceConflictResponse;
import org.openapis.openapi.models.operations.async.GetPetOwnersRequestBuilder;
import org.openapis.openapi.models.operations.async.GetPetOwnersResponse;
import org.openapis.openapi.models.operations.async.GetTripleNamespaceConflictRequestBuilder;
import org.openapis.openapi.models.operations.async.GetTripleNamespaceConflictResponse;
import org.openapis.openapi.models.operations.async.PutNamespaceConflictRequestBuilder;
import org.openapis.openapi.models.operations.async.PutNamespaceConflictResponse;
import org.openapis.openapi.models.shared.ObjWithRenamedProperties;
import org.openapis.openapi.operations.CreateNamespaceConflict;
import org.openapis.openapi.operations.GetNamespaceConflict;
import org.openapis.openapi.operations.GetPetOwners;
import org.openapis.openapi.operations.GetTripleNamespaceConflict;
import org.openapis.openapi.operations.PutNamespaceConflict;
import org.openapis.openapi.utils.Headers;

public class AsyncConflicts {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Conflicts syncSDK;

    AsyncConflicts(Conflicts syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     *
     * @return The sync SDK
     */
    public Conflicts toSync() {
        return syncSDK;
    }

    /**
     * Get Namespace Conflict Test
     *
     * <p>This endpoint tests the x-speakeasy-model-namespace extension by returning
     * a model that references two different Pet types from different namespaces.
     * The SDK should properly import and alias both Pet types.
     *
     * @return The async call builder
     */
    public GetNamespaceConflictRequestBuilder getNamespaceConflict() {
        return new GetNamespaceConflictRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Namespace Conflict Test
     *
     * <p>This endpoint tests the x-speakeasy-model-namespace extension by returning
     * a model that references two different Pet types from different namespaces.
     * The SDK should properly import and alias both Pet types.
     *
     * @return {@code CompletableFuture<GetNamespaceConflictResponse>} - The async response
     */
    public CompletableFuture<GetNamespaceConflictResponse> getNamespaceConflictDirect() {
        AsyncRequestlessOperation<GetNamespaceConflictResponse> operation =
                new GetNamespaceConflict.Async(sdkConfiguration, _headers);
        return operation.doRequest().thenCompose(operation::handleResponse);
    }

    /**
     * Put Property Name Conflicts Behind
     *
     * <p>This endpoint tests property name conflict resolution through
     * x-speakeasy-name-override and x-speakeasy-model-namespace extensions.
     *
     * @return The async call builder
     */
    public PutNamespaceConflictRequestBuilder putNamespaceConflict() {
        return new PutNamespaceConflictRequestBuilder(sdkConfiguration);
    }

    /**
     * Put Property Name Conflicts Behind
     *
     * <p>This endpoint tests property name conflict resolution through
     * x-speakeasy-name-override and x-speakeasy-model-namespace extensions.
     *
     * @return {@code CompletableFuture<PutNamespaceConflictResponse>} - The async response
     */
    public CompletableFuture<PutNamespaceConflictResponse> putNamespaceConflictDirect() {
        return putNamespaceConflict(null);
    }

    /**
     * Put Property Name Conflicts Behind
     *
     * <p>This endpoint tests property name conflict resolution through
     * x-speakeasy-name-override and x-speakeasy-model-namespace extensions.
     *
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<PutNamespaceConflictResponse>} - The async response
     */
    public CompletableFuture<PutNamespaceConflictResponse> putNamespaceConflict(
            @Nullable ObjWithRenamedProperties request) {
        AsyncRequestOperation<ObjWithRenamedProperties, PutNamespaceConflictResponse> operation =
                new PutNamespaceConflict.Async(sdkConfiguration, _headers);
        return operation.doRequest(request).thenCompose(operation::handleResponse);
    }

    /**
     * Create Namespace Conflict Test
     *
     * <p>This endpoint tests creating with models from different namespaces.
     * Uses foo.Pet in the request and bar.Pet in the response.
     *
     * @return The async call builder
     */
    public CreateNamespaceConflictRequestBuilder createNamespaceConflict() {
        return new CreateNamespaceConflictRequestBuilder(sdkConfiguration);
    }

    /**
     * Create Namespace Conflict Test
     *
     * <p>This endpoint tests creating with models from different namespaces.
     * Uses foo.Pet in the request and bar.Pet in the response.
     *
     * @param request The request object containing all the parameters for the API call.
     * @return {@code CompletableFuture<CreateNamespaceConflictResponse>} - The async response
     */
    public CompletableFuture<CreateNamespaceConflictResponse> createNamespaceConflict(@Nonnull Pet request) {
        AsyncRequestOperation<Pet, CreateNamespaceConflictResponse> operation =
                new CreateNamespaceConflict.Async(sdkConfiguration, _headers);
        return operation.doRequest(request).thenCompose(operation::handleResponse);
    }

    /**
     * Get Triple Namespace Conflict Test
     *
     * <p>This endpoint tests the x-speakeasy-model-namespace extension by returning
     * a model that references three different Pet types from different namespaces.
     * The SDK should properly import and alias all three Pet types.
     *
     * @return The async call builder
     */
    public GetTripleNamespaceConflictRequestBuilder getTripleNamespaceConflict() {
        return new GetTripleNamespaceConflictRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Triple Namespace Conflict Test
     *
     * <p>This endpoint tests the x-speakeasy-model-namespace extension by returning
     * a model that references three different Pet types from different namespaces.
     * The SDK should properly import and alias all three Pet types.
     *
     * @return {@code CompletableFuture<GetTripleNamespaceConflictResponse>} - The async response
     */
    public CompletableFuture<GetTripleNamespaceConflictResponse> getTripleNamespaceConflictDirect() {
        AsyncRequestlessOperation<GetTripleNamespaceConflictResponse> operation =
                new GetTripleNamespaceConflict.Async(sdkConfiguration, _headers);
        return operation.doRequest().thenCompose(operation::handleResponse);
    }

    /**
     * Get Pet Owners
     *
     * <p>This endpoint tests using PetOwner models from different namespaces.
     * Returns both foo.PetOwner and bar.PetOwner in the response.
     *
     * @return The async call builder
     */
    public GetPetOwnersRequestBuilder getPetOwners() {
        return new GetPetOwnersRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Pet Owners
     *
     * <p>This endpoint tests using PetOwner models from different namespaces.
     * Returns both foo.PetOwner and bar.PetOwner in the response.
     *
     * @return {@code CompletableFuture<GetPetOwnersResponse>} - The async response
     */
    public CompletableFuture<GetPetOwnersResponse> getPetOwnersDirect() {
        AsyncRequestlessOperation<GetPetOwnersResponse> operation = new GetPetOwners.Async(sdkConfiguration, _headers);
        return operation.doRequest().thenCompose(operation::handleResponse);
    }
}
