/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.AsyncRequestlessOperation;

import jakarta.annotation.Nullable;
import java.lang.Deprecated;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapis.openapi.models.operations.async.Deprecated1RequestBuilder;
import org.openapis.openapi.models.operations.async.Deprecated1Response;
import org.openapis.openapi.operations.Deprecated1;
import org.openapis.openapi.utils.Headers;

/**
 * A subSDK in which all operations are deprecated.
 */
public class AsyncObsolete {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final Obsolete syncSDK;

    AsyncObsolete(Obsolete syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     *
     * @return The sync SDK
     */
    public Obsolete toSync() {
        return syncSDK;
    }

    /**
     * Deprecated Operation
     *
     * @return The async call builder
     * @deprecated method: This endpoint is deprecated.. Use getRequestBodyFlattenedAway instead.
     */
    @Deprecated
    public Deprecated1RequestBuilder deprecated1() {
        return new Deprecated1RequestBuilder(sdkConfiguration);
    }

    /**
     * Deprecated Operation
     *
     * @return {@code CompletableFuture<Deprecated1Response>} - The async response
     * @deprecated method: This endpoint is deprecated.. Use getRequestBodyFlattenedAway instead.
     */
    @Deprecated
    public CompletableFuture<Deprecated1Response> deprecated1Direct() {
        return deprecated1(null);
    }

    /**
     * Deprecated Operation
     *
     * @param serverURL Overrides the server URL.
     * @return {@code CompletableFuture<Deprecated1Response>} - The async response
     * @deprecated method: This endpoint is deprecated.. Use getRequestBodyFlattenedAway instead.
     */
    @Deprecated
    public CompletableFuture<Deprecated1Response> deprecated1(@Nullable String serverURL) {
        AsyncRequestlessOperation<Deprecated1Response> operation =
                new Deprecated1.Async(sdkConfiguration, serverURL, _headers);
        return operation.doRequest().thenCompose(operation::handleResponse);
    }
}
