// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// LoginResponseBody - OK
type LoginResponseBody struct {
	Token string `json:"token"`
}

func (o *LoginResponseBody) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

type LoginResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *LoginResponseBody
}

func (o *LoginResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *LoginResponse) GetObject() *LoginResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
