// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/shared"
	"net/http"
)

type CreateOasEnumResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	OASEnumResponse *shared.OASEnumResponse
}

func (c *CreateOasEnumResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOasEnumResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOasEnumResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOasEnumResponse) GetOASEnumResponse() *shared.OASEnumResponse {
	if c == nil {
		return nil
	}
	return c.OASEnumResponse
}
