// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/shared"
	"net/http"
)

type CreateRootUnionWriteonlyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created
	RootUnionWriteOnly *shared.RootUnionWriteOnlyOutput
}

func (c *CreateRootUnionWriteonlyResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateRootUnionWriteonlyResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateRootUnionWriteonlyResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateRootUnionWriteonlyResponse) GetRootUnionWriteOnly() *shared.RootUnionWriteOnlyOutput {
	if c == nil {
		return nil
	}
	return c.RootUnionWriteOnly
}

func (c *CreateRootUnionWriteonlyResponse) GetRootUnionWriteOnlyAlpha() *shared.RootUnionWriteOnlyAlphaOutput {
	if v := c.GetRootUnionWriteOnly(); v != nil {
		return v.RootUnionWriteOnlyAlphaOutput
	}
	return nil
}

func (c *CreateRootUnionWriteonlyResponse) GetRootUnionWriteOnlyBeta() *shared.RootUnionWriteOnlyBetaOutput {
	if v := c.GetRootUnionWriteOnly(); v != nil {
		return v.RootUnionWriteOnlyBetaOutput
	}
	return nil
}
