// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteOasDeprecatedRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteOasDeprecatedRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteOasDeprecatedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteOasDeprecatedResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteOasDeprecatedResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteOasDeprecatedResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
