// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteImportMultipleIDRequest struct {
	Param1 string `pathParam:"style=simple,explode=false,name=param1"`
	Param2 string `pathParam:"style=simple,explode=false,name=param2"`
}

func (d *DeleteImportMultipleIDRequest) GetParam1() string {
	if d == nil {
		return ""
	}
	return d.Param1
}

func (d *DeleteImportMultipleIDRequest) GetParam2() string {
	if d == nil {
		return ""
	}
	return d.Param2
}

type DeleteImportMultipleIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteImportMultipleIDResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteImportMultipleIDResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteImportMultipleIDResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
