// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterData struct {
	RequestString *string `json:"request_string,omitempty"`
}

func (g *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterData) GetRequestString() *string {
	if g == nil {
		return nil
	}
	return g.RequestString
}

// #region class-body-getrequestbodyrequiredinlinexspeakeasyentitylevel2withparameterdata
// #endregion class-body-getrequestbodyrequiredinlinexspeakeasyentitylevel2withparameterdata

// GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterRequestBody - Intentionally required request body
type GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterRequestBody struct {
	Data *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterData `json:"data,omitempty"`
}

func (g *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterRequestBody) GetData() *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterData {
	if g == nil {
		return nil
	}
	return g.Data
}

// #region class-body-getrequestbodyrequiredinlinexspeakeasyentitylevel2withparameterrequestbody
// #endregion class-body-getrequestbodyrequiredinlinexspeakeasyentitylevel2withparameterrequestbody

type GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterRequest struct {
	// Intentional query parameter
	QueryParam *int64 `queryParam:"style=form,explode=true,name=queryParam"`
	// Intentionally required request body
	RequestBody GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterRequestBody `request:"mediaType=application/json"`
}

func (g *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterRequest) GetQueryParam() *int64 {
	if g == nil {
		return nil
	}
	return g.QueryParam
}

func (g *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterRequest) GetRequestBody() GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterRequestBody {
	if g == nil {
		return GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterRequestBody{}
	}
	return g.RequestBody
}

// #region class-body-getrequestbodyrequiredinlinexspeakeasyentitylevel2withparameterrequest
// #endregion class-body-getrequestbodyrequiredinlinexspeakeasyentitylevel2withparameterrequest

// GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterResponseBody - OK
type GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterResponseBody struct {
	ResponseString *string `json:"response_string,omitempty"`
}

func (g *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterResponseBody) GetResponseString() *string {
	if g == nil {
		return nil
	}
	return g.ResponseString
}

// #region class-body-getrequestbodyrequiredinlinexspeakeasyentitylevel2withparameterresponsebody
// #endregion class-body-getrequestbodyrequiredinlinexspeakeasyentitylevel2withparameterresponsebody

type GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterResponseBody
}

func (g *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterResponse) GetObject() *GetRequestbodyRequiredInlineXspeakeasyentityLevel2WithparameterResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

// #region class-body-getrequestbodyrequiredinlinexspeakeasyentitylevel2withparameterresponse
// #endregion class-body-getrequestbodyrequiredinlinexspeakeasyentitylevel2withparameterresponse
