// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

// GetRequestbodyRequiredRefXspeakeasyentityLevel1ResponseBody - OK
type GetRequestbodyRequiredRefXspeakeasyentityLevel1ResponseBody struct {
	ResponseString *string `json:"response_string,omitempty"`
}

func (g *GetRequestbodyRequiredRefXspeakeasyentityLevel1ResponseBody) GetResponseString() *string {
	if g == nil {
		return nil
	}
	return g.ResponseString
}

// #region class-body-getrequestbodyrequiredrefxspeakeasyentitylevel1responsebody
// #endregion class-body-getrequestbodyrequiredrefxspeakeasyentitylevel1responsebody

type GetRequestbodyRequiredRefXspeakeasyentityLevel1Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *GetRequestbodyRequiredRefXspeakeasyentityLevel1ResponseBody
}

func (g *GetRequestbodyRequiredRefXspeakeasyentityLevel1Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetRequestbodyRequiredRefXspeakeasyentityLevel1Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetRequestbodyRequiredRefXspeakeasyentityLevel1Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetRequestbodyRequiredRefXspeakeasyentityLevel1Response) GetObject() *GetRequestbodyRequiredRefXspeakeasyentityLevel1ResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}

// #region class-body-getrequestbodyrequiredrefxspeakeasyentitylevel1response
// #endregion class-body-getrequestbodyrequiredrefxspeakeasyentitylevel1response
