// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/shared"
	"net/http"
)

// ListXClientFilterArrayResponseBody - OK
type ListXClientFilterArrayResponseBody struct {
	Data []shared.XClientFilterArrayItem `json:"data,omitempty"`
}

func (l *ListXClientFilterArrayResponseBody) GetData() []shared.XClientFilterArrayItem {
	if l == nil {
		return nil
	}
	return l.Data
}

type ListXClientFilterArrayResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *ListXClientFilterArrayResponseBody
}

func (l *ListXClientFilterArrayResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListXClientFilterArrayResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListXClientFilterArrayResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListXClientFilterArrayResponse) GetObject() *ListXClientFilterArrayResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
