// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/shared"
	"net/http"
)

type UpdateUndiscriminatedUnionArrayResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	UndiscriminatedUnionArrayResponse *shared.UndiscriminatedUnionArrayResponse
}

func (u *UpdateUndiscriminatedUnionArrayResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateUndiscriminatedUnionArrayResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateUndiscriminatedUnionArrayResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateUndiscriminatedUnionArrayResponse) GetUndiscriminatedUnionArrayResponse() *shared.UndiscriminatedUnionArrayResponse {
	if u == nil {
		return nil
	}
	return u.UndiscriminatedUnionArrayResponse
}
