// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/shared"
	"net/http"
)

type UpdateXMatchPriorStateRequest struct {
	// The current name of the resource (should use prior state value in updates)
	Name                          string                               `pathParam:"style=simple,explode=false,name=name"`
	XMatchPriorStateUpdateRequest shared.XMatchPriorStateUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateXMatchPriorStateRequest) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateXMatchPriorStateRequest) GetXMatchPriorStateUpdateRequest() shared.XMatchPriorStateUpdateRequest {
	if u == nil {
		return shared.XMatchPriorStateUpdateRequest{}
	}
	return u.XMatchPriorStateUpdateRequest
}

type UpdateXMatchPriorStateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	XMatchPriorStateResponse *shared.XMatchPriorStateResponse
}

func (u *UpdateXMatchPriorStateResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateXMatchPriorStateResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateXMatchPriorStateResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateXMatchPriorStateResponse) GetXMatchPriorStateResponse() *shared.XMatchPriorStateResponse {
	if u == nil {
		return nil
	}
	return u.XMatchPriorStateResponse
}
