// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/shared"
	"net/http"
)

type UpdateXSpeakeasyAdditionalPropertiesNameRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Additional parameter to verify operations scope request type handling
	Slug                      string                           `pathParam:"style=simple,explode=false,name=slug"`
	XAdditionalPropertiesName shared.XAdditionalPropertiesName `request:"mediaType=application/json"`
}

func (u *UpdateXSpeakeasyAdditionalPropertiesNameRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateXSpeakeasyAdditionalPropertiesNameRequest) GetSlug() string {
	if u == nil {
		return ""
	}
	return u.Slug
}

func (u *UpdateXSpeakeasyAdditionalPropertiesNameRequest) GetXAdditionalPropertiesName() shared.XAdditionalPropertiesName {
	if u == nil {
		return shared.XAdditionalPropertiesName{}
	}
	return u.XAdditionalPropertiesName
}

type UpdateXSpeakeasyAdditionalPropertiesNameResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	XAdditionalPropertiesNameResponse *shared.XAdditionalPropertiesNameResponse
}

func (u *UpdateXSpeakeasyAdditionalPropertiesNameResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateXSpeakeasyAdditionalPropertiesNameResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateXSpeakeasyAdditionalPropertiesNameResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateXSpeakeasyAdditionalPropertiesNameResponse) GetXAdditionalPropertiesNameResponse() *shared.XAdditionalPropertiesNameResponse {
	if u == nil {
		return nil
	}
	return u.XAdditionalPropertiesNameResponse
}
