// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tag3

import (
	"github.com/spf13/cobra"
	"openapi/internal/usage"
)

func InitTag3Root(parent *cobra.Command) error {
	var Tag3Cmd = &cobra.Command{
		Use:         "tag3",
		Short:       "Operations for tag3",
		Long:        "Operations for tag3",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initPostTestCmd(Tag3Cmd); err != nil {
		return err
	}

	parent.AddCommand(Tag3Cmd)
	return nil
}
