<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Baz;


class Namespaced
{
    /**
     *
     * @var ?string $namespace
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('namespace')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $namespace = null;

    /**
     * @param  ?string  $namespace
     * @phpstan-pure
     */
    public function __construct(?string $namespace = 'baz')
    {
        $this->namespace = $namespace;
    }
}