/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type AssetNoteStep = {
  type: "note";
  text?: string | undefined;
};

/** @internal */
export const AssetNoteStep$inboundSchema: z.ZodMiniType<
  AssetNoteStep,
  unknown
> = z.object({
  type: types.literal("note"),
  text: types.optional(types.string()),
});

export function assetNoteStepFromJSON(
  jsonString: string,
): SafeParseResult<AssetNoteStep, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssetNoteStep$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssetNoteStep' from JSON`,
  );
}
