/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as discriminatedUnionTypes from "../types/discriminatedUnion.js";
import { discriminatedUnion } from "../types/discriminatedUnion.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AssetNoteStep, AssetNoteStep$inboundSchema } from "./assetnotestep.js";
import {
  AssetOutputStep,
  AssetOutputStep$inboundSchema,
} from "./assetoutputstep.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export enum Status {
  InProgress = "in_progress",
  Completed = "completed",
  Failed = "failed",
  RequiresAction = "requires_action",
}
export type StatusOpen = OpenEnum<typeof Status>;

export type Step =
  | AssetNoteStep
  | AssetOutputStep
  | discriminatedUnionTypes.Unknown<"type">;

/**
 * The result of a render request.
 */
export type AssetResult = {
  id?: string | undefined;
  status?: StatusOpen | undefined;
  steps?:
    | Array<
      AssetNoteStep | AssetOutputStep | discriminatedUnionTypes.Unknown<"type">
    >
    | undefined;
};

/** @internal */
export const Status$inboundSchema: z.ZodMiniType<StatusOpen, unknown> =
  openEnums.inboundSchema(Status);

/** @internal */
export const Step$inboundSchema: z.ZodMiniType<Step, unknown> =
  discriminatedUnion("type", {
    note: AssetNoteStep$inboundSchema,
    output: AssetOutputStep$inboundSchema,
  });

export function stepFromJSON(
  jsonString: string,
): SafeParseResult<Step, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Step$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Step' from JSON`,
  );
}

/** @internal */
export const AssetResult$inboundSchema: z.ZodMiniType<AssetResult, unknown> = z
  .object({
    id: types.optional(types.string()),
    status: types.optional(Status$inboundSchema),
    steps: types.optional(
      z.array(
        discriminatedUnion("type", {
          note: AssetNoteStep$inboundSchema,
          output: AssetOutputStep$inboundSchema,
        }),
      ),
    ),
  });

export function assetResultFromJSON(
  jsonString: string,
): SafeParseResult<AssetResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssetResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssetResult' from JSON`,
  );
}
