/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type Test2Response = {
  test2?: string | null | undefined;
  someConst?: "someConstValue" | undefined;
  /**
   * A required but nullable field to verify error accessor type matching for nullable-only fields
   */
  requiredNullableField: string | null;
};

/** @internal */
export const Test2Response$inboundSchema: z.ZodMiniType<
  Test2Response,
  unknown
> = z.object({
  test2: z.optional(z.nullable(types.string())),
  someConst: types.optional(types.literal("someConstValue")),
  requiredNullableField: types.nullable(types.string()),
});

export function test2ResponseFromJSON(
  jsonString: string,
): SafeParseResult<Test2Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Test2Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Test2Response' from JSON`,
  );
}
