/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations.async;

import static org.openapis.openapi.operations.Operations.AsyncRequestOperation;

import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.operations.AssetStatusStream;
import org.openapis.openapi.models.operations.GetAssetRequest;
import org.openapis.openapi.operations.GetAsset;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;
import org.openapis.openapi.utils.reactive.EventStream;
import org.reactivestreams.Publisher;

public class GetAssetRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetAssetRequest.Builder pojoBuilder;
    private GetAssetRequest request;
    private boolean _setterCalled;

    public GetAssetRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetAssetRequest.builder();
    }

    public GetAssetRequestBuilder id(@Nonnull String id) {
        this.pojoBuilder.id(id);
        this._setterCalled = true;
        return this;
    }

    public GetAssetRequestBuilder stream(@Nullable Boolean stream) {
        this.pojoBuilder.stream(stream);
        this._setterCalled = true;
        return this;
    }

    private GetAssetRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }

    public GetAssetRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
     * Executes the request and returns the response.
     *
     *
     * <p>This operation returns a {@link Publisher<AssetStatusStream>} that implements reactive SSE (Server-Sent Events).
     *
     * <p>
     * The publisher is compliant with the Reactive Streams specification and is interoperable with all reactive-streams
     * compliant toolkits including RxJava, Project Reactor, and Java 9+ Flow API. The underlying response is directly
     * accessible from this construct.
     *
     * @return A reactive streaming {@link Publisher} that emits typed events from the server.
     */
    public EventStream<GetAssetResponse, AssetStatusStream> call() {
        AsyncRequestOperation<GetAssetRequest, GetAssetResponse> operation =
                new GetAsset.Async(sdkConfiguration, _headers);
        return EventStream.forSSE(
                operation.doRequest(this._buildRequest()).thenCompose(operation::handleResponse),
                new TypeReference<>() {},
                Utils.mapper(),
                null);
    }
}
