"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ...types import BaseModel
from typing_extensions import TypedDict


class PetTypedDict(TypedDict):
    r"""A pet in the bar namespace"""

    id: str
    name: str
    owner: str
    r"""The owner of the pet"""


class Pet(BaseModel):
    r"""A pet in the bar namespace"""

    id: str

    name: str

    owner: str
    r"""The owner of the pet"""
