/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupSubGroupSubGroupOp } from "../../funcs/groupSubGroupSubGroupOp.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$groupSubGroupSubGroupOp: ToolDefinition = {
  name: "group-sub-group-sub-group-op",
  description: `An operation at the group's top level`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await groupSubGroupSubGroupOp(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
