// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package openapi

import (
	"example.com/openapi-go-sdk/internal/utils"
)

type CreateUserResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	User *User
}

func (c CreateUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (c *CreateUserResponse) GetHTTPMeta() HTTPMetadata {
	if c == nil {
		return HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateUserResponse) GetUser() *User {
	if c == nil {
		return nil
	}
	return c.User
}
