// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"errors"
	"example.com/openapi-go-sdk/internal/utils"
	"fmt"
)

type OneOfWithUnionDescriptionType string

const (
	OneOfWithUnionDescriptionTypeExhaustiveObject OneOfWithUnionDescriptionType = "ExhaustiveObject"
	OneOfWithUnionDescriptionTypeSimpleObject     OneOfWithUnionDescriptionType = "SimpleObject"
	OneOfWithUnionDescriptionTypeUnknown          OneOfWithUnionDescriptionType = "Unknown"
)

// OneOfWithUnionDescription - A union of two types.
type OneOfWithUnionDescription struct {
	ExhaustiveObject *ExhaustiveObject `queryParam:"inline" union:"member"`
	SimpleObject     *SimpleObject     `queryParam:"inline" union:"member"`
	UnknownRaw       json.RawMessage   `json:"-" union:"unknown"`

	Type OneOfWithUnionDescriptionType
}

type OneOfWithUnionDescriptionMember interface {
	ExhaustiveObject | SimpleObject
}

func NewOneOfWithUnionDescription[T OneOfWithUnionDescriptionMember](val T) OneOfWithUnionDescription {
	switch v := any(val).(type) {
	case ExhaustiveObject:
		return OneOfWithUnionDescription{
			ExhaustiveObject: &v,
			Type:             OneOfWithUnionDescriptionTypeExhaustiveObject,
		}
	case SimpleObject:
		return OneOfWithUnionDescription{
			SimpleObject: &v,
			Type:         OneOfWithUnionDescriptionTypeSimpleObject,
		}
	}
	panic(fmt.Sprintf("unreachable: %T is not a member of union OneOfWithUnionDescription", val))
}
func NewOneOfWithUnionDescriptionUnknown(raw json.RawMessage) OneOfWithUnionDescription {
	return OneOfWithUnionDescription{
		UnknownRaw: raw,
		Type:       OneOfWithUnionDescriptionTypeUnknown,
	}
}

func (u OneOfWithUnionDescription) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u OneOfWithUnionDescription) IsUnknown() bool {
	return u.Type == OneOfWithUnionDescriptionTypeUnknown
}

func (u *OneOfWithUnionDescription) UnmarshalJSON(data []byte) error {
	*u = OneOfWithUnionDescription{}

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var exhaustiveObject ExhaustiveObject = ExhaustiveObject{}
	if err := utils.UnmarshalJSON(data, &exhaustiveObject, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OneOfWithUnionDescriptionTypeExhaustiveObject,
			Value: &exhaustiveObject,
		})
	}

	var simpleObject SimpleObject = SimpleObject{}
	if err := utils.UnmarshalJSON(data, &simpleObject, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  OneOfWithUnionDescriptionTypeSimpleObject,
			Value: &simpleObject,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OneOfWithUnionDescriptionTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = OneOfWithUnionDescriptionTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(OneOfWithUnionDescriptionType)
	switch best.Type {
	case OneOfWithUnionDescriptionTypeExhaustiveObject:
		u.ExhaustiveObject = best.Value.(*ExhaustiveObject)
		return nil
	case OneOfWithUnionDescriptionTypeSimpleObject:
		u.SimpleObject = best.Value.(*SimpleObject)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = OneOfWithUnionDescriptionTypeUnknown
	return nil
}

func (u OneOfWithUnionDescription) MarshalJSON() ([]byte, error) {
	if u.ExhaustiveObject != nil {
		return utils.MarshalJSON(u.ExhaustiveObject, "", true)
	}

	if u.SimpleObject != nil {
		return utils.MarshalJSON(u.SimpleObject, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type OneOfWithUnionDescription: all fields are null")
}

type SimpleAllOf struct {
	// A string property.
	Str *string `json:"str,omitempty"`
	// A boolean property.
	Bool *bool `json:"bool,omitempty"`
}

func (s SimpleAllOf) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SimpleAllOf) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SimpleAllOf) GetStr() *string {
	if s == nil {
		return nil
	}
	return s.Str
}

func (s *SimpleAllOf) GetBool() *bool {
	if s == nil {
		return nil
	}
	return s.Bool
}

// AllOfWithFactoredOutProperties - An object with allOf and factored out properties.
type AllOfWithFactoredOutProperties struct {
	// An overriding property.
	AnOverridingProperty *string `json:"anOverridingProperty,omitempty"`
	// Another property.
	AnotherProperty *string `json:"anotherProperty,omitempty"`
	// An extra property.
	AnExtraProperty *string `json:"anExtraProperty,omitempty"`
}

func (a AllOfWithFactoredOutProperties) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AllOfWithFactoredOutProperties) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AllOfWithFactoredOutProperties) GetAnOverridingProperty() *string {
	if a == nil {
		return nil
	}
	return a.AnOverridingProperty
}

func (a *AllOfWithFactoredOutProperties) GetAnotherProperty() *string {
	if a == nil {
		return nil
	}
	return a.AnotherProperty
}

func (a *AllOfWithFactoredOutProperties) GetAnExtraProperty() *string {
	if a == nil {
		return nil
	}
	return a.AnExtraProperty
}

// GetPolymorphismResponseBody - OK
type GetPolymorphismResponseBody struct {
	// A union of two types.
	OneOfWithUnionDescription *OneOfWithUnionDescription `json:"oneOfWithUnionDescription,omitempty"`
	// A union of two types with factored out properties.
	OneOfWithFactoredOutProperties *OneOfWithFactoredOutProperties `json:"oneOfWithFactoredOutProperties,omitempty"`
	SimpleAllOf                    *SimpleAllOf                    `json:"simpleAllOf,omitempty"`
	// An object with allOf and factored out properties.
	AllOfWithFactoredOutProperties *AllOfWithFactoredOutProperties `json:"allOfWithFactoredOutProperties,omitempty"`
	CircularUnion                  *CircularUnion                  `json:"circularUnion,omitempty"`
	// A form field schema that can be recursive - the array type variant contains an array of RecursiveFormField items.
	RecursiveFormField *RecursiveFormField `json:"recursiveFormField,omitempty"`
}

func (g GetPolymorphismResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPolymorphismResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetPolymorphismResponseBody) GetOneOfWithUnionDescription() *OneOfWithUnionDescription {
	if g == nil {
		return nil
	}
	return g.OneOfWithUnionDescription
}

func (g *GetPolymorphismResponseBody) GetOneOfWithFactoredOutProperties() *OneOfWithFactoredOutProperties {
	if g == nil {
		return nil
	}
	return g.OneOfWithFactoredOutProperties
}

func (g *GetPolymorphismResponseBody) GetSimpleAllOf() *SimpleAllOf {
	if g == nil {
		return nil
	}
	return g.SimpleAllOf
}

func (g *GetPolymorphismResponseBody) GetAllOfWithFactoredOutProperties() *AllOfWithFactoredOutProperties {
	if g == nil {
		return nil
	}
	return g.AllOfWithFactoredOutProperties
}

func (g *GetPolymorphismResponseBody) GetCircularUnion() *CircularUnion {
	if g == nil {
		return nil
	}
	return g.CircularUnion
}

func (g *GetPolymorphismResponseBody) GetRecursiveFormField() *RecursiveFormField {
	if g == nil {
		return nil
	}
	return g.RecursiveFormField
}

func (g *GetPolymorphismResponseBody) GetRecursiveFormFieldText() *RecursiveFormFieldText {
	if v := g.GetRecursiveFormField(); v != nil {
		return v.RecursiveFormFieldText
	}
	return nil
}

func (g *GetPolymorphismResponseBody) GetRecursiveFormFieldNumber() *RecursiveFormFieldNumber {
	if v := g.GetRecursiveFormField(); v != nil {
		return v.RecursiveFormFieldNumber
	}
	return nil
}

func (g *GetPolymorphismResponseBody) GetRecursiveFormFieldArray() *RecursiveFormFieldArray {
	if v := g.GetRecursiveFormField(); v != nil {
		return v.RecursiveFormFieldArray
	}
	return nil
}

type GetPolymorphismResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *GetPolymorphismResponseBody
}

func (g GetPolymorphismResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetPolymorphismResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (g *GetPolymorphismResponse) GetHTTPMeta() HTTPMetadata {
	if g == nil {
		return HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetPolymorphismResponse) GetObject() *GetPolymorphismResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
