// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package openapi

import (
	"example.com/openapi-go-sdk/internal/utils"
)

// LoginResponseBody - OK
type LoginResponseBody struct {
	Token string `json:"token"`
}

func (l LoginResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LoginResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"token"}); err != nil {
		return err
	}
	return nil
}

func (l *LoginResponseBody) GetToken() string {
	if l == nil {
		return ""
	}
	return l.Token
}

type LoginResponse struct {
	HTTPMeta HTTPMetadata `json:"-"`
	// OK
	Object *LoginResponseBody
}

func (l LoginResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LoginResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"HttpMeta"}); err != nil {
		return err
	}
	return nil
}

func (l *LoginResponse) GetHTTPMeta() HTTPMetadata {
	if l == nil {
		return HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *LoginResponse) GetObject() *LoginResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
