// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package openapi

import (
	"example.com/openapi-go-sdk/bar"
	"example.com/openapi-go-sdk/foo"
	"example.com/openapi-go-sdk/internal/utils"
)

// NamespaceConflictTest - A model that references both foo.Pet and bar.Pet to test import aliasing
type NamespaceConflictTest struct {
	// A pet in the foo namespace
	FooPet foo.Pet `json:"fooPet"`
	// A pet in the bar namespace
	BarPet bar.Pet `json:"barPet"`
}

func (n NamespaceConflictTest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NamespaceConflictTest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, []string{"fooPet", "barPet"}); err != nil {
		return err
	}
	return nil
}

func (n *NamespaceConflictTest) GetFooPet() foo.Pet {
	if n == nil {
		return foo.Pet{}
	}
	return n.FooPet
}

func (n *NamespaceConflictTest) GetBarPet() bar.Pet {
	if n == nil {
		return bar.Pet{}
	}
	return n.BarPet
}
