"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ..types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AloofParam(TypedDict):
    bool_: NotRequired[bool]
    int_: NotRequired[int]


class Aloof(BaseModel):
    bool_: Annotated[Optional[bool], pydantic.Field(alias="bool")] = None

    int_: Annotated[Optional[int], pydantic.Field(alias="int")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["bool", "int"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Aloof.model_rebuild()
except NameError:
    pass
