"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ..types import BaseModel, UNSET_SENTINEL
from ..utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from .shape import Shape, ShapeParam
from .shaperequest import ShapeRequest, ShapeRequestParam
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateWithUnionRequestParam(TypedDict):
    shape_request: ShapeRequestParam
    dry_run: NotRequired[bool]
    r"""If true, validates without creating"""


class CreateWithUnionRequest(BaseModel):
    shape_request: Annotated[
        ShapeRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    dry_run: Annotated[
        Optional[bool],
        pydantic.Field(alias="dryRun"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""If true, validates without creating"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["dryRun"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateWithUnionResponseTypedDict(TypedDict):
    r"""OK"""

    id: NotRequired[str]
    shape: NotRequired[ShapeParam]
    r"""A discriminated union of shape types"""


class CreateWithUnionResponse(BaseModel):
    r"""OK"""

    id: Optional[str] = None

    shape: Optional[Shape] = None
    r"""A discriminated union of shape types"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "shape"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
