"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ..types import BaseModel, UNSET_SENTINEL
from ..utils import FieldMetadata, PathParamMetadata, QueryParamMetadata, eventstreaming
from .assetresult import AssetResult, AssetResultTypedDict
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GetAssetRequestParam(TypedDict):
    id: str
    stream: NotRequired[bool]


class GetAssetRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    stream: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = True

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["stream"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class AssetStatusStreamTypedDict(TypedDict):
    r"""OK"""

    data: AssetResultTypedDict
    r"""The result of a render request."""


class AssetStatusStream(BaseModel):
    r"""OK"""

    data: AssetResult
    r"""The result of a render request."""


GetAssetResponseTypedDict = TypeAliasType(
    "GetAssetResponseTypedDict",
    Union[
        AssetResultTypedDict,
        Union[
            eventstreaming.EventStream[AssetResultTypedDict],
            eventstreaming.EventStreamAsync[AssetResultTypedDict],
        ],
    ],
)


GetAssetResponse = TypeAliasType(
    "GetAssetResponse",
    Union[
        AssetResult,
        Union[
            eventstreaming.EventStream[AssetResult],
            eventstreaming.EventStreamAsync[AssetResult],
        ],
    ],
)
