"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ..types import BaseModel, UNSET_SENTINEL
from ..utils import eventstreaming
from .assetresult import AssetResult, AssetResultTypedDict
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


OutputModality = Literal[
    "text",
    "image",
]


class RenderAssetRequestParam(TypedDict):
    prompt: str
    output_modalities: NotRequired[List[OutputModality]]


class RenderAssetRequest(BaseModel):
    prompt: str

    output_modalities: Optional[List[OutputModality]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["output_modalities"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class AssetStreamTypedDict(TypedDict):
    r"""OK"""

    data: AssetResultTypedDict
    r"""The result of a render request."""


class AssetStream(BaseModel):
    r"""OK"""

    data: AssetResult
    r"""The result of a render request."""


RenderAssetResponseTypedDict = TypeAliasType(
    "RenderAssetResponseTypedDict",
    Union[
        AssetResultTypedDict,
        Union[
            eventstreaming.EventStream[AssetResultTypedDict],
            eventstreaming.EventStreamAsync[AssetResultTypedDict],
        ],
    ],
)


RenderAssetResponse = TypeAliasType(
    "RenderAssetResponse",
    Union[
        AssetResult,
        Union[
            eventstreaming.EventStream[AssetResult],
            eventstreaming.EventStreamAsync[AssetResult],
        ],
    ],
)
