// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/shared"
)

func (r *RequestBodyRequiredRefNullableWithParameterDataSourceModel) RefreshFromOperationsGetRequestbodyRequiredRefNullableWithParameterResponseBody(ctx context.Context, resp *operations.GetRequestbodyRequiredRefNullableWithParameterResponseBody) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.ResponseString = types.StringPointerValue(resp.ResponseString)
	}

	return diags
}

func (r *RequestBodyRequiredRefNullableWithParameterDataSourceModel) ToOperationsGetRequestbodyRequiredRefNullableWithParameterRequest(ctx context.Context) (*operations.GetRequestbodyRequiredRefNullableWithParameterRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	queryParam := new(int64)
	if !r.QueryParam.IsUnknown() && !r.QueryParam.IsNull() {
		*queryParam = r.QueryParam.ValueInt64()
	} else {
		queryParam = nil
	}
	requestBodyRefNullableRequest, requestBodyRefNullableRequestDiags := r.ToSharedRequestBodyRefNullableRequest(ctx)
	diags.Append(requestBodyRefNullableRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.GetRequestbodyRequiredRefNullableWithParameterRequest{
		QueryParam:                    queryParam,
		RequestBodyRefNullableRequest: requestBodyRefNullableRequest,
	}

	return &out, diags
}

func (r *RequestBodyRequiredRefNullableWithParameterDataSourceModel) ToSharedRequestBodyRefNullableRequest(ctx context.Context) (*shared.RequestBodyRefNullableRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	requestString := new(string)
	if !r.RequestString.IsUnknown() && !r.RequestString.IsNull() {
		*requestString = r.RequestString.ValueString()
	} else {
		requestString = nil
	}
	out := shared.RequestBodyRefNullableRequest{
		RequestString: requestString,
	}

	return &out, diags
}
