// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk"
)

// #region imports
// #endregion imports

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSource{}
var _ datasource.DataSourceWithConfigure = &RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSource{}

func NewRequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSource() datasource.DataSource {
	return &RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSource{}
}

// RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSource is the data source implementation.
type RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSource struct {
	// Provider configured SDK client.
	client *sdk.SDK
}

// RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSourceModel describes the data model.
type RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSourceModel struct {
	RequestString  types.String `tfsdk:"request_string"`
	ResponseString types.String `tfsdk:"response_string"`
}

// Metadata returns the data source type name.
func (r *RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_request_body_required_ref_x_speakeasy_entity_level2_array"
}

// Schema defines the schema for the data source.
func (r *RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "RequestBodyRequiredRefXSpeakeasyEntityLevel2Array DataSource",

		Attributes: map[string]schema.Attribute{
			"request_string": schema.StringAttribute{
				Optional: true,
			},
			"response_string": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (r *RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*TestingProviderConfigureData)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *TestingProviderConfigureData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = providerData.SDKClient
}

func (r *RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *RequestBodyRequiredRefXSpeakeasyEntityLevel2ArrayDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToSharedRequestBodyRefXSpeakeasyEntityLevel2ArrayRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.GetRequestbodyRequiredRefXspeakeasyentityLevel2Array(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.Object != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromOperationsGetRequestbodyRequiredRefXspeakeasyentityLevel2ArrayResponseBody(ctx, res.Object)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
