// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/shared"
)

func (r *XEntityVersionDataSourceModel) RefreshFromSharedXEntityVersionResponse(ctx context.Context, resp *shared.XEntityVersionResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.ID = types.StringPointerValue(resp.ID)
	}

	return diags
}

func (r *XEntityVersionDataSourceModel) ToOperationsGetXEntityVersionRequest(ctx context.Context) (*operations.GetXEntityVersionRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetXEntityVersionRequest{
		ID: id,
	}

	return &out, diags
}
