// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
	"github.com/hashicorp/terraform-provider-testing/internal/provider"
	"github.com/hashicorp/terraform-provider-testing/internal/tfmockserver"
)

// TestXMatchNestedReadonlyResourceLifecycle validates that a flat request body
// field mapped via x-speakeasy-match to a nested response path generates a
// schema where the parent container (safety_settings) is Optional+Computed,
// not Computed-only (readonly). Without the fix, Terraform would reject the
// config because safety_settings would be read-only.
func TestXMatchNestedReadonlyResourceLifecycle(t *testing.T) {
	t.Parallel()

	id := "resource-456"
	endpointsBuilder := tfmockserver.ResourceEndpoints{
		Create: tfmockserver.Endpoints{
			{
				Endpoint: "POST /v0/xmatch-nested-readonly",
				ResponseOverlay: map[string]any{
					"id": id,
					"safety_settings": map[string]any{
						"enforce_approval": true,
						"created_at":       "2025-01-01T00:00:00Z",
					},
				},
			},
		},
		Get: tfmockserver.Endpoints{
			{
				Endpoint: "GET /v0/xmatch-nested-readonly/{id}",
				ResponseOverlay: map[string]any{
					"id": id,
					"safety_settings": map[string]any{
						"enforce_approval": true,
						"created_at":       "2025-01-01T00:00:00Z",
					},
				},
			},
		},
		Delete: tfmockserver.Endpoints{
			{
				Endpoint: "DELETE /v0/xmatch-nested-readonly/{id}",
			},
		},
	}

	mockServer := tfmockserver.StartServer(endpointsBuilder, t)
	defer mockServer.Close()

	resourceAddress := "testing_x_match_nested_readonly.test"

	resource.Test(t, resource.TestCase{
		Steps: []resource.TestStep{
			{
				ConfigDirectory:          config.TestNameDirectory(),
				ProtoV6ProviderFactories: provider.GetTestProviders(),
				ConfigVariables: config.Variables{
					"server_url": config.StringVariable(mockServer.URL),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					// Computed ID from the API response.
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("id"),
						knownvalue.StringExact(id),
					),
					// User-provided value via flat match into nested container.
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("safety_settings").AtMapKey("enforce_approval"),
						knownvalue.Bool(true),
					),
					// Response-only field inside the nested container.
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("safety_settings").AtMapKey("created_at"),
						knownvalue.StringExact("2025-01-01T00:00:00Z"),
					),
				},
			},
		},
	})
}
