// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider_test

import (
	"net/http"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/config"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
	"github.com/hashicorp/terraform-provider-testing/internal/provider"
	"github.com/hashicorp/terraform-provider-testing/internal/tfmockserver"
)

// TestAccXPaginationOffsetLimitsResource_Pagination verifies that:
// 1. Paginated array attributes correctly accumulate data across multiple pages within a single Read
// 2. Array data is correctly reinitialized on each separate Read operation (no accumulation across Reads)
// 3. Multiple pages are correctly fetched and merged (no data loss)
//
// This test specifically validates the TFGEN-214 fix where arrays were accumulating
// duplicate values during refresh operations instead of being properly reinitialized.
func TestAccXPaginationOffsetLimitsResource_Pagination(t *testing.T) {
	t.Parallel()

	resourceAddress := "testing_x_pagination_offset_limits.test"

	// Track number of GET requests made across all test steps
	// This allows us to return different data at different stages of the test lifecycle
	getCallCount := 0

	endpoints := tfmockserver.ResourceEndpoints{
		Create: tfmockserver.Endpoints{
			{
				Endpoint: "POST /v0/xpagination/offsetLimit",
			},
		},
		Get: tfmockserver.Endpoints{
			{
				Endpoint: "GET /v0/xpagination/offsetLimit",
				// Use ResponseFunc to simulate paginated responses based on page parameter
				// This ensures we test that pagination actually fetches and accumulates
				// data from multiple pages within a single Read operation.
				ResponseFunc: func(r *http.Request, w http.ResponseWriter) {
					pageStr := r.URL.Query().Get("page")
					getCallCount++

					var response map[string]any

					// For the first 6 calls (Create + Update steps), return empty results
					// Each Read operation makes 3 calls (page 1, page 2, page 3) before stopping
					// So 6 calls = 2 Read operations (Create's Read + Update's Read)
					if getCallCount <= 6 {
						// Return empty results (no pagination data yet)
						response = map[string]any{
							"id":      "default",
							"results": []string{},
						}
					} else if pageStr == "" || pageStr == "1" {
						// After the first 6 calls (7+), subsequent Reads return paginated data
						// First page: 3 items
						response = map[string]any{
							"id":      "default",
							"results": []string{"item-1", "item-2", "item-3"},
						}
					} else if pageStr == "2" {
						// Second page: 2 items
						response = map[string]any{
							"id":      "default",
							"results": []string{"item-4", "item-5"},
						}
					} else {
						// No more pages - empty results signals end of pagination
						response = map[string]any{
							"id":      "default",
							"results": []string{},
						}
					}

					tfmockserver.JSONResponse(w, 200, response)
				},
			},
		},
		Update: tfmockserver.Endpoints{
			{
				Endpoint: "PATCH /v0/xpagination/offsetLimit",
			},
		},
		Delete: tfmockserver.Endpoints{
			{
				Endpoint: "DELETE /v0/xpagination/offsetLimit",
			},
		},
	}
	mockServer := tfmockserver.StartServer(endpoints, t)
	defer mockServer.Close()

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: provider.GetTestProviders(),
		Steps: []resource.TestStep{
			// Create and Read - should accumulate all 5 items from 2 pages
			{
				Config: `
variable "server_url" {
  type = string
}

provider "testing" {
  server_url = var.server_url
}

resource "testing_x_pagination_offset_limits" "test" {
  string_request = "test-value"
}
`,
				ConfigVariables: config.Variables{
					"server_url": config.StringVariable(mockServer.URL),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("id"),
						knownvalue.StringExact("default"),
					),
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("string_request"),
						knownvalue.StringExact("test-value"),
					),
					// After Create, results is empty (mock returns empty for first calls)
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("results"),
						knownvalue.ListExact([]knownvalue.Check{}),
					),
				},
			},
			// Update and Read - verify array is still empty (mock still returns empty for call count <= 6)
			{
				Config: `
variable "server_url" {
  type = string
}

provider "testing" {
  server_url = var.server_url
}

resource "testing_x_pagination_offset_limits" "test" {
  string_request = "updated-value"
}
`,
				ConfigVariables: config.Variables{
					"server_url": config.StringVariable(mockServer.URL),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("id"),
						knownvalue.StringExact("default"),
					),
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("string_request"),
						knownvalue.StringExact("updated-value"),
					),
					// After Update, results is still empty (mock returns empty for first 6 calls)
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("results"),
						knownvalue.ListExact([]knownvalue.Check{}),
					),
				},
			},
			// Refresh state explicitly to trigger a Read operation
			// Now pagination kicks in (call count > 6)
			// This tests that pagination correctly accumulates data across multiple pages
			// and that arrays don't accumulate across separate Read operations
			{
				RefreshState: true,
			},
			// Apply again to verify the refreshed state with pagination data
			{
				Config: `
variable "server_url" {
  type = string
}

provider "testing" {
  server_url = var.server_url
}

resource "testing_x_pagination_offset_limits" "test" {
  string_request = "updated-value"
}
`,
				ConfigVariables: config.Variables{
					"server_url": config.StringVariable(mockServer.URL),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("id"),
						knownvalue.StringExact("default"),
					),
					// Critical test: After refresh, Read fetches paginated data
					// Mock returns 5 items across 2 pages (item-1, item-2, item-3, item-4, item-5)
					// Tests two things:
					// 1. Pagination works: items from multiple pages are accumulated within the Read
					// 2. Reinitialization works: array is exactly 5 items, not accumulated from previous Reads
					// If TFGEN-214 bug existed, arrays would have duplicates from previous Read operations
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("results"),
						knownvalue.ListExact([]knownvalue.Check{
							knownvalue.StringExact("item-1"),
							knownvalue.StringExact("item-2"),
							knownvalue.StringExact("item-3"),
							knownvalue.StringExact("item-4"),
							knownvalue.StringExact("item-5"),
						}),
					),
				},
			},
			// Another explicit refresh to ensure arrays don't accumulate on subsequent refreshes
			// This is the core TFGEN-214 test: refresh should not duplicate existing data
			{
				RefreshState: true,
			},
			// Verify state after second refresh - should STILL be exactly 5 items
			{
				Config: `
variable "server_url" {
  type = string
}

provider "testing" {
  server_url = var.server_url
}

resource "testing_x_pagination_offset_limits" "test" {
  string_request = "updated-value"
}
`,
				ConfigVariables: config.Variables{
					"server_url": config.StringVariable(mockServer.URL),
				},
				ConfigStateChecks: []statecheck.StateCheck{
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("id"),
						knownvalue.StringExact("default"),
					),
					// Critical TFGEN-214 test: After multiple refreshes, should STILL be exactly 5 items
					// If bug existed: would accumulate to 15 items (5 + 5 + 5)
					// With fix: properly reinitialized on each Read, so exactly 5 items
					statecheck.ExpectKnownValue(
						resourceAddress,
						tfjsonpath.New("results"),
						knownvalue.ListExact([]knownvalue.Check{
							knownvalue.StringExact("item-1"),
							knownvalue.StringExact("item-2"),
							knownvalue.StringExact("item-3"),
							knownvalue.StringExact("item-4"),
							knownvalue.StringExact("item-5"),
						}),
					),
				},
			},
		},
	})
}
