// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/shared"
)

func (r *XPaginationSingletonDataSourceModel) RefreshFromSharedXPaginationSingletonAndListResponse(ctx context.Context, resp *shared.XPaginationSingletonAndListResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if len(resp.Data) == 0 {
			diags.AddError("Unexpected response from API", "Missing response body array data.")
			return diags
		}

		diags.Append(r.RefreshFromSharedXPaginationSingletonAndListResponseData(ctx, &resp.Data[0])...)

		if diags.HasError() {
			return diags
		}

		r.Number = types.Int64Value(resp.Meta.Page.Number)
		r.Size = types.Int64Value(resp.Meta.Page.Size)
		r.Total = types.Int64Value(resp.Meta.Page.Total)
	}

	return diags
}

func (r *XPaginationSingletonDataSourceModel) RefreshFromSharedXPaginationSingletonAndListResponseData(ctx context.Context, resp *shared.XPaginationSingletonAndListResponseData) diag.Diagnostics {
	var diags diag.Diagnostics

	r.ID = types.StringValue(resp.ID)
	r.Name = types.StringValue(resp.Name)

	return diags
}

func (r *XPaginationSingletonDataSourceModel) ToOperationsListXPaginationSingletonAndListRequest(ctx context.Context) (*operations.ListXPaginationSingletonAndListRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	filterName := new(string)
	if !r.FilterName.IsUnknown() && !r.FilterName.IsNull() {
		*filterName = r.FilterName.ValueString()
	} else {
		filterName = nil
	}
	out := operations.ListXPaginationSingletonAndListRequest{
		FilterName: filterName,
	}

	return &out, diags
}
