// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk"
)

// #region imports
// #endregion imports

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &XPaginationUrlsDataSource{}
var _ datasource.DataSourceWithConfigure = &XPaginationUrlsDataSource{}

func NewXPaginationUrlsDataSource() datasource.DataSource {
	return &XPaginationUrlsDataSource{}
}

// XPaginationUrlsDataSource is the data source implementation.
type XPaginationUrlsDataSource struct {
	// Provider configured SDK client.
	client *sdk.SDK
}

// XPaginationUrlsDataSourceModel describes the data model.
type XPaginationUrlsDataSourceModel struct {
	Results       []types.String `tfsdk:"results"`
	StringRequest types.String   `tfsdk:"string_request"`
}

// Metadata returns the data source type name.
func (r *XPaginationUrlsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_x_pagination_urls"
}

// Schema defines the schema for the data source.
func (r *XPaginationUrlsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "XPaginationUrls DataSource",

		Attributes: map[string]schema.Attribute{
			"results": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},
			"string_request": schema.StringAttribute{
				Optional: true,
				MarkdownDescription: `Configurable string for request, to ensure other configurable` + "\n" +
					`attributes are not affected by pagination having input attributes` + "\n" +
					`removed.`,
			},
		},
	}
}

func (r *XPaginationUrlsDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*TestingProviderConfigureData)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *TestingProviderConfigureData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = providerData.SDKClient
}

func (r *XPaginationUrlsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *XPaginationUrlsDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToSharedXPaginationUrlsRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.ListXPaginationUrls(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.XPaginationUrlsResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.Results = nil
	resp.Diagnostics.Append(data.RefreshFromSharedXPaginationUrlsResponse(ctx, res.XPaginationUrlsResponse)...)

	if resp.Diagnostics.HasError() {
		return
	}
	for {
		var err error

		res, err = res.Next()

		if err != nil {
			resp.Diagnostics.AddError("failed to retrieve next page of results", err.Error())
			if res != nil && res.RawResponse != nil {
				resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
			}
			return
		}

		if res == nil {
			break
		}

		resp.Diagnostics.Append(data.RefreshFromSharedXPaginationUrlsResponse(ctx, res.XPaginationUrlsResponse)...)

		if resp.Diagnostics.HasError() {
			return
		}
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
