// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/mapvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	custom_boolplanmodifier "github.com/hashicorp/terraform-provider-testing/internal/planmodifiers/boolplanmodifier"
	custom_float32planmodifier "github.com/hashicorp/terraform-provider-testing/internal/planmodifiers/float32planmodifier"
	custom_float64planmodifier "github.com/hashicorp/terraform-provider-testing/internal/planmodifiers/float64planmodifier"
	custom_int32planmodifier "github.com/hashicorp/terraform-provider-testing/internal/planmodifiers/int32planmodifier"
	custom_int64planmodifier "github.com/hashicorp/terraform-provider-testing/internal/planmodifiers/int64planmodifier"
	custom_listplanmodifier "github.com/hashicorp/terraform-provider-testing/internal/planmodifiers/listplanmodifier"
	custom_mapplanmodifier "github.com/hashicorp/terraform-provider-testing/internal/planmodifiers/mapplanmodifier"
	custom_objectplanmodifier "github.com/hashicorp/terraform-provider-testing/internal/planmodifiers/objectplanmodifier"
	custom_setplanmodifier "github.com/hashicorp/terraform-provider-testing/internal/planmodifiers/setplanmodifier"
	custom_stringplanmodifier "github.com/hashicorp/terraform-provider-testing/internal/planmodifiers/stringplanmodifier"
	tfTypes "github.com/hashicorp/terraform-provider-testing/internal/provider/types"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk"
	"github.com/hashicorp/terraform-provider-testing/internal/validators"
	speakeasy_objectvalidators "github.com/hashicorp/terraform-provider-testing/internal/validators/objectvalidators"
)

// #region imports
// #endregion imports

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &XPlanModifiersResource{}
var _ resource.ResourceWithImportState = &XPlanModifiersResource{}

func NewXPlanModifiersResource() resource.Resource {
	return &XPlanModifiersResource{}
}

// XPlanModifiersResource defines the resource implementation.
type XPlanModifiersResource struct {
	// Provider configured SDK client.
	client *sdk.SDK
}

// XPlanModifiersResourceModel describes the resource data model.
type XPlanModifiersResourceModel struct {
	Any        jsontypes.Normalized                      `tfsdk:"any"`
	Bool       types.Bool                                `tfsdk:"bool"`
	Float32    types.Float32                             `tfsdk:"float32"`
	Float64    types.Float64                             `tfsdk:"float64"`
	ID         types.String                              `tfsdk:"id"`
	Int32      types.Int32                               `tfsdk:"int32"`
	Int64      types.Int64                               `tfsdk:"int64"`
	List       []types.String                            `tfsdk:"list"`
	ListNested []tfTypes.XPlanModifiersRequestListNested `tfsdk:"list_nested"`
	Map        map[string]jsontypes.Normalized           `tfsdk:"map"`
	Object     *tfTypes.XPlanModifiersRequestObject      `tfsdk:"object"`
	Set        []types.String                            `tfsdk:"set"`
	SetNested  []tfTypes.XPlanModifiersRequestSetNested  `tfsdk:"set_nested"`
	String     types.String                              `tfsdk:"string"`
}

func (r *XPlanModifiersResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_x_plan_modifiers"
}

func (r *XPlanModifiersResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "XPlanModifiers Resource",
		Attributes: map[string]schema.Attribute{
			"any": schema.StringAttribute{
				CustomType: jsontypes.NormalizedType{},
				Computed:   true,
				Optional:   true,
				PlanModifiers: []planmodifier.String{
					custom_stringplanmodifier.Custom(),
				},
				Description: `Parsed as JSON.`,
			},
			"bool": schema.BoolAttribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.Bool{
					custom_boolplanmodifier.Custom(),
				},
			},
			"float32": schema.Float32Attribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.Float32{
					custom_float32planmodifier.Custom(),
				},
			},
			"float64": schema.Float64Attribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.Float64{
					custom_float64planmodifier.Custom(),
				},
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"int32": schema.Int32Attribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.Int32{
					custom_int32planmodifier.Custom(),
				},
			},
			"int64": schema.Int64Attribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.Int64{
					custom_int64planmodifier.Custom(),
				},
			},
			"list": schema.ListAttribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.List{
					custom_listplanmodifier.Custom(),
				},
				ElementType: types.StringType,
			},
			"list_nested": schema.ListNestedAttribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.List{
					custom_listplanmodifier.Custom(),
				},
				NestedObject: schema.NestedAttributeObject{
					Validators: []validator.Object{
						speakeasy_objectvalidators.NotNull(),
					},
					PlanModifiers: []planmodifier.Object{
						custom_objectplanmodifier.Custom(),
					},
					Attributes: map[string]schema.Attribute{
						"list_nested_string": schema.StringAttribute{
							Computed: true,
							Optional: true,
							PlanModifiers: []planmodifier.String{
								custom_stringplanmodifier.Custom(),
							},
						},
					},
				},
			},
			"map": schema.MapAttribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.Map{
					custom_mapplanmodifier.Custom(),
				},
				ElementType: jsontypes.NormalizedType{},
				Validators: []validator.Map{
					mapvalidator.ValueStringsAre(validators.IsValidJSON()),
				},
			},
			"object": schema.SingleNestedAttribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.Object{
					custom_objectplanmodifier.Custom(),
				},
				Attributes: map[string]schema.Attribute{
					"object_string": schema.StringAttribute{
						Computed: true,
						Optional: true,
					},
				},
			},
			"set": schema.SetAttribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.Set{
					custom_setplanmodifier.Custom(),
				},
				ElementType: types.StringType,
			},
			"set_nested": schema.SetNestedAttribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.Set{
					custom_setplanmodifier.Custom(),
				},
				NestedObject: schema.NestedAttributeObject{
					Validators: []validator.Object{
						speakeasy_objectvalidators.NotNull(),
					},
					PlanModifiers: []planmodifier.Object{
						custom_objectplanmodifier.Custom(),
					},
					Attributes: map[string]schema.Attribute{
						"set_nested_string": schema.StringAttribute{
							Computed: true,
							Optional: true,
						},
					},
				},
			},
			"string": schema.StringAttribute{
				Computed: true,
				Optional: true,
				PlanModifiers: []planmodifier.String{
					custom_stringplanmodifier.Custom(),
				},
			},
		},
	}
}

func (r *XPlanModifiersResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	providerData, ok := req.ProviderData.(*TestingProviderConfigureData)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *TestingProviderConfigureData, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = providerData.SDKClient
}

func (r *XPlanModifiersResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *XPlanModifiersResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToSharedXPlanModifiersRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.CreateXPlanModifiers(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.XPlanModifiersResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedXPlanModifiersResponse(ctx, res.XPlanModifiersResponse)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// #region post-create
	// #endregion post-create

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *XPlanModifiersResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *XPlanModifiersResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetCustomPlanModifiersRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.GetCustomPlanModifiers(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.XPlanModifiersResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedXPlanModifiersResponse(ctx, res.XPlanModifiersResponse)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// #region post-read
	// #endregion post-read

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *XPlanModifiersResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *XPlanModifiersResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsUpdateXPlanModifiersRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.UpdateXPlanModifiers(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.XPlanModifiersResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedXPlanModifiersResponse(ctx, res.XPlanModifiersResponse)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// #region post-update
	// #endregion post-update

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *XPlanModifiersResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *XPlanModifiersResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	// #region pre-delete
	// #endregion pre-delete

	request, requestDiags := data.ToOperationsDeleteCustomPlanModifiersRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.DeleteCustomPlanModifiers(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	switch res.StatusCode {
	case 200, 404:
		break
	default:
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *XPlanModifiersResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
