// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/operations"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/shared"
)

func (r *XUnknownValuesResourceModel) RefreshFromSharedXUnknownValuesResponse(ctx context.Context, resp *shared.XUnknownValuesResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.ClosedEnumString != nil {
			r.ClosedEnumString = types.StringValue(string(*resp.ClosedEnumString))
		} else {
			r.ClosedEnumString = types.StringNull()
		}
		r.ID = types.StringValue(resp.ID)
		if resp.OptionalComputedOpenEnumInt64 != nil {
			r.OptionalComputedOpenEnumInt64 = types.Int64Value(int64(*resp.OptionalComputedOpenEnumInt64))
		} else {
			r.OptionalComputedOpenEnumInt64 = types.Int64Null()
		}
		if resp.OptionalComputedOpenEnumString != nil {
			r.OptionalComputedOpenEnumString = types.StringValue(string(*resp.OptionalComputedOpenEnumString))
		} else {
			r.OptionalComputedOpenEnumString = types.StringNull()
		}
		r.RequiredOpenEnumString = types.StringValue(string(resp.RequiredOpenEnumString))
		if resp.ResponseOnlyOpenEnumInt64 != nil {
			r.ResponseOnlyOpenEnumInt64 = types.Int64Value(int64(*resp.ResponseOnlyOpenEnumInt64))
		} else {
			r.ResponseOnlyOpenEnumInt64 = types.Int64Null()
		}
		if resp.ResponseOnlyOpenEnumString != nil {
			r.ResponseOnlyOpenEnumString = types.StringValue(string(*resp.ResponseOnlyOpenEnumString))
		} else {
			r.ResponseOnlyOpenEnumString = types.StringNull()
		}
	}

	return diags
}

func (r *XUnknownValuesResourceModel) ToOperationsDeleteXUnknownValuesRequest(ctx context.Context) (*operations.DeleteXUnknownValuesRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.DeleteXUnknownValuesRequest{
		ID: id,
	}

	return &out, diags
}

func (r *XUnknownValuesResourceModel) ToOperationsGetXUnknownValuesRequest(ctx context.Context) (*operations.GetXUnknownValuesRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var id string
	id = r.ID.ValueString()

	out := operations.GetXUnknownValuesRequest{
		ID: id,
	}

	return &out, diags
}

func (r *XUnknownValuesResourceModel) ToSharedXUnknownValuesRequest(ctx context.Context) (*shared.XUnknownValuesRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	requiredOpenEnumString := shared.XUnknownValuesRequestRequiredOpenEnumString(r.RequiredOpenEnumString.ValueString())
	optionalOpenEnumString := new(shared.OptionalOpenEnumString)
	if !r.OptionalOpenEnumString.IsUnknown() && !r.OptionalOpenEnumString.IsNull() {
		*optionalOpenEnumString = shared.OptionalOpenEnumString(r.OptionalOpenEnumString.ValueString())
	} else {
		optionalOpenEnumString = nil
	}
	optionalComputedOpenEnumString := new(shared.XUnknownValuesRequestOptionalComputedOpenEnumString)
	if !r.OptionalComputedOpenEnumString.IsUnknown() && !r.OptionalComputedOpenEnumString.IsNull() {
		*optionalComputedOpenEnumString = shared.XUnknownValuesRequestOptionalComputedOpenEnumString(r.OptionalComputedOpenEnumString.ValueString())
	} else {
		optionalComputedOpenEnumString = nil
	}
	optionalComputedOpenEnumInt64 := new(shared.XUnknownValuesRequestOptionalComputedOpenEnumInt64)
	if !r.OptionalComputedOpenEnumInt64.IsUnknown() && !r.OptionalComputedOpenEnumInt64.IsNull() {
		*optionalComputedOpenEnumInt64 = shared.XUnknownValuesRequestOptionalComputedOpenEnumInt64(r.OptionalComputedOpenEnumInt64.ValueInt64())
	} else {
		optionalComputedOpenEnumInt64 = nil
	}
	closedEnumString := new(shared.XUnknownValuesRequestClosedEnumString)
	if !r.ClosedEnumString.IsUnknown() && !r.ClosedEnumString.IsNull() {
		*closedEnumString = shared.XUnknownValuesRequestClosedEnumString(r.ClosedEnumString.ValueString())
	} else {
		closedEnumString = nil
	}
	out := shared.XUnknownValuesRequest{
		RequiredOpenEnumString:         requiredOpenEnumString,
		OptionalOpenEnumString:         optionalOpenEnumString,
		OptionalComputedOpenEnumString: optionalComputedOpenEnumString,
		OptionalComputedOpenEnumInt64:  optionalComputedOpenEnumInt64,
		ClosedEnumString:               closedEnumString,
	}

	return &out, diags
}
