// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types/stream"
)

type StreamMetadataData struct {
	Content    *string `json:"content,omitempty"`
	ResourceID *string `json:"resource_id,omitempty"`
}

func (o *StreamMetadataData) GetContent() *string {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *StreamMetadataData) GetResourceID() *string {
	if o == nil {
		return nil
	}
	return o.ResourceID
}

// StreamMetadataResponseBody - Streamed resource events.
type StreamMetadataResponseBody struct {
	Data StreamMetadataData `json:"data"`
}

func (o *StreamMetadataResponseBody) GetData() StreamMetadataData {
	if o == nil {
		return StreamMetadataData{}
	}
	return o.Data
}

func (o StreamMetadataResponseBody) GetEventEncoding(event string) (string, error) {
	return "application/json", nil
}

type StreamMetadataResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Streamed resource events.
	Object *stream.EventStream[StreamMetadataResponseBody]
}

func (o *StreamMetadataResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *StreamMetadataResponse) GetObject() *stream.EventStream[StreamMetadataResponseBody] {
	if o == nil {
		return nil
	}
	return o.Object
}
