// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime"
	"mime/multipart"
	"net/http"
	"net/url"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"openapi/internal/config"
	"openapi/internal/flagutil"
)

// maxBodyPreview is the maximum number of bytes to show in body previews.
const maxBodyPreview = 4096

// maxRedactDepth is the maximum depth for recursive JSON redaction.
const maxRedactDepth = 64

// IsDryRun returns true when --dry-run is set on the command.
func IsDryRun(cmd *cobra.Command) bool {
	v, _ := flagutil.GetBoolFlag(cmd, "dry-run")
	return v
}

func IsJSONDryRun(cmd *cobra.Command) bool {
	if !IsDryRun(cmd) {
		return false
	}
	format := flagutil.ResolveOutputFormat(cmd, config.GetString("output-format"), false)
	return format == "json" || flagutil.FlagChanged(cmd, "jq")
}

// IsDebug returns true when --debug is set and --dry-run is not.
// When both flags are set, dry-run takes precedence.
func IsDebug(cmd *cobra.Command) bool {
	if IsDryRun(cmd) {
		return false
	}
	v, _ := flagutil.GetBoolFlag(cmd, "debug")
	return v
}

// sensitiveHeaderKeys lists header key patterns that should be redacted.
// Matching is case-insensitive. Beyond the generic entries, the list includes
// every API-key header name declared by this API's security schemes.
var sensitiveHeaderKeys = []string{
	"authorization",
	"proxy-authorization",
	"x-api-key",
	"api-key",
	"x-session-token",
	"cookie",
	"set-cookie",
	"api_key",
}

// sensitiveHeaderSuffixes lists header key suffixes that should be redacted.
var sensitiveHeaderSuffixes = []string{
	"-secret",
	"-token",
}

// sensitiveJSONKeys lists JSON field names to redact, normalized to lowercase without separators.
var sensitiveJSONKeys = map[string]bool{
	"password":     true,
	"secret":       true,
	"token":        true,
	"accesstoken":  true,
	"refreshtoken": true,
	"apikey":       true,
	"privatekey":   true,
	"clientsecret": true,
}

type sensitiveBodyNode struct {
	Sensitive bool
	Fields    map[string]int
	Item      int
	Variants  []int
}

type sensitiveBodySchema struct {
	Nodes []sensitiveBodyNode
	Roots []int
}

var sensitiveBodyFields = map[string]sensitiveBodySchema{}

var sensitiveQueryKeys = map[string]bool{
	"apikey":       true,
	"accesstoken":  true,
	"token":        true,
	"key":          true,
	"clientsecret": true,
	"password":     true,
	"signature":    true,
}

var sensitiveNameSubstrings = []string{
	"key",
	"token",
	"secret",
	"auth",
	"session",
	"cookie",
	"password",
	"passwd",
	"signature",
	"credential",
}

const redactionDepthMarker = "<redacted:max-depth>"

// isSensitiveHeader returns true if the header key matches a sensitive pattern.
func isSensitiveHeader(key string) bool {
	lower := strings.ToLower(key)
	for _, s := range sensitiveHeaderKeys {
		if lower == s {
			return true
		}
	}
	for _, suffix := range sensitiveHeaderSuffixes {
		if strings.HasSuffix(lower, suffix) {
			return true
		}
	}
	return isSensitiveName(key)
}

// redactHeaders returns a copy of headers with sensitive values replaced by "[REDACTED]".
func redactHeaders(h http.Header) http.Header {
	out := make(http.Header, len(h))
	for k, vals := range h {
		if isSensitiveHeader(k) {
			out[k] = []string{"[REDACTED]"}
		} else {
			out[k] = append([]string(nil), vals...)
		}
	}
	return out
}

func normalizeSensitiveKey(key string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(key) {
		if r != '_' && r != '-' {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func isSensitiveName(key string) bool {
	normalized := normalizeSensitiveKey(key)
	if normalized == "sig" || sensitiveQueryKeys[normalized] || sensitiveJSONKeys[normalized] {
		return true
	}
	for _, token := range sensitiveNameSubstrings {
		if strings.Contains(normalized, token) {
			return true
		}
	}
	return false
}

func sensitiveBodyFieldsFor(cmd *cobra.Command) sensitiveBodySchema {
	if cmd == nil {
		return sensitiveBodySchema{}
	}
	return sensitiveBodyFields[cmd.Annotations["speakeasy_operation"]]
}

func (s sensitiveBodySchema) expandedRoots() []int {
	var roots []int
	seen := make(map[int]bool)
	var visit func(int)
	visit = func(id int) {
		if id <= 0 || id >= len(s.Nodes) || seen[id] {
			return
		}
		seen[id] = true
		roots = append(roots, id)
		for _, variant := range s.Nodes[id].Variants {
			visit(variant)
		}
	}
	for _, root := range s.Roots {
		visit(root)
	}
	return roots
}

func (s sensitiveBodySchema) isSensitive() bool {
	for _, id := range s.expandedRoots() {
		if s.Nodes[id].Sensitive {
			return true
		}
	}
	return false
}

func (s sensitiveBodySchema) child(name string) sensitiveBodySchema {
	var roots []int
	for _, id := range s.expandedRoots() {
		node := s.Nodes[id]
		if child := node.Fields[name]; child != 0 {
			roots = append(roots, child)
		}
		if node.Item != 0 {
			roots = append(roots, node.Item)
		}
	}
	return sensitiveBodySchema{Nodes: s.Nodes, Roots: roots}
}

func (s sensitiveBodySchema) items() sensitiveBodySchema {
	var roots []int
	for _, id := range s.expandedRoots() {
		if item := s.Nodes[id].Item; item != 0 {
			roots = append(roots, item)
		}
	}
	return sensitiveBodySchema{Nodes: s.Nodes, Roots: roots}
}

func isSensitiveEncodedField(sensitive sensitiveBodySchema, name string) bool {
	nested := sensitive.child(name)
	return nested.isSensitive() || nested.items().isSensitive()
}

func redactJSON(v interface{}, depth int, sensitive sensitiveBodySchema) interface{} {
	if depth > maxRedactDepth {
		return redactionDepthMarker
	}
	if sensitive.isSensitive() {
		return "[REDACTED]"
	}
	switch val := v.(type) {
	case map[string]interface{}:
		out := make(map[string]interface{}, len(val))
		for k, child := range val {
			if sensitiveJSONKeys[normalizeSensitiveKey(k)] {
				out[k] = "[REDACTED]"
			} else {
				out[k] = redactJSON(child, depth+1, sensitive.child(k))
			}
		}
		return out
	case []interface{}:
		out := make([]interface{}, len(val))
		items := sensitive.items()
		for i, child := range val {
			out[i] = redactJSON(child, depth+1, items)
		}
		return out
	case string:
		return redactBase64String(val)
	default:
		return v
	}
}

func redactBase64String(value string) string {
	if strings.HasPrefix(value, "<bytes:") && strings.HasSuffix(value, ">") {
		return value
	}
	candidate := value
	if strings.HasPrefix(strings.ToLower(candidate), "data:") {
		comma := strings.IndexByte(candidate, ',')
		if comma < 0 || !strings.Contains(strings.ToLower(candidate[:comma]), ";base64") {
			return value
		}
		candidate = candidate[comma+1:]
	}
	if len(candidate) < 128 || isAllHex(candidate) {
		return value
	}

	urlAlphabet := strings.ContainsAny(candidate, "-_")
	for i, r := range candidate {
		valid := r >= 'A' && r <= 'Z' || r >= 'a' && r <= 'z' || r >= '0' && r <= '9'
		if urlAlphabet {
			valid = valid || r == '-' || r == '_'
		} else {
			valid = valid || r == '+' || r == '/'
		}
		if r == '=' {
			valid = i >= len(candidate)-2
		}
		if !valid {
			return value
		}
	}

	padded := strings.HasSuffix(candidate, "=")
	if padded && len(candidate)%4 != 0 || !padded && len(candidate)%4 == 1 {
		return value
	}
	var encoding *base64.Encoding
	switch {
	case urlAlphabet && padded:
		encoding = base64.URLEncoding.Strict()
	case urlAlphabet:
		encoding = base64.RawURLEncoding.Strict()
	case padded:
		encoding = base64.StdEncoding.Strict()
	default:
		encoding = base64.RawStdEncoding.Strict()
	}
	n, err := io.Copy(io.Discard, base64.NewDecoder(encoding, strings.NewReader(candidate)))
	if err != nil {
		return value
	}
	return fmt.Sprintf("<bytes:%d>", n)
}

func isAllHex(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range value {
		if !(r >= '0' && r <= '9' || r >= 'a' && r <= 'f' || r >= 'A' && r <= 'F') {
			return false
		}
	}
	return true
}

func decodeJSON(body []byte, sensitive sensitiveBodySchema) (interface{}, bool) {
	dec := json.NewDecoder(bytes.NewReader(body))
	dec.UseNumber()
	var parsed interface{}
	if err := dec.Decode(&parsed); err != nil {
		return nil, false
	}
	if err := dec.Decode(&struct{}{}); err != io.EOF {
		return nil, false
	}
	return redactJSON(parsed, 0, sensitive), true
}

func isTextMediaType(mediaType string) bool {
	return isJSONMediaType(mediaType) ||
		strings.HasPrefix(mediaType, "text/") ||
		mediaType == "application/xml" ||
		strings.HasSuffix(mediaType, "+xml") ||
		mediaType == "application/x-www-form-urlencoded"
}

func previewBody(body []byte, contentType string, sensitive sensitiveBodySchema) interface{} {
	if len(body) == 0 {
		return nil
	}
	if sensitive.isSensitive() {
		return "[REDACTED]"
	}
	mediaType, params, err := mime.ParseMediaType(contentType)
	if err != nil {
		mediaType = strings.ToLower(strings.TrimSpace(strings.SplitN(contentType, ";", 2)[0]))
	}
	if isJSONMediaType(mediaType) || mediaType == "" {
		if parsed, ok := decodeJSON(body, sensitive); ok {
			return parsed
		}
	}
	if mediaType == "application/x-www-form-urlencoded" {
		return previewForm(body, sensitive)
	}
	if strings.HasPrefix(mediaType, "multipart/") {
		if boundary := params["boundary"]; boundary != "" {
			if summary, ok := previewMultipart(body, boundary, sensitive); ok {
				return summary
			}
		}
		return fmt.Sprintf("<bytes:%d>", len(body))
	}
	if mediaType != "" && !isTextMediaType(mediaType) {
		return fmt.Sprintf("<bytes:%d>", len(body))
	}
	return redactBase64String(string(body))
}

func previewForm(body []byte, sensitive sensitiveBodySchema) string {
	raw := string(body)
	if _, err := url.ParseQuery(raw); err != nil {
		return fmt.Sprintf("<bytes:%d>", len(body))
	}
	parts := strings.Split(raw, "&")
	for i, part := range parts {
		key, value, found := strings.Cut(part, "=")
		decodedKey, keyErr := url.QueryUnescape(key)
		decodedValue, valueErr := url.QueryUnescape(value)
		if keyErr != nil || valueErr != nil {
			parts[i] = key + "=[REDACTED]"
			continue
		}
		if isSensitiveName(decodedKey) || isSensitiveEncodedField(sensitive, decodedKey) {
			parts[i] = key + "=[REDACTED]"
			continue
		}
		if nested := sensitive.child(decodedKey); len(nested.Roots) > 0 {
			if parsed, ok := decodeJSON([]byte(decodedValue), nested); ok {
				if encoded, err := encodeJSON(parsed, ""); err == nil {
					parts[i] = key + "=" + url.QueryEscape(encoded)
					continue
				}
			}
		}
		redacted := redactBase64String(decodedValue)
		if redacted != decodedValue {
			parts[i] = key + "=" + redacted
		} else if !found {
			parts[i] = key
		}
	}
	return strings.Join(parts, "&")
}

func previewMultipart(body []byte, boundary string, sensitive sensitiveBodySchema) (string, bool) {
	r := multipart.NewReader(bytes.NewReader(body), boundary)
	var lines []string
	for {
		part, err := r.NextPart()
		if err == io.EOF {
			break
		}
		if err != nil {
			return "", false
		}
		data, err := io.ReadAll(part)
		if err != nil {
			return "", false
		}
		name := part.FormName()
		if name == "" {
			name = "(unnamed)"
		}
		if part.FileName() != "" {
			lines = append(lines, fmt.Sprintf("%s: <bytes:%d>", name, len(data)))
			continue
		}
		value := previewBody(data, part.Header.Get("Content-Type"), sensitive.child(name))
		if isSensitiveName(name) || isSensitiveEncodedField(sensitive, name) {
			value = "[REDACTED]"
		}
		lines = append(lines, fmt.Sprintf("%s: %s", name, formatBodyPreview(value, 0)))
	}
	return strings.Join(lines, string(rune(10))), true
}

func encodeJSON(value interface{}, indent string) (string, error) {
	var out bytes.Buffer
	enc := json.NewEncoder(&out)
	enc.SetEscapeHTML(false)
	if indent != "" {
		enc.SetIndent(indent, indent)
	}
	if err := enc.Encode(value); err != nil {
		return "", err
	}
	return strings.TrimSuffix(out.String(), string(rune(10))), nil
}

func formatBodyPreview(value interface{}, capBytes int) string {
	if value == nil {
		return "(empty)"
	}
	var rendered string
	if _, ok := value.(string); ok {
		rendered = value.(string)
	} else if out, err := encodeJSON(value, "  "); err == nil {
		rendered = out
	} else {
		rendered = fmt.Sprint(value)
	}
	if capBytes > 0 && len(rendered) > capBytes {
		return rendered[:capBytes] + "... (truncated)"
	}
	return rendered
}

// readAndRestoreBody reads the body from a request or response, then restores
// it so downstream consumers can still read it.
func readAndRestoreBody(body io.ReadCloser) ([]byte, io.ReadCloser, error) {
	if body == nil {
		return nil, nil, nil
	}
	data, err := io.ReadAll(body)
	body.Close()
	return data, io.NopCloser(bytes.NewReader(data)), err
}

// formatHeaders formats headers for diagnostic output.
func formatHeaders(h http.Header) string {
	if len(h) == 0 {
		return "    (none)\n"
	}
	var sb strings.Builder
	keys := make([]string, 0, len(h))
	for k := range h {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		vals := h[k]
		sb.WriteString(fmt.Sprintf("    %s: %s\n", k, strings.Join(vals, ", ")))
	}
	return sb.String()
}

// redactURL returns the URL string with sensitive query parameters redacted.
func redactURL(u string) string {
	parsed, err := url.Parse(u)
	if err != nil {
		return u
	}
	// Userinfo may carry an HTTP Basic password.
	parsed.User = nil
	if parsed.RawQuery == "" {
		return parsed.String()
	}
	parts := strings.Split(parsed.RawQuery, "&")
	for i, part := range parts {
		key, _, _ := strings.Cut(part, "=")
		decoded, err := url.QueryUnescape(key)
		if err == nil && isSensitiveName(decoded) {
			parts[i] = key + "=[REDACTED]"
		}
	}
	parsed.RawQuery = strings.Join(parts, "&")
	return parsed.String()
}

// DebugClient wraps an HTTP client and logs request/response diagnostics to stderr.
type DebugClient struct {
	Inner               HTTPClient
	Stderr              io.Writer
	SensitiveBodyFields sensitiveBodySchema
}

// HTTPClient is the interface that SDK clients implement.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// Do executes the request, logging diagnostics before and after.
func (c *DebugClient) Do(req *http.Request) (*http.Response, error) {
	// Log request
	fmt.Fprintf(c.Stderr, "[DEBUG] Request: %s %s\n", req.Method, redactURL(req.URL.String()))
	fmt.Fprintf(c.Stderr, "[DEBUG] Request Headers:\n%s", formatHeaders(redactHeaders(req.Header)))
	if req.Body != nil {
		bodyData, restored, readErr := readAndRestoreBody(req.Body)
		req.Body = restored
		if readErr != nil {
			fmt.Fprintf(c.Stderr, "[DEBUG] Request Body Read Error: %v\n", readErr)
		} else {
			body := previewBody(bodyData, req.Header.Get("Content-Type"), c.SensitiveBodyFields)
			fmt.Fprintf(c.Stderr, "[DEBUG] Request Body:\n  %s\n", formatBodyPreview(body, maxBodyPreview))
		}
	}

	// Execute
	resp, err := c.Inner.Do(req)
	if err != nil {
		fmt.Fprintf(c.Stderr, "[DEBUG] Transport Error: %v\n", err)
		return nil, err
	}

	// Log response
	fmt.Fprintf(c.Stderr, "[DEBUG] Response: %d %s\n", resp.StatusCode, resp.Status)
	fmt.Fprintf(c.Stderr, "[DEBUG] Response Headers:\n%s", formatHeaders(redactHeaders(resp.Header)))
	if resp.Body != nil {
		if isStreamingResponse(resp) {
			// Reading a streaming body here buffers every event until the server closes the stream.
			fmt.Fprintf(c.Stderr, "[DEBUG] Response Body: <streaming %s; not captured>\n", resp.Header.Get("Content-Type"))
		} else {
			bodyData, restored, readErr := readAndRestoreBody(resp.Body)
			resp.Body = restored
			if readErr != nil {
				fmt.Fprintf(c.Stderr, "[DEBUG] Response Body Read Error: %v\n", readErr)
			} else if len(bodyData) > 0 {
				body := previewBody(bodyData, resp.Header.Get("Content-Type"), sensitiveBodySchema{})
				fmt.Fprintf(c.Stderr, "[DEBUG] Response Body:\n  %s\n", formatBodyPreview(body, maxBodyPreview))
			}
		}
	}

	return resp, nil
}

func isStreamingResponse(resp *http.Response) bool {
	mediaType := strings.ToLower(strings.TrimSpace(strings.SplitN(resp.Header.Get("Content-Type"), ";", 2)[0]))
	if strings.HasPrefix(mediaType, "text/event-stream") {
		return true
	}
	for _, suffix := range []string{"jsonl", "x-ndjson", "json-seq"} {
		if strings.HasSuffix(mediaType, "/"+suffix) || strings.HasSuffix(mediaType, "+"+suffix) {
			return true
		}
	}
	return false
}

// DryRunClient intercepts HTTP requests and returns a synthetic response
// without making any network calls.
type DryRunClient struct {
	Stderr              io.Writer
	Stdout              io.Writer
	JSON                bool
	Cmd                 *cobra.Command
	SensitiveBodyFields sensitiveBodySchema
}

type dryRunBody struct{ length int64 }

// NewDryRunBody returns an empty body that previews as <bytes:length> under --dry-run.
func NewDryRunBody(length int64) io.ReadCloser { return &dryRunBody{length: length} }

func (b *dryRunBody) Read([]byte) (int, error) { return 0, io.EOF }
func (b *dryRunBody) Close() error             { return nil }

type dryRunPreview struct {
	DryRun  bool                 `json:"dry_run"`
	Request dryRunPreviewRequest `json:"request"`
}

type dryRunPreviewRequest struct {
	Method  string      `json:"method"`
	URL     string      `json:"url"`
	Headers http.Header `json:"headers"`
	Body    interface{} `json:"body"`
}

func (c *DryRunClient) Do(req *http.Request) (*http.Response, error) {
	flagutil.MarkDryRunRequest(c.Cmd)
	var body interface{}
	var bodyData []byte
	if placeholder, ok := req.Body.(*dryRunBody); ok {
		body = fmt.Sprintf("<bytes:%d>", placeholder.length)
	} else if req.Body != nil {
		var restored io.ReadCloser
		var err error
		bodyData, restored, err = readAndRestoreBody(req.Body)
		req.Body = restored
		if err != nil {
			return nil, fmt.Errorf("read request body for dry-run preview: %w", err)
		}
		body = previewBody(bodyData, req.Header.Get("Content-Type"), c.SensitiveBodyFields)
	}
	requestURL := redactURL(req.URL.String())
	headers := redactHeaders(req.Header)
	if c.JSON {
		out := c.Stdout
		if out == nil {
			out = io.Discard
		}
		enc := json.NewEncoder(out)
		enc.SetEscapeHTML(false)
		if err := enc.Encode(dryRunPreview{
			DryRun: true,
			Request: dryRunPreviewRequest{
				Method: req.Method, URL: requestURL, Headers: headers, Body: body,
			},
		}); err != nil {
			return nil, fmt.Errorf("write dry-run preview: %w", err)
		}
	} else {
		stderr := c.Stderr
		if stderr == nil {
			stderr = io.Discard
		}
		fmt.Fprintf(stderr, "[DRY-RUN] Would send: %s %s\n", req.Method, requestURL)
		fmt.Fprintf(stderr, "[DRY-RUN] Headers:\n%s", formatHeaders(headers))
		if req.Body != nil {
			fmt.Fprintf(stderr, "[DRY-RUN] Body:\n  %s\n", formatBodyPreview(body, 0))
		}
		fmt.Fprintf(stderr, "[DRY-RUN] Network call skipped.\n")
	}

	contentType, syntheticBody := dryRunResponseShape(req.Header.Get("Accept"))
	if isTokenExchange(req, bodyData) {
		contentType = "application/json"
		syntheticBody = []byte(`{"access_token":"[DRY-RUN]","token_type":"Bearer","expires_in":3600}`)
	}
	return &http.Response{
		StatusCode: http.StatusOK,
		Status:     "200 OK",
		Header:     http.Header{"Content-Type": []string{contentType}},
		Body:       io.NopCloser(bytes.NewReader(syntheticBody)),
		Request:    req,
	}, nil
}

func isTokenExchange(req *http.Request, body []byte) bool {
	if req == nil || req.URL == nil {
		return false
	}
	if req.Method == http.MethodPost && strings.HasSuffix(strings.TrimSuffix(strings.ToLower(req.URL.Path), "/"), "/token") {
		return true
	}
	mediaType, _, _ := mime.ParseMediaType(req.Header.Get("Content-Type"))
	switch {
	case mediaType == "application/x-www-form-urlencoded":
		values, err := url.ParseQuery(string(body))
		return err == nil && values.Has("grant_type")
	case isJSONMediaType(mediaType):
		dec := json.NewDecoder(bytes.NewReader(body))
		dec.UseNumber()
		var value interface{}
		return dec.Decode(&value) == nil && containsJSONKey(value, "granttype")
	default:
		return false
	}
}

func containsJSONKey(value interface{}, normalizedKey string) bool {
	switch current := value.(type) {
	case map[string]interface{}:
		for key, child := range current {
			if normalizeSensitiveKey(key) == normalizedKey || containsJSONKey(child, normalizedKey) {
				return true
			}
		}
	case []interface{}:
		for _, child := range current {
			if containsJSONKey(child, normalizedKey) {
				return true
			}
		}
	}
	return false
}

func isJSONMediaType(mediaType string) bool {
	mediaType = strings.ToLower(mediaType)
	return mediaType == "application/json" || strings.HasSuffix(mediaType, "+json")
}

// Generated response dispatch may match the complete Content-Type value, parameters included.
func dryRunResponseShape(accept string) (string, []byte) {
	first := ""
	for _, part := range strings.Split(accept, ",") {
		segments := strings.Split(part, ";")
		baseType := strings.TrimSpace(segments[0])
		if baseType == "" {
			continue
		}

		params := make([]string, 0, len(segments)-1)
		for _, segment := range segments[1:] {
			param := strings.TrimSpace(segment)
			if param == "" {
				continue
			}
			name := strings.TrimSpace(strings.SplitN(param, "=", 2)[0])
			if strings.EqualFold(name, "q") {
				continue
			}
			params = append(params, param)
		}

		acceptedType := baseType
		if len(params) > 0 {
			acceptedType += "; " + strings.Join(params, "; ")
		}
		if baseType == "*/*" {
			return "application/json", []byte("{}")
		}
		if isJSONMediaType(baseType) {
			return acceptedType, []byte("{}")
		}
		if first == "" {
			first = acceptedType
		}
	}
	if first == "" {
		return "application/json", []byte("{}")
	}
	return first, nil
}

// WrapClientForDiagnostics wraps an HTTP client based on diagnostics mode.
// Returns the original client if no diagnostics flags are set.
func WrapClientForDiagnostics(cmd *cobra.Command, inner HTTPClient) HTTPClient {
	stderr := cmd.ErrOrStderr()
	if IsDryRun(cmd) {
		return &DryRunClient{Stderr: stderr, Stdout: cmd.OutOrStdout(), JSON: IsJSONDryRun(cmd), Cmd: cmd, SensitiveBodyFields: sensitiveBodyFieldsFor(cmd)}
	}
	if IsDebug(cmd) {
		return &DebugClient{Inner: inner, Stderr: stderr, SensitiveBodyFields: sensitiveBodyFieldsFor(cmd)}
	}
	return inner
}
