<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI;


class PaymentUpdatedRequest
{
    /**
     * Payment amount
     *
     * @var string $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public string $amount;

    /**
     *
     * @var \OpenAPI\OpenAPI\PaymentUpdatedType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\PaymentUpdatedType')]
    public PaymentUpdatedType $type;

    /**
     * @param  string  $amount
     * @param  \OpenAPI\OpenAPI\PaymentUpdatedType  $type
     * @phpstan-pure
     */
    public function __construct(string $amount, PaymentUpdatedType $type)
    {
        $this->amount = $amount;
        $this->type = $type;
    }
}