<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI;


enum PaymentUpdatedType: string
{
    case PaymentUpdated = 'payment.updated';
}
