<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI;


/** PolicyStep - A step in the policy */
class PolicyStep
{
    /**
     *
     * @var string $stepId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('stepId')]
    public string $stepId;

    /**
     * Approval configuration with escalation
     *
     * @var \OpenAPI\OpenAPI\ApprovalConfig $approval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('approval')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\ApprovalConfig')]
    public ApprovalConfig $approval;

    /**
     * @param  string  $stepId
     * @param  \OpenAPI\OpenAPI\ApprovalConfig  $approval
     * @phpstan-pure
     */
    public function __construct(string $stepId, ApprovalConfig $approval)
    {
        $this->stepId = $stepId;
        $this->approval = $approval;
    }
}