<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI;

use OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class PostFileRequest
{
    /**
     * A file
     *
     * @var \OpenAPI\OpenAPI\File $upload
     */
    #[SpeakeasyMetadata('multipartForm:file=true,name=upload')]
    public File $upload;

    /**
     * @param  \OpenAPI\OpenAPI\File  $upload
     * @phpstan-pure
     */
    public function __construct(File $upload)
    {
        $this->upload = $upload;
    }
}