<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI;

use OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class SecurityOption5
{
    /**
     *
     * @var string $mobileAuth
     */
    #[SpeakeasyMetadata('security:scheme=true,type=oauth2,name=Authorization')]
    public string $mobileAuth;

    /**
     * @param  string  $mobileAuth
     * @phpstan-pure
     */
    public function __construct(string $mobileAuth)
    {
        $this->mobileAuth = $mobileAuth;
    }
}