<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI;

use OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class SecurityOption3
{
    /**
     *
     * @var string $oauth2
     */
    #[SpeakeasyMetadata('security:scheme=true,type=oauth2,name=Authorization')]
    public string $oauth2;

    /**
     * @param  string  $oauth2
     * @phpstan-pure
     */
    public function __construct(string $oauth2)
    {
        $this->oauth2 = $oauth2;
    }
}