<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI;


/** String enum with x-speakeasy-enums as map (partial coverage) */
enum StringPartialMapFormat: string
{
    case InitialDraftVersion = 'draft_mode';
    case UnderReview = 'under_review';
    case LivePublishedContent = 'published_live';
    case ArchivedOld = 'archived_old';
}
