<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI;


/** TripleNamespaceConflictTest - A model that references Pet from foo, bar, and baz namespaces */
class TripleNamespaceConflictTest
{
    /**
     * A pet in the foo namespace
     *
     * @var \OpenAPI\OpenAPI\Foo\Pet $fooPet
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fooPet')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Foo\Pet')]
    public \OpenAPI\OpenAPI\Foo\Pet $fooPet;

    /**
     * A pet in the bar namespace
     *
     * @var \OpenAPI\OpenAPI\Bar\Pet $barPet
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('barPet')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Bar\Pet')]
    public \OpenAPI\OpenAPI\Bar\Pet $barPet;

    /**
     * A pet in the baz namespace with completely different schema
     *
     * @var \OpenAPI\OpenAPI\Baz\Pet $bazPet
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bazPet')]
    #[\Speakeasy\Serializer\Annotation\Type('\OpenAPI\OpenAPI\Baz\Pet')]
    public \OpenAPI\OpenAPI\Baz\Pet $bazPet;

    /**
     * @param  \OpenAPI\OpenAPI\Foo\Pet  $fooPet
     * @param  \OpenAPI\OpenAPI\Bar\Pet  $barPet
     * @param  \OpenAPI\OpenAPI\Baz\Pet  $bazPet
     * @phpstan-pure
     */
    public function __construct(\OpenAPI\OpenAPI\Foo\Pet $fooPet, \OpenAPI\OpenAPI\Bar\Pet $barPet, \OpenAPI\OpenAPI\Baz\Pet $bazPet)
    {
        $this->fooPet = $fooPet;
        $this->barPet = $barPet;
        $this->bazPet = $bazPet;
    }
}