<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI;

use OpenAPI\OpenAPI\Utils\SpeakeasyMetadata;
class UpdateUserRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \OpenAPI\OpenAPI\User $user
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public User $user;

    /**
     * @param  string  $id
     * @param  \OpenAPI\OpenAPI\User  $user
     * @phpstan-pure
     */
    public function __construct(string $id, User $user)
    {
        $this->id = $id;
        $this->user = $user;
    }
}