/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * AllOfWithFactoredOutProperties
 *
 * <p>An object with allOf and factored out properties.
 */
public class AllOfWithFactoredOutProperties {
    /**
     * An overriding property.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("anOverridingProperty")
    private String anOverridingProperty;

    /**
     * Another property.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("anotherProperty")
    private String anotherProperty;

    /**
     * An extra property.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("anExtraProperty")
    private String anExtraProperty;

    @JsonCreator
    public AllOfWithFactoredOutProperties(
            @JsonProperty("anOverridingProperty") @Nullable String anOverridingProperty,
            @JsonProperty("anotherProperty") @Nullable String anotherProperty,
            @JsonProperty("anExtraProperty") @Nullable String anExtraProperty) {
        this.anOverridingProperty = anOverridingProperty;
        this.anotherProperty = anotherProperty;
        this.anExtraProperty = anExtraProperty;
    }

    public AllOfWithFactoredOutProperties() {
        this(null, null, null);
    }

    /**
     * An overriding property.
     */
    public Optional<String> anOverridingProperty() {
        return Optional.ofNullable(this.anOverridingProperty);
    }

    /**
     * Another property.
     */
    public Optional<String> anotherProperty() {
        return Optional.ofNullable(this.anotherProperty);
    }

    /**
     * An extra property.
     */
    public Optional<String> anExtraProperty() {
        return Optional.ofNullable(this.anExtraProperty);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * An overriding property.
     */
    public AllOfWithFactoredOutProperties withAnOverridingProperty(@Nullable String anOverridingProperty) {
        this.anOverridingProperty = anOverridingProperty;
        return this;
    }

    /**
     * Another property.
     */
    public AllOfWithFactoredOutProperties withAnotherProperty(@Nullable String anotherProperty) {
        this.anotherProperty = anotherProperty;
        return this;
    }

    /**
     * An extra property.
     */
    public AllOfWithFactoredOutProperties withAnExtraProperty(@Nullable String anExtraProperty) {
        this.anExtraProperty = anExtraProperty;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AllOfWithFactoredOutProperties other = (AllOfWithFactoredOutProperties) o;
        return Utils.enhancedDeepEquals(this.anOverridingProperty, other.anOverridingProperty)
                && Utils.enhancedDeepEquals(this.anotherProperty, other.anotherProperty)
                && Utils.enhancedDeepEquals(this.anExtraProperty, other.anExtraProperty);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(anOverridingProperty, anotherProperty, anExtraProperty);
    }

    @Override
    public String toString() {
        return Utils.toString(
                AllOfWithFactoredOutProperties.class,
                "anOverridingProperty",
                anOverridingProperty,
                "anotherProperty",
                anotherProperty,
                "anExtraProperty",
                anExtraProperty);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String anOverridingProperty;

        private String anotherProperty;

        private String anExtraProperty;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * An overriding property.
         */
        public Builder anOverridingProperty(@Nullable String anOverridingProperty) {
            this.anOverridingProperty = anOverridingProperty;
            return this;
        }

        /**
         * Another property.
         */
        public Builder anotherProperty(@Nullable String anotherProperty) {
            this.anotherProperty = anotherProperty;
            return this;
        }

        /**
         * An extra property.
         */
        public Builder anExtraProperty(@Nullable String anExtraProperty) {
            this.anExtraProperty = anExtraProperty;
            return this;
        }

        public AllOfWithFactoredOutProperties build() {
            return new AllOfWithFactoredOutProperties(anOverridingProperty, anotherProperty, anExtraProperty);
        }
    }
}
