/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * ChatResponseBody
 *
 * <p>A stream containing chat completion tokens
 */
public class ChatResponseBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private String data;

    @JsonCreator
    public ChatResponseBody(@JsonProperty("data") @Nullable String data) {
        this.data = data;
    }

    public ChatResponseBody() {
        this(null);
    }

    public Optional<String> data() {
        return Optional.ofNullable(this.data);
    }

    public static Builder builder() {
        return new Builder();
    }

    public ChatResponseBody withData(@Nullable String data) {
        this.data = data;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ChatResponseBody other = (ChatResponseBody) o;
        return Utils.enhancedDeepEquals(this.data, other.data);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(data);
    }

    @Override
    public String toString() {
        return Utils.toString(ChatResponseBody.class, "data", data);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String data;

        private Builder() {
            // force use of static builder() method
        }

        public Builder data(@Nullable String data) {
            this.data = data;
            return this;
        }

        public ChatResponseBody build() {
            return new ChatResponseBody(data);
        }
    }
}
