/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class GetPositionalDefaultRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;

    @JsonCreator
    public GetPositionalDefaultRequest(@Nullable String id) {
        this.id = Optional.ofNullable(id).orElse(Builder._SINGLETON_VALUE_Id.value());
    }

    public GetPositionalDefaultRequest() {
        this(null);
    }

    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public GetPositionalDefaultRequest withId(@Nonnull String id) {
        this.id = Utils.checkNotNull(id, "id");
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetPositionalDefaultRequest other = (GetPositionalDefaultRequest) o;
        return Utils.enhancedDeepEquals(this.id, other.id);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(id);
    }

    @Override
    public String toString() {
        return Utils.toString(GetPositionalDefaultRequest.class, "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String id;

        private Builder() {
            // force use of static builder() method
        }

        public Builder id(@Nonnull String id) {
            this.id = Utils.checkNotNull(id, "id");
            return this;
        }

        public GetPositionalDefaultRequest build() {
            return new GetPositionalDefaultRequest(id);
        }

        private static final LazySingletonValue<String> _SINGLETON_VALUE_Id =
                new LazySingletonValue<>("id", "\"default-id\"", new TypeReference<String>() {});
    }
}
