/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.GetPositionalDefault;
import org.openapis.openapi.utils.Headers;
import org.openapis.openapi.utils.Utils;

public class GetPositionalDefaultRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers();
    private final GetPositionalDefaultRequest.Builder pojoBuilder;
    private GetPositionalDefaultRequest request;
    private boolean _setterCalled;

    public GetPositionalDefaultRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetPositionalDefaultRequest.builder();
    }

    public GetPositionalDefaultRequestBuilder id(@Nonnull String id) {
        this.pojoBuilder.id(id);
        this._setterCalled = true;
        return this;
    }

    private GetPositionalDefaultRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }

    public GetPositionalDefaultRequestBuilder header(String name, String value) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(value, "value");
        this._headers.add(name, value);
        return this;
    }

    /**
     * Executes the request and returns the response.
     *
     * @return The response from the server.
     */
    public GetPositionalDefaultResponse call() {
        RequestOperation<GetPositionalDefaultRequest, GetPositionalDefaultResponse> operation =
                new GetPositionalDefault.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
