openapi: 3.1.0
info:
  title: Minimal document for testing README sections insertion, removal and editing.
  version: 2.0.0
  summary: |-
    - pagination is enabled
servers:
  - url: http://localhost:12345
security: []

paths:
  /operation/1:
    get:
      operationId: op1
      tags:
        - tag1
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          required: true
      x-speakeasy-pagination:
        type: offsetLimit
        inputs:
          - name: page
            in: parameters
            type: page
        outputs:
          results: $.resultArray
      responses:
        "200":
          description: OK
