# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module OpenApiSDK
  module Operations
    module V2
      module Schemas

        class GetFullyFlattenedRequestRequest
          extend T::Sig
          include Crystalline::MetadataFields

          field :lang, ::String, {'query_param': {'field_name': "lang", 'style': "form", 'explode': true}}

          field(
            :request_body,
            Operations::V2::Schemas::GetFullyFlattenedRequestRequestBody,
            {'request': {'media_type': "application/json"}}
          )

          field(
            :max_length,
            Crystalline::Nilable.new(::Integer),
            {'query_param': {'field_name': "max_length", 'style': "form", 'explode': true}}
          )

          sig {
            params(
              lang: ::String,
              request_body: Operations::V2::Schemas::GetFullyFlattenedRequestRequestBody,
              max_length: T.nilable(::Integer)
            )
              .void
          }
          def initialize(lang:, request_body:, max_length: nil)
            @lang = lang
            @request_body = request_body
            @max_length = max_length
          end

          sig { params(other: T.untyped).returns(T::Boolean) }
          def ==(other)
            return false unless other.is_a?(self.class)
            return false unless @lang == other.lang
            return false unless @request_body == other.request_body
            return false unless @max_length == other.max_length
            true
          end
        end
      end
    end
  end
end
