// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// ErrorType1 - An error of type one.
type ErrorType1 struct {
	// Error code
	Code   *string `const:"rate_limit_exceeded" json:"code"`
	Error_ string  `json:"error"`
	// Error message
	Message  int64                   `json:"message"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ErrorType1{}

func (e *ErrorType1) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
