//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using NodaTime;
using Speakeasy.OpenAPI;
using Speakeasy.OpenAPI.Bar;
using Speakeasy.OpenAPI.Baz;
using Speakeasy.OpenAPI.Foo;
using Speakeasy.OpenAPI.Utils;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Numerics;
using System.Threading.Tasks;
using Xunit;

public class SDKTests
{

    [Fact(Skip = "incomplete test found please make sure to address the following errors: [`workflow step testEndpoint.test referencing operation testEndpoint is missing required request body`, `workflow step testEndpoint.test referencing operation testEndpoint missing required path parameter testName`]")]
    public async Task TestSDK_TestEndpoint()
    {
        await Task.CompletedTask;
    }

    [Fact]
    public async Task TestSDK_GetUserTestWithStatusCodeOnly()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getUser-testWithStatusCodeOnly");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.GetUserAsync(id: "test123");

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact(Skip = "test marked as skipped for csharp or generated unit tests not production ready yet")]
    public async Task TestSDK_GetUserTestWithResponseBody()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getUser-testWithResponseBody");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.GetUserAsync(id: "test123");

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.User);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new User() {
                Id = "test123",
                Email = "Trystan_Crooks@hotmail.com",
                FirstName = "Trystan",
                LastName = "Crooks",
                Age = 32D,
                PostalCode = "94110",
                Metadata = new Metadata() {
                    Allergies = "none",
                    AdditionalProperties = new Dictionary<string, string>() {
                        { "color", "red" },
                        { "height", "182" },
                        { "weight", "77" },
                        { "is_smoking", "true" },
                    },
                },
            }),
            CommonHelpers.NormalizeJson(res.User)
        );
    }

    [Fact(Skip = "test marked as skipped for csharp or generated unit tests not production ready yet")]
    public async Task TestSDK_GetUserTestWithResponseBodyFields()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getUser-testWithResponseBodyFields");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.GetUserAsync(id: "test123");

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.User?.Metadata?.Allergies);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("none"),
            CommonHelpers.NormalizeDateTimeStrings(res.User?.Metadata?.Allergies)
        );
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("red"),
            CommonHelpers.NormalizeDateTimeStrings(res.User?.Metadata?.AdditionalProperties?["color"])
        );
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("test123"),
            CommonHelpers.NormalizeDateTimeStrings(res.User?.AssociatedIds?[1])
        );
    }

    [Fact]
    public async Task TestSDK_GetFullyFlattenedRequestNamedExampleThatIsntMatchedAcrossDifferentExamples()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getFullyFlattenedRequest-namedExampleThatIsntMatchedAcrossDifferentExamples");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_URL") ?? "",
            client: testHttpClient,
            security: new Security() {
                Option6 = new SecurityOption6() {
                    ClientID = "<YOUR_CLIENT_ID_HERE>",
                    ClientSecret = "<YOUR_CLIENT_SECRET_HERE>",
                    TokenURL = "/_mockserver/oauth2/token",
                },
            }
        );
        var res = await sdk.GetFullyFlattenedRequestAsync(
            lang: "en",
            requestBody: new GetFullyFlattenedRequestRequestBody() {
                Name = "<value>",
            }
        );

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact(Skip = "test marked as skipped for csharp or generated unit tests not production ready yet")]
    public async Task TestSDK_PostFile()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("postFile");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        PostFileRequest req = new PostFileRequest() {
            Upload = new Speakeasy.OpenAPI.File() {
                FileName = "postfiletest.txt",
                Content = System.IO.File.ReadAllBytes("../../../../.speakeasy/testfiles/postfiletest.txt"),
            },
        };

        var res = await sdk.PostFileAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.File);
        Assert.Equal(
            System.Text.Encoding.UTF8.GetBytes("0x8fBAEeAAE7"),
            res.File
        );
    }

    [Fact]
    public async Task TestSDK_GetPolymorphism()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getPolymorphism");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.GetPolymorphismAsync();

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.Object);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new GetPolymorphismResponseBody() {
                OneOfWithUnionDescription = OneOfWithUnionDescription.CreateExhaustiveObject(
                    new ExhaustiveObject() {
                        Str = "example",
                        Bool = true,
                        Integer = 999999,
                        Int32 = 1,
                        Num = 1.1D,
                        Float32 = 7754.37F,
                        EnumProp = Speakeasy.OpenAPI.Enum.First,
                        Date = LocalDate.FromDateTime(System.DateTime.Parse("2022-04-06")),
                        DateTime = System.DateTime.Parse("2020-01-01T00:00:00Z").ToUniversalTime(),
                        Anything = "<value>",
                        BoolOpt = true,
                        IntOptNull = 999999,
                        NumOptNull = 1.1D,
                        IntEnum = Speakeasy.OpenAPI.IntEnum.Third,
                        Int32Enum = Int32Enum.SixtyNine,
                        Bigint = BigInteger.Parse("815677"),
                        BigintStr = BigInteger.Parse("12345678901234567890"),
                        DecimalStr = 7753.11M,
                        Obj = new SimpleObject() {
                            Str = "example",
                        },
                        Map = new Dictionary<string, SimpleObject>() {

                        },
                        Arr = new List<SimpleObject>() {
                            new SimpleObject() {
                                Str = "example",
                            },
                            new SimpleObject() {
                                Str = "example",
                            },
                            new SimpleObject() {
                                Str = "example",
                            },
                        },
                        Any = Any.CreateStr("<value>"),
                        Type = "0",
                        NullableIntEnum = Speakeasy.OpenAPI.NullableIntEnum.Third,
                        NullableStringEnum = NullableStringEnum.First,
                        Color = Speakeasy.OpenAPI.Color.Green,
                        Icon = Icon.Tick,
                        HeroWidth = HeroWidth.FourHundredAndEighty,
                    }
                ),
                OneOfWithFactoredOutProperties = OneOfWithFactoredOutProperties.CreateOneOfWithFactoredOutPropertiesSimpleObject(new OneOfWithFactoredOutPropertiesSimpleObject() {
                    Str = "example",
                    AnExtraProperty = "example",
                }),
                SimpleAllOf = new SimpleAllOf() {
                    Str = "example",
                    Bool = true,
                },
                AllOfWithFactoredOutProperties = new AllOfWithFactoredOutProperties() {
                    AnOverridingProperty = "example",
                    AnotherProperty = "example",
                    AnExtraProperty = "example",
                },
            }),
            CommonHelpers.NormalizeJson(res.Object)
        );
    }

    [Fact(Skip = "test marked as skipped for csharp or generated unit tests not production ready yet")]
    public async Task TestSDK_GetUnionErrors()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getUnionErrors");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        GetUnionErrorsResponse? res = await sdk.GetUnionErrorsAsync(page: 12);

        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.Object);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new GetUnionErrorsResponseBody() {
                Pages = new List<string>() {},
            }),
            CommonHelpers.NormalizeJson(res.Object)
        );

        while (res != null)
        {
            // handle items

            res = await res.Next!();
        }
    }

    [Fact]
    public async Task TestSDK_GetRequestBodyFlattenedAway()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getRequestBodyFlattenedAway");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            loneQueryParam: "<value>",
            client: testHttpClient
        );
        var res = await sdk.GetRequestBodyFlattenedAwayAsync();

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestSDK_GetUserSuccess()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getUser-success");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.GetUserAsync(id: "<id>");

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.User);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new User() {
                Id = "8ffac18c-7d88-4879-b057-e5f45b9ce7dg",
                Email = "Trystan_Crooks@hotmail.com",
            }),
            CommonHelpers.NormalizeJson(res.User)
        );
    }

    [Fact(Skip = "incomplete test found please make sure to address the following errors: [`workflow step chat.test referencing operation chat is not currently supported`]")]
    public async Task TestSDK_Chat()
    {
        await Task.CompletedTask;
    }

    [Fact]
    public async Task TestSDK_GetBinaryDefaultResponse()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getBinaryDefaultResponse");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.GetBinaryDefaultResponseAsync();

        // handle response
        Assert.NotNull(res);
        Assert.DoesNotContain((int)res.HttpMeta.Response.StatusCode, new int[] { 200, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423, 424, 425, 426, 428, 429, 431, 451, 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511 });
        Assert.NotNull(res.Bytes);
        Assert.Equal(
            System.Text.Encoding.UTF8.GetBytes("0xf58AcDF799"),
            res.Bytes
        );
    }

    [Fact]
    public async Task TestSDK_UserLifecycle()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("user-lifecycle");

        TestHelpers.AuthenticateOutputs? authenticateOutputs = await TestHelpers.Authenticate();
        Assert.NotNull(authenticateOutputs);
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                UserPassAuth = new UserPassAuth() {
                    Username = "<USERNAME>",
                    Password = "<PASSWORD>",
                },
            },
            client: testHttpClient
        );
        BaseUser createReq = new BaseUser() {
            Email = "Trystan_Crooks@hotmail.com",
            FirstName = "Trystan",
            LastName = "Crooks",
            Age = 32D,
            PostalCode = "94110",
            Metadata = new Metadata() {
                Allergies = "none",
                AdditionalProperties = new Dictionary<string, string>() {
                    { "color", "red" },
                    { "height", "182" },
                    { "weight", "77" },
                    { "is_smoking", "true" },
                },
            },
        };

        var createRes = await sdk.CreateUserAsync(createReq);

        // handle response
        Assert.NotNull(createRes);
        Assert.Equal(200, (int)createRes.HttpMeta.Response.StatusCode);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Trystan_Crooks@hotmail.com"),
            CommonHelpers.NormalizeDateTimeStrings(createRes.User?.Email)
        );
        Assert.NotNull(createRes.User?.PostalCode);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("94110"),
            CommonHelpers.NormalizeDateTimeStrings(createRes.User?.PostalCode)
        );

        Assert.NotNull(createRes.User?.Id);
        var getRes = await sdk.GetUserAsync(id: createRes.User?.Id!);

        // handle response
        Assert.NotNull(getRes);
        Assert.Equal(200, (int)getRes.HttpMeta.Response.StatusCode);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Trystan_Crooks@hotmail.com"),
            CommonHelpers.NormalizeDateTimeStrings(getRes.User?.Email)
        );
        Assert.NotNull(getRes.User?.FirstName);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Trystan"),
            CommonHelpers.NormalizeDateTimeStrings(getRes.User?.FirstName)
        );
        Assert.NotNull(getRes.User?.LastName);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Crooks"),
            CommonHelpers.NormalizeDateTimeStrings(getRes.User?.LastName)
        );
        Assert.Equal(
            32D,
            getRes.User?.Age
        );
        Assert.NotNull(getRes.User?.PostalCode);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("94110"),
            CommonHelpers.NormalizeDateTimeStrings(getRes.User?.PostalCode)
        );

        Assert.NotNull(getRes.User);
        var updateRes = await sdk.UpdateUserAsync(
            id: createRes.User?.Id!,
            user: getRes.User!
        );

        // handle response
        Assert.NotNull(updateRes);
        Assert.Equal(200, (int)updateRes.HttpMeta.Response.StatusCode);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Trystan_Crooks@hotmail.com"),
            CommonHelpers.NormalizeDateTimeStrings(updateRes.User?.Email)
        );
        Assert.NotNull(updateRes.User?.FirstName);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Trystan"),
            CommonHelpers.NormalizeDateTimeStrings(updateRes.User?.FirstName)
        );
        Assert.NotNull(updateRes.User?.LastName);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Crooks"),
            CommonHelpers.NormalizeDateTimeStrings(updateRes.User?.LastName)
        );
        Assert.Equal(
            32D,
            updateRes.User?.Age
        );
        Assert.NotNull(updateRes.User?.PostalCode);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("94107"),
            CommonHelpers.NormalizeDateTimeStrings(updateRes.User?.PostalCode)
        );

        Assert.NotNull(updateRes.User?.Email);
        var updateAgainRes = await sdk.UpdateUserAsync(
            id: createRes.User?.Id!,
            user: new User() {
                Id = createRes.User?.Id!,
                Email = updateRes.User?.Email!,
                FirstName = updateRes.User?.FirstName,
                LastName = updateRes.User?.LastName,
                Age = 33D,
                PostalCode = "94110",
                Metadata = updateRes.User?.Metadata,
            }
        );

        // handle response
        Assert.NotNull(updateAgainRes);
        Assert.Equal(200, (int)updateAgainRes.HttpMeta.Response.StatusCode);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Trystan_Crooks@hotmail.com"),
            CommonHelpers.NormalizeDateTimeStrings(updateAgainRes.User?.Email)
        );
        Assert.NotNull(updateAgainRes.User?.FirstName);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Trystan"),
            CommonHelpers.NormalizeDateTimeStrings(updateAgainRes.User?.FirstName)
        );
        Assert.NotNull(updateAgainRes.User?.LastName);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Crooks"),
            CommonHelpers.NormalizeDateTimeStrings(updateAgainRes.User?.LastName)
        );
        Assert.Equal(
            33D,
            updateAgainRes.User?.Age
        );
        Assert.NotNull(updateAgainRes.User?.PostalCode);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("94110"),
            CommonHelpers.NormalizeDateTimeStrings(updateAgainRes.User?.PostalCode)
        );

        var deleteRes = await sdk.DeleteUserAsync(id: createRes.User?.Id!);

        // handle response
        Assert.NotNull(deleteRes);
        Assert.Equal(200, (int)deleteRes.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestSDK_UpdateUser()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("updateUser");

        TestHelpers.UserSetupOutputs? setupOutputs = await TestHelpers.UserSetup();
        Assert.NotNull(setupOutputs);
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        Assert.NotNull(setupOutputs.User?.Id);
        Assert.NotNull(setupOutputs.User);
        var res = await sdk.UpdateUserAsync(
            id: setupOutputs.User?.Id!,
            user: setupOutputs.User!
        );

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Trystan_Crooks@hotmail.com"),
            CommonHelpers.NormalizeDateTimeStrings(res.User?.Email)
        );
        Assert.NotNull(res.User?.FirstName);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Trystan"),
            CommonHelpers.NormalizeDateTimeStrings(res.User?.FirstName)
        );
        Assert.NotNull(res.User?.LastName);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("Crooks"),
            CommonHelpers.NormalizeDateTimeStrings(res.User?.LastName)
        );
        Assert.Equal(
            33D,
            res.User?.Age
        );
        Assert.NotNull(res.User?.PostalCode);
        Assert.Equal(
            CommonHelpers.NormalizeDateTimeStrings("94107"),
            CommonHelpers.NormalizeDateTimeStrings(res.User?.PostalCode)
        );

        Assert.NotNull(setupOutputs.User?.Id);
        await TestHelpers.UserTeardown(new TestHelpers.UserTeardownInputs() {
            Id = setupOutputs.User?.Id!,
        });
    }

    [Fact]
    public async Task TestSDK_GetNestedIntegerString()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getNestedIntegerString");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.GetNestedIntegerStringAsync();

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.TaskResponse);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new TaskResponse() {
                Task = new ReviewTask() {
                    Id = "task-123",
                    Name = "Review Task",
                    Policy = new MCPPolicy() {
                        PolicyId = "policy-456",
                        Steps = new List<PolicyStep>() {
                            new PolicyStep() {
                                StepId = "step-1",
                                Approval = new ApprovalConfig() {
                                    Approvers = new List<string>() {
                                        "user-1",
                                        "user-2",
                                    },
                                    Escalation = new Escalation() {
                                        Enabled = true,
                                        Expiration = "86400",
                                        FallbackApprovers = new List<string>() {
                                            "admin-1",
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            }),
            CommonHelpers.NormalizeJson(res.TaskResponse)
        );
    }

    [Fact]
    public async Task TestSDK_CreateUserRequestOnly()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("createUser-request-only");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        BaseUser req = new BaseUser() {
            Email = "request-only@example.com",
        };

        var res = await sdk.CreateUserAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.User);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new User() {
                Id = "8ffac18c-7d88-4879-b057-e5f45b9ce7de",
                Email = "Aglae92@gmail.com",
                Gender = Gender.Other,
            }),
            CommonHelpers.NormalizeJson(res.User)
        );
    }

    [Fact]
    public async Task TestSDK_CreateUserPairedExample()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("createUser-paired-example");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        BaseUser req = new BaseUser() {
            Email = "paired@example.com",
            FirstName = "John",
        };

        var res = await sdk.CreateUserAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.User);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new User() {
                Id = "user-paired",
                Email = "paired@example.com",
                FirstName = "John",
            }),
            CommonHelpers.NormalizeJson(res.User)
        );
    }

    [Fact]
    public async Task TestSDK_CreateUserResponseOnly()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("createUser-response-only");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        BaseUser req = new BaseUser() {
            Id = "8ffac18c-7d88-4879-b057-e5f45b9ce7de",
            Email = "Virginie47@gmail.com",
            Gender = Gender.Other,
        };

        var res = await sdk.CreateUserAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.User);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new User() {
                Id = "user-response",
                Email = "response-only@example.com",
            }),
            CommonHelpers.NormalizeJson(res.User)
        );
    }

    [Fact]
    public async Task TestSDK_GetNamedPrimitiveUnion()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getNamedPrimitiveUnion");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.GetNamedPrimitiveUnionAsync();

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.SomeUnion);
        Assert.Equal(
            CommonHelpers.NormalizeJson(SomeUnion.CreateFoo(
                true
            )),
            CommonHelpers.NormalizeJson(res.SomeUnion)
        );
    }

    [Fact]
    public async Task TestSDK_GetEmptyObjectError()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getEmptyObjectError");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.GetEmptyObjectErrorAsync();

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.Object);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new GetEmptyObjectErrorResponseBody() {
                Success = true,
            }),
            CommonHelpers.NormalizeJson(res.Object)
        );
    }

    [Fact]
    public async Task TestSDK_ParenthesesInPathAllowed()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("parenthesesInPathAllowed");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.ParenthesesInPathAllowedAsync(
            id: "<id>",
            templateBracesTest: new TemplateBracesTest() {
                FieldWithBracesInExample = "A string with {{ double braces }} and { single braces }\nand \\{\\{ escaped curlies \\}\\} and `backticks`.\nand \\`escaped backticks\\` and double slashes\\\\\nand 'single quotes' and \"double quotes\".\nand  \\'escaped single quotes\\' and \\\"escaped double quotes\\\".\n",
            }
        );

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.TemplateBracesTest);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new TemplateBracesTest() {
                FieldWithBracesInDefault = "A string with {{ double braces }} and { single braces }\nand \\{\\{ escaped curlies \\}\\} and `backticks`.\nand \\`escaped backticks\\` and double slashes\\\\\nand 'single quotes' and \"double quotes\".\nand  \\'escaped single quotes\\' and \\\"escaped double quotes\\\".\n",
                FieldWithBracesInExample = "A string with {{ double braces }} and { single braces }\nand \\{\\{ escaped curlies \\}\\} and `backticks`.\nand \\`escaped backticks\\` and double slashes\\\\\nand 'single quotes' and \"double quotes\".\nand  \\'escaped single quotes\\' and \\\"escaped double quotes\\\".\n",
            }),
            CommonHelpers.NormalizeJson(res.TemplateBracesTest)
        );
    }

    [Fact]
    public async Task TestSDK_GetErrorOnlyExample()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getErrorOnlyExample");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.GetErrorOnlyExampleAsync();

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.Object);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new GetErrorOnlyExampleResponseBody() {
                Id = "<id>",
                Name = "<value>",
            }),
            CommonHelpers.NormalizeJson(res.Object)
        );
    }

    [Fact]
    public async Task TestSDK_GetDuplicateExportCollision()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getDuplicateExportCollision");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.GetDuplicateExportCollisionAsync();

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.Object);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new GetDuplicateExportCollisionResponseBody() {}),
            CommonHelpers.NormalizeJson(res.Object)
        );
    }

    [Fact]
    public async Task TestSDK_CreateWithUnion()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("createWithUnion");
        var sdk = new SDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            client: testHttpClient
        );
        var res = await sdk.CreateWithUnionAsync(shapeRequest: new ShapeRequest() {
            Name = "<value>",
            Shape = Shape.CreateRectangle(
                new Rectangle() {
                    Type = "rectangle",
                    Width = 3125.73D,
                    Height = 922.51D,
                }
            ),
        });

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
        Assert.NotNull(res.Object);
        Assert.Equal(
            CommonHelpers.NormalizeJson(new CreateWithUnionResponseBody() {}),
            CommonHelpers.NormalizeJson(res.Object)
        );
    }

    [Fact(Skip = "incomplete test found please make sure to address the following errors: [`workflow step paginationOffsetNullable.test referencing operation paginationOffsetNullable not found in document`]")]
    public async Task TestSDK_PaginationOffsetNullable()
    {
        await Task.CompletedTask;
    }

    [Fact(Skip = "incomplete test found please make sure to address the following errors: [`workflow step renderAsset.test referencing operation renderAsset is not currently supported`]")]
    public async Task TestSDK_RenderAsset()
    {
        await Task.CompletedTask;
    }
}
