package namespaces

import (
	"testing"

	"github.com/speakeasy-api/openapi-generation/v2/pkg/generate/snapshots/snaptest"
)

// Regression test: when a cursor/pagination type in Operations has an array
// field whose items are in a custom namespace sub-package, sanitizeArray was
// adding a `use` import for the namespace without checking
// hasCustomModelNamespace. The actual type reference uses a fully qualified
// name (no short import needed), so the `use` statement is unused and fails
// the pint no_unused_imports lint rule.
func TestSnapPhpModelNamespaceUnusedImport(t *testing.T) {
	t.Parallel()

	spec := `openapi: 3.1.0
info:
  title: Unused Import Test
  version: 1.0.0
servers:
  - url: https://api.example.com
paths:
  /ns1/items:
    get:
      operationId: listItems
      tags:
        - ns1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListItemsResponse'
  /things:
    post:
      operationId: createThing
      tags:
        - other
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [item]
              properties:
                item:
                  $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
components:
  schemas:
    Item:
      type: object
      required: [id, name]
      properties:
        id:
          type: string
        name:
          type: string
      x-speakeasy-model-namespace: ns1
    ListItemsResponse:
      type: object
      required: [cursor]
      properties:
        cursor:
          $ref: '#/components/schemas/ListItemsCursorBody'
    ListItemsCursorBody:
      type: object
      required: [data, hasMore]
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        hasMore:
          type: boolean
`

	genYaml := `php:
  packageName: test/sdk
`

	expectedSnapshotFiles := []string{
		"src/Models/Components/ListItemsCursorBody.php",
	}

	expectedSnapshot := `--- src/Models/Components/ListItemsCursorBody.php ---
<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * Generated under the AGPL-3.0-only license.
 * SPDX-License-Identifier: AGPL-3.0-only
 */

declare(strict_types=1);

namespace OpenAPI\OpenAPI\Models\Components;


class ListItemsCursorBody
{
    /**
     * $data
     *
     * @var array<\OpenAPI\OpenAPI\Models\Ns1\Item> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\OpenAPI\OpenAPI\Models\Ns1\Item>')]
    public array $data;

    /**
     *
     * @var bool $hasMore
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasMore')]
    public bool $hasMore;

    /**
     * @param  array<\OpenAPI\OpenAPI\Models\Ns1\Item>  $data
     * @param  bool  $hasMore
     * @phpstan-pure
     */
    public function __construct(array $data, bool $hasMore)
    {
        $this->data = $data;
        $this->hasMore = $hasMore;
    }
}

` // end of snapshot

	snaptest.DoTestSnapshot(t, snaptest.Options{
		Spec:         spec,
		GenYaml:      genYaml,
		IncludeGlobs: expectedSnapshotFiles,
		Expected:     expectedSnapshot,
	})
}
