/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

let value: ParenthesesInPathAllowedRequest = {
  id: "<id>",
  templateBracesTest: {
    fieldWithBracesInExample: "A string with {{"{{"}} double braces }} and { single braces }\nand \\{\\{ escaped curlies \\}\\} and `backticks`.\nand \\`escaped backticks\\` and double slashes\\\\\nand 'single quotes' and \"double quotes\".\nand  \\'escaped single quotes\\' and \\\"escaped double quotes\\\".\n",
  },
};