// Package merge implements the 3-way merge subsystem for SDK generation.
//
// This package provides the core merge algorithm and data structures for
// preserving user modifications across regenerations. The implementation
// is split between this package (pure merge logic) and the patches package
// (integration with Git and filesystem).
//
// # Architecture Overview
//
// The merge system uses Git's object database as an efficient content-addressable
// store for pristine (generated) versions of files. This enables:
//   - 3-way merges between base (previous pristine), current (user's version), and new (regenerated)
//   - Detection of user modifications via checksum comparison
//   - Efficient storage via Git's delta compression
//   - Conflict detection and resolution using standard Git conflict markers
//
// # Key Components
//
//   - [VirtualFile]: Represents a generated file held in memory before writing
//   - [MergeContext]: Contains all inputs for the merge operation
//   - [MergeResult]: Contains outputs including conflicts and no-op detection
//   - [Git]: Interface for Git operations (implemented by patches.GitAdapter)
//   - [ConflictsError]: Returned when merge conflicts require manual resolution
//
// # Merge Algorithm
//
// The [Merge] function performs a 4-step algorithm:
//
//  1. Immediate Blobbing: Write all generated content to Git object database.
//     Each file is hashed (SHA1) and stored as a blob, providing deduplication.
//
//  2. Determinism Check: Build a tree hash from all tracked files.
//     If tree hash matches previous generation, this is a no-op run (return early).
//
//  3. 3-Way Merge Loop: For each file, determine the appropriate action:
//     - New file: Write directly
//     - Clean file (disk matches last write): Overwrite with new version
//     - Dirty file (user modified): Perform 3-way merge
//     - Deleted file (user deleted): Respect deletion, update tracking only
//     - Moved file (user moved): Write to new location
//
//  4. Commit & Push: Create a Git commit linking the tree, push to remote.
//     This is handled by the caller (patches.Subsystem) which owns UUID generation.
//
// # 3-Way Text Merge
//
// The [merge3Way] function uses line-based diffing to merge changes:
//   - Convert files to line-based rune strings for efficient comparison
//   - Compute diffs from base to current (user changes) and base to new (generator changes)
//   - Walk both diff lists, merging non-overlapping changes automatically
//   - Generate conflict markers for overlapping changes
//
// Conflict format:
//
//	<<<<<<< Current (Your changes)
//	[user's version]
//	=======
//	[generated version]
//	>>>>>>> New (Generated by Speakeasy)
//
// # File Move Detection
//
// Users can move generated files to new locations. The system detects this via:
//   - Embedded @generated-id comments in file headers (e.g., "// @generated-id: a1b2c3d4e5f6")
//   - Scanning the output directory for files with these IDs
//   - Matching scanned IDs against computed IDs (based on original paths)
//
// When a move is detected, the generator writes to the new location, respecting
// the user's file organization.
//
// # No-Op Detection
//
// The system detects "no-op" runs where regeneration produces identical output.
// This is determined by comparing the tree hash of generated content against
// the previous pristine tree hash stored in the lockfile. When no-op is detected:
//   - No files are written
//   - No commit is created
//   - The lockfile is unchanged
//
// This prevents unnecessary churn in version control and CI pipelines.
//
// # Integration Flow
//
//  1. Generator renders templates, collecting [VirtualFile] entries in memory
//  2. Generator calls patches.Subsystem.PerformMerge() with virtual files
//  3. PerformMerge builds [MergeContext] and calls [Merge]
//  4. [Merge] performs the algorithm, writing merged files via FileSystem
//  5. PerformMerge creates commit, pushes to remote, updates lockfile
//  6. If conflicts exist, [ConflictsError] is returned after files are written
//
// # Lockfile State
//
// The gen.lock file tracks state for the merge system:
//
//	persistentEdits:
//	  generation_id: "uuid"           # Unique ID for this generation run
//	  pristine_commit_hash: "sha1"    # Git commit hash of pristine tree
//	  pristine_tree_hash: "sha1"      # Git tree hash for no-op detection
//	trackedFiles:
//	  path/to/file.go:
//	    id: "a1b2c3d4e5f6"           # Short ID embedded in file header
//	    last_write_checksum: "sha1:..." # Hash of file as last written
//	    pristine_git_object: "sha1"  # Git blob hash of pristine version
//	    moved_to: "new/path.go"      # Present if user moved the file
//	    deleted: true                # Present if user deleted the file
//
// # Error Handling
//
// The system is designed to be resilient:
//   - Network failures during push are soft failures (code still works locally)
//   - Missing Git objects trigger fetch attempts before falling back
//   - Scan failures for file IDs are logged but don't block generation
//   - Conflicts are written as markers, allowing manual resolution
//
// # References
//
// For implementation details, see:
//   - [Merge]: Main merge entry point
//   - [merge3Way]: Text merge algorithm
//   - [Git]: Git operations interface
//   - patches.Subsystem: Integration with Generator (in openapi-generation/internal/patches)
//   - patches.GitAdapter: Git interface implementation (in speakeasy/internal/patches)
package merge
