// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	examplealias "example.com/openapi-go-sdk"
	"example.com/openapi-go-sdk/internal/utils"
	"example.com/openapi-go-sdk/optionalnullable"
	"example.com/openapi-go-sdk/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"math/big"
	"os"
	"testing"
)

func TestSDK_TestEndpoint(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step testEndpoint.test referencing operation testEndpoint is missing required request body`, `workflow step testEndpoint.test referencing operation testEndpoint missing required path parameter testName`]")
}

func TestSDK_GetUserTestWithStatusCodeOnly(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getUser-testWithStatusCodeOnly")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetUser(ctx, "test123")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestSDK_GetUserTestWithResponseBody(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getUser-testWithResponseBody")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetUser(ctx, "test123")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.User)
	assert.Equal(t, &examplealias.User{
		ID:         "test123",
		Email:      "Trystan_Crooks@hotmail.com",
		FirstName:  examplealias.Pointer("Trystan"),
		LastName:   examplealias.Pointer("Crooks"),
		Age:        examplealias.Pointer[float64](32.0),
		PostalCode: examplealias.Pointer("94110"),
		Metadata: &examplealias.Metadata{
			Allergies: examplealias.Pointer("none"),
			AdditionalProperties: map[string]string{
				"color":      "red",
				"height":     "182",
				"weight":     "77",
				"is_smoking": "true",
			},
		},
	}, res.User)

}

func TestSDK_GetUserTestWithResponseBodyFields(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getUser-testWithResponseBodyFields")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetUser(ctx, "test123")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.User.Metadata.Allergies)
	assert.Equal(t, examplealias.Pointer("none"), res.User.Metadata.Allergies)
	assert.Equal(t, "red", res.User.Metadata.AdditionalProperties["color"])
	assert.Equal(t, "test123", res.User.AssociatedIds[1])

}

func TestSDK_GetFullyFlattenedRequestNamedExampleThatIsntMatchedAcrossDifferentExamples(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getFullyFlattenedRequest-namedExampleThatIsntMatchedAcrossDifferentExamples")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_URL", "")),
		examplealias.WithClient(testHTTPClient),
		examplealias.WithSecurity(examplealias.Security{
			Option6: &examplealias.SecurityOption6{
				ClientCredentials: utils.GetEnv("SPEAKEASY_CLIENT_CREDENTIALS", "value"),
			},
		}),
	)

	res, err := s.GetFullyFlattenedRequest(ctx, "en", examplealias.GetFullyFlattenedRequestRequestBody{
		Name: "<value>",
	}, nil)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestSDK_PostFile(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("postFile")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	postfiletest, fileErr := os.Open("../.speakeasy/testfiles/postfiletest.txt")
	require.NoError(t, fileErr)

	res, err := s.PostFile(ctx, examplealias.PostFileRequest{
		Upload: examplealias.File{
			FileName: "postfiletest.txt",
			Content:  postfiletest,
		},
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.File)
	assert.Equal(t, []byte("0x8fBAEeAAE7"), readBytes(res.File))

}

func TestSDK_GetPolymorphism(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getPolymorphism")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetPolymorphism(ctx)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Object)
	assert.Equal(t, &examplealias.GetPolymorphismResponseBody{
		OneOfWithUnionDescription: examplealias.Pointer(examplealias.NewOneOfWithUnionDescription(
			examplealias.ExhaustiveObject{
				Str:        "example",
				Bool:       true,
				Integer:    999999,
				Int32:      1,
				Num:        1.1,
				Float32:    7754.37,
				EnumProp:   examplealias.EnumFirst.ToPointer(),
				Date:       types.MustDateFromString("2022-04-06"),
				DateTime:   types.MustTimeFromString("2020-01-01T00:00:00Z"),
				Anything:   "<value>",
				BoolOpt:    examplealias.Pointer(true),
				IntOptNull: examplealias.Pointer[int64](999999),
				NumOptNull: examplealias.Pointer[float64](1.1),
				IntEnum:    examplealias.IntEnumThird.ToPointer(),
				Int32Enum:  examplealias.Int32EnumSixtyNine,
				Bigint:     big.NewInt(815677),
				BigintStr:  types.MustNewBigIntFromString("12345678901234567890"),
				DecimalStr: types.MustNewDecimalFromString("7753.11"),
				Obj: examplealias.SimpleObject{
					Str: "example",
				},
				Map: map[string]examplealias.SimpleObject{},
				Arr: []examplealias.SimpleObject{
					examplealias.SimpleObject{
						Str: "example",
					},
					examplealias.SimpleObject{
						Str: "example",
					},
					examplealias.SimpleObject{
						Str: "example",
					},
				},
				Any: examplealias.NewAny(
					"<value>",
				),
				Type:               examplealias.Pointer("0"),
				NullableIntEnum:    optionalnullable.From(examplealias.Pointer(examplealias.NullableIntEnumThird)),
				NullableStringEnum: examplealias.NullableStringEnumFirst.ToPointer(),
				Color:              examplealias.ColorGreen.ToPointer(),
				Icon:               examplealias.IconTick,
				HeroWidth:          examplealias.HeroWidthFourHundredAndEighty.ToPointer(),
			},
		)),
		OneOfWithFactoredOutProperties: examplealias.Pointer(examplealias.NewOneOfWithFactoredOutProperties(
			examplealias.OneOfWithFactoredOutPropertiesSimpleObject{
				Str:             "example",
				AnExtraProperty: examplealias.Pointer("example"),
			},
		)),
		SimpleAllOf: &examplealias.SimpleAllOf{
			Str:  examplealias.Pointer("example"),
			Bool: examplealias.Pointer(true),
		},
		AllOfWithFactoredOutProperties: &examplealias.AllOfWithFactoredOutProperties{
			AnOverridingProperty: examplealias.Pointer("example"),
			AnotherProperty:      examplealias.Pointer("example"),
			AnExtraProperty:      examplealias.Pointer("example"),
		},
	}, res.Object)

}

func TestSDK_GetUnionErrors(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getUnionErrors")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetUnionErrors(ctx, 12)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Object)
	assert.Equal(t, &examplealias.GetUnionErrorsResponseBody{
		Pages: []string{},
	}, res.Object)

}

func TestSDK_GetRequestBodyFlattenedAway(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getRequestBodyFlattenedAway")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithLoneQueryParam("<value>"),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetRequestBodyFlattenedAway(ctx)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestSDK_GetUserSuccess(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getUser-success")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetUser(ctx, "<id>")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.User)
	assert.Equal(t, &examplealias.User{
		ID:    "8ffac18c-7d88-4879-b057-e5f45b9ce7dg",
		Email: "Trystan_Crooks@hotmail.com",
	}, res.User)

}

func TestSDK_Chat(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step chat.test referencing operation chat is not currently supported`]")
}

func TestSDK_GetBinaryDefaultResponse(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getBinaryDefaultResponse")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetBinaryDefaultResponse(ctx)
	require.NoError(t, err)
	assert.NotContains(t, []any{200, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 421, 422, 423, 424, 425, 426, 428, 429, 431, 451, 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, 511}, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Bytes)
	assert.Equal(t, []byte("0xf58AcDF799"), readBytes(res.Bytes))

}

func TestSDK_UserLifecycle(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("user-lifecycle")

	authenticateOutputs := authenticate(t)
	assert.NotNil(t, authenticateOutputs)

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithSecurity(examplealias.Security{
			UserPassAuth: &examplealias.UserPassAuth{
				Username: "<USERNAME>",
				Password: "<PASSWORD>",
			},
		}),
		examplealias.WithClient(testHTTPClient),
	)

	createRes, err := s.CreateUser(ctx, examplealias.BaseUser{
		Email:      "Trystan_Crooks@hotmail.com",
		FirstName:  examplealias.Pointer("Trystan"),
		LastName:   examplealias.Pointer("Crooks"),
		Age:        examplealias.Pointer[float64](32.0),
		PostalCode: examplealias.Pointer("94110"),
		Metadata: &examplealias.Metadata{
			Allergies: examplealias.Pointer("none"),
			AdditionalProperties: map[string]string{
				"color":      "red",
				"height":     "182",
				"weight":     "77",
				"is_smoking": "true",
			},
		},
	})
	require.NoError(t, err)
	assert.Equal(t, 200, createRes.HTTPMeta.Response.StatusCode)
	assert.Equal(t, "Trystan_Crooks@hotmail.com", createRes.User.Email)
	assert.NotNil(t, createRes.User.PostalCode)
	assert.Equal(t, examplealias.Pointer("94110"), createRes.User.PostalCode)

	getRes, err := s.GetUser(ctx, createRes.User.ID)
	require.NoError(t, err)
	assert.Equal(t, 200, getRes.HTTPMeta.Response.StatusCode)
	assert.Equal(t, "Trystan_Crooks@hotmail.com", getRes.User.Email)
	assert.NotNil(t, getRes.User.FirstName)
	assert.Equal(t, examplealias.Pointer("Trystan"), getRes.User.FirstName)
	assert.NotNil(t, getRes.User.LastName)
	assert.Equal(t, examplealias.Pointer("Crooks"), getRes.User.LastName)
	assert.NotNil(t, getRes.User.Age)
	assert.Equal(t, examplealias.Pointer[float64](32.0), getRes.User.Age)
	assert.NotNil(t, getRes.User.PostalCode)
	assert.Equal(t, examplealias.Pointer("94110"), getRes.User.PostalCode)

	user := *getRes.User
	user.PostalCode = examplealias.Pointer("94107")
	user.Age = getRes.User.Age

	updateRes, err := s.UpdateUser(ctx, createRes.User.ID, user)
	require.NoError(t, err)
	assert.Equal(t, 200, updateRes.HTTPMeta.Response.StatusCode)
	assert.Equal(t, "Trystan_Crooks@hotmail.com", updateRes.User.Email)
	assert.NotNil(t, updateRes.User.FirstName)
	assert.Equal(t, examplealias.Pointer("Trystan"), updateRes.User.FirstName)
	assert.NotNil(t, updateRes.User.LastName)
	assert.Equal(t, examplealias.Pointer("Crooks"), updateRes.User.LastName)
	assert.NotNil(t, updateRes.User.Age)
	assert.Equal(t, examplealias.Pointer[float64](32.0), updateRes.User.Age)
	assert.NotNil(t, updateRes.User.PostalCode)
	assert.Equal(t, examplealias.Pointer("94107"), updateRes.User.PostalCode)

	updateAgainRes, err := s.UpdateUser(ctx, createRes.User.ID, examplealias.User{
		ID:         createRes.User.ID,
		Email:      updateRes.User.Email,
		FirstName:  updateRes.User.FirstName,
		LastName:   updateRes.User.LastName,
		Age:        examplealias.Pointer[float64](33.0),
		PostalCode: examplealias.Pointer("94110"),
		Metadata:   updateRes.User.Metadata,
	})
	require.NoError(t, err)
	assert.Equal(t, 200, updateAgainRes.HTTPMeta.Response.StatusCode)
	assert.Equal(t, "Trystan_Crooks@hotmail.com", updateAgainRes.User.Email)
	assert.NotNil(t, updateAgainRes.User.FirstName)
	assert.Equal(t, examplealias.Pointer("Trystan"), updateAgainRes.User.FirstName)
	assert.NotNil(t, updateAgainRes.User.LastName)
	assert.Equal(t, examplealias.Pointer("Crooks"), updateAgainRes.User.LastName)
	assert.NotNil(t, updateAgainRes.User.Age)
	assert.Equal(t, examplealias.Pointer[float64](33.0), updateAgainRes.User.Age)
	assert.NotNil(t, updateAgainRes.User.PostalCode)
	assert.Equal(t, examplealias.Pointer("94110"), updateAgainRes.User.PostalCode)

	deleteRes, err := s.DeleteUser(ctx, createRes.User.ID)
	require.NoError(t, err)
	assert.Equal(t, 200, deleteRes.HTTPMeta.Response.StatusCode)

}

func TestSDK_UpdateUser(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("updateUser")

	setupOutputs := userSetup(t)
	assert.NotNil(t, setupOutputs)

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	user := setupOutputs.User
	user.PostalCode = examplealias.Pointer("94107")
	user.Age = examplealias.Pointer[float64](33.0)

	res, err := s.UpdateUser(ctx, setupOutputs.User.ID, user)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.Equal(t, "Trystan_Crooks@hotmail.com", res.User.Email)
	assert.NotNil(t, res.User.FirstName)
	assert.Equal(t, examplealias.Pointer("Trystan"), res.User.FirstName)
	assert.NotNil(t, res.User.LastName)
	assert.Equal(t, examplealias.Pointer("Crooks"), res.User.LastName)
	assert.NotNil(t, res.User.Age)
	assert.Equal(t, examplealias.Pointer[float64](33.0), res.User.Age)
	assert.NotNil(t, res.User.PostalCode)
	assert.Equal(t, examplealias.Pointer("94107"), res.User.PostalCode)

	userTeardown(t, UserTeardownInputs{
		ID: setupOutputs.User.ID,
	})

}

func TestSDK_GetNestedIntegerString(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getNestedIntegerString")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetNestedIntegerString(ctx)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.TaskResponse)
	assert.Equal(t, &examplealias.TaskResponse{
		Task: examplealias.ReviewTask{
			ID:   "task-123",
			Name: "Review Task",
			Policy: examplealias.MCPPolicy{
				PolicyID: "policy-456",
				Steps: []examplealias.PolicyStep{
					examplealias.PolicyStep{
						StepID: "step-1",
						Approval: examplealias.ApprovalConfig{
							Approvers: []string{
								"user-1",
								"user-2",
							},
							Escalation: examplealias.Escalation{
								Enabled:    true,
								Expiration: 86400,
								FallbackApprovers: []string{
									"admin-1",
								},
							},
						},
					},
				},
			},
		},
	}, res.TaskResponse)

}

func TestSDK_TestEnumFormats(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("testEnumFormats")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.TestEnumFormats(ctx, examplealias.TestEnumFormatsRequest{
		StringArrayFormat:       examplealias.StringArrayFormatAwaitingReviewProcess,
		StringMapFormat:         examplealias.StringMapFormatModerateImportanceLevel,
		StringPartialMapFormat:  examplealias.StringPartialMapFormatInitialDraftVersion,
		IntegerMapFormat:        examplealias.IntegerMapFormatSuccessfulOperationComplete,
		IntegerPartialMapFormat: examplealias.IntegerPartialMapFormatPrimaryFirstOption,
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Object)
	assert.Equal(t, &examplealias.TestEnumFormatsResponseBody{
		Message: "Enum formats processed successfully",
	}, res.Object)

}

func TestSDK_GetEmptyObjectError(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getEmptyObjectError")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetEmptyObjectError(ctx)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Object)
	assert.Equal(t, &examplealias.GetEmptyObjectErrorResponseBody{
		Success: true,
	}, res.Object)

}

func TestSDK_ParenthesesInPathAllowed(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("parenthesesInPathAllowed")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.ParenthesesInPathAllowed(ctx, "<id>", examplealias.TemplateBracesTest{
		FieldWithBracesInExample: examplealias.Pointer("A string with {{ double braces }} and { single braces }\nand \\{\\{ escaped curlies \\}\\} and `backticks`.\nand \\`escaped backticks\\` and double slashes\\\\\nand 'single quotes' and \"double quotes\".\nand  \\'escaped single quotes\\' and \\\"escaped double quotes\\\".\n"),
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.TemplateBracesTest)
	assert.Equal(t, &examplealias.TemplateBracesTest{
		FieldWithBracesInDefault: examplealias.Pointer("A string with {{ double braces }} and { single braces }\nand \\{\\{ escaped curlies \\}\\} and `backticks`.\nand \\`escaped backticks\\` and double slashes\\\\\nand 'single quotes' and \"double quotes\".\nand  \\'escaped single quotes\\' and \\\"escaped double quotes\\\".\n"),
		FieldWithBracesInExample: examplealias.Pointer("A string with {{ double braces }} and { single braces }\nand \\{\\{ escaped curlies \\}\\} and `backticks`.\nand \\`escaped backticks\\` and double slashes\\\\\nand 'single quotes' and \"double quotes\".\nand  \\'escaped single quotes\\' and \\\"escaped double quotes\\\".\n"),
	}, res.TemplateBracesTest)

}

func TestSDK_GetErrorOnlyExample(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getErrorOnlyExample")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetErrorOnlyExample(ctx)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Object)
	assert.Equal(t, &examplealias.GetErrorOnlyExampleResponseBody{
		ID:   "<id>",
		Name: "<value>",
	}, res.Object)

}

func TestSDK_GetNamedPrimitiveUnion(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getNamedPrimitiveUnion")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetNamedPrimitiveUnion(ctx)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.SomeUnion)
	assert.Equal(t, examplealias.Pointer(examplealias.NewSomeUnion(
		true,
	)), res.SomeUnion)

}

func TestSDK_CreateUserRequestOnly(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("createUser-request-only")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.CreateUser(ctx, examplealias.BaseUser{
		Email: "request-only@example.com",
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.User)
	assert.Equal(t, &examplealias.User{
		ID:     "8ffac18c-7d88-4879-b057-e5f45b9ce7de",
		Email:  "Aglae92@gmail.com",
		Gender: examplealias.GenderOther.ToPointer(),
	}, res.User)

}

func TestSDK_CreateUserPairedExample(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("createUser-paired-example")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.CreateUser(ctx, examplealias.BaseUser{
		Email:     "paired@example.com",
		FirstName: examplealias.Pointer("John"),
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.User)
	assert.Equal(t, &examplealias.User{
		ID:        "user-paired",
		Email:     "paired@example.com",
		FirstName: examplealias.Pointer("John"),
	}, res.User)

}

func TestSDK_CreateUserResponseOnly(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("createUser-response-only")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.CreateUser(ctx, examplealias.BaseUser{
		ID:     examplealias.Pointer("8ffac18c-7d88-4879-b057-e5f45b9ce7de"),
		Email:  "Virginie47@gmail.com",
		Gender: examplealias.GenderOther.ToPointer(),
	})
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.User)
	assert.Equal(t, &examplealias.User{
		ID:    "user-response",
		Email: "response-only@example.com",
	}, res.User)

}

func TestSDK_GetDuplicateExportCollision(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getDuplicateExportCollision")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.GetDuplicateExportCollision(ctx)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Object)
	assert.Equal(t, &examplealias.GetDuplicateExportCollisionResponseBody{}, res.Object)

}

func TestSDK_CreateWithUnion(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("createWithUnion")

	s := examplealias.New(
		examplealias.WithServerURL(utils.GetEnv("TEST_SERVER_URL", "http://localhost:18080")),
		examplealias.WithClient(testHTTPClient),
	)

	res, err := s.CreateWithUnion(ctx, examplealias.ShapeRequest{
		Name: "<value>",
		Shape: examplealias.NewShape(
			examplealias.Rectangle{
				Type:   "rectangle",
				Width:  3125.73,
				Height: 922.51,
			},
		),
	}, nil)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)
	assert.NotNil(t, res.Object)
	assert.Equal(t, &examplealias.CreateWithUnionResponseBody{}, res.Object)

}

func TestSDK_PaginationOffsetNullable(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step paginationOffsetNullable.test referencing operation paginationOffsetNullable not found in document`]")
}

func TestSDK_RenderAsset(t *testing.T) {
	t.Skip("incomplete test found please make sure to address the following errors: [`workflow step renderAsset.test referencing operation renderAsset is not currently supported`]")
}
