/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.HasSecurity;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class MyApiKey implements HasSecurity {

    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=header,name=api_key")
    private String myApiKey;

    @JsonCreator
    public MyApiKey(@Nonnull String myApiKey) {
        this.myApiKey = Optional.ofNullable(myApiKey)
                .orElseThrow(() -> new IllegalArgumentException("myApiKey cannot be null"));
    }

    public String myApiKey() {
        return this.myApiKey;
    }

    public static Builder builder() {
        return new Builder();
    }

    public MyApiKey withMyApiKey(@Nonnull String myApiKey) {
        this.myApiKey = Utils.checkNotNull(myApiKey, "myApiKey");
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MyApiKey other = (MyApiKey) o;
        return Utils.enhancedDeepEquals(this.myApiKey, other.myApiKey);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(myApiKey);
    }

    @Override
    public String toString() {
        return Utils.toString(MyApiKey.class, "myApiKey", myApiKey);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String myApiKey;

        private Builder() {
            // force use of static builder() method
        }

        public Builder myApiKey(@Nonnull String myApiKey) {
            this.myApiKey = Utils.checkNotNull(myApiKey, "myApiKey");
            return this;
        }

        public MyApiKey build() {
            return new MyApiKey(myApiKey);
        }
    }
}
