/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;

/**
 * RecursiveFormFieldArray
 *
 * <p>An array field that contains nested form fields
 */
public class RecursiveFormFieldArray implements RecursiveFormField {

    @JsonProperty("type")
    private String type;

    @JsonProperty("label")
    private String label;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("required")
    private Boolean required;

    /**
     * A form field schema that can be recursive - the array type variant contains an array of
     * RecursiveFormField items.
     */
    @JsonProperty("item_type")
    private RecursiveFormField itemType;

    @JsonCreator
    public RecursiveFormFieldArray(
            @JsonProperty("label") @Nonnull String label,
            @JsonProperty("required") @Nullable Boolean required,
            @JsonProperty("item_type") @Nonnull RecursiveFormField itemType) {
        this.type = Builder._SINGLETON_VALUE_Type.value();
        this.label = Optional.ofNullable(label).orElseThrow(() -> new IllegalArgumentException("label cannot be null"));
        this.required = required;
        this.itemType = Optional.ofNullable(itemType)
                .orElseThrow(() -> new IllegalArgumentException("itemType cannot be null"));
    }

    public RecursiveFormFieldArray(@Nonnull String label, @Nonnull RecursiveFormField itemType) {
        this(label, null, itemType);
    }

    @Override
    public String type() {
        return Utils.discriminatorToString(type);
    }

    public String label() {
        return this.label;
    }

    public Optional<Boolean> required() {
        return Optional.ofNullable(this.required);
    }

    /**
     * A form field schema that can be recursive - the array type variant contains an array of
     * RecursiveFormField items.
     */
    public RecursiveFormField itemType() {
        return this.itemType;
    }

    public static Builder builder() {
        return new Builder();
    }

    public RecursiveFormFieldArray withLabel(@Nonnull String label) {
        this.label = Utils.checkNotNull(label, "label");
        return this;
    }

    public RecursiveFormFieldArray withRequired(@Nullable Boolean required) {
        this.required = required;
        return this;
    }

    /**
     * A form field schema that can be recursive - the array type variant contains an array of
     * RecursiveFormField items.
     */
    public RecursiveFormFieldArray withItemType(@Nonnull RecursiveFormField itemType) {
        this.itemType = Utils.checkNotNull(itemType, "itemType");
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RecursiveFormFieldArray other = (RecursiveFormFieldArray) o;
        return Utils.enhancedDeepEquals(this.type, other.type)
                && Utils.enhancedDeepEquals(this.label, other.label)
                && Utils.enhancedDeepEquals(this.required, other.required)
                && Utils.enhancedDeepEquals(this.itemType, other.itemType);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(type, label, required, itemType);
    }

    @Override
    public String toString() {
        return Utils.toString(
                RecursiveFormFieldArray.class,
                "type",
                type,
                "label",
                label,
                "required",
                required,
                "itemType",
                itemType);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private String label;

        private Boolean required;

        private RecursiveFormField itemType;

        private Builder() {
            // force use of static builder() method
        }

        public Builder label(@Nonnull String label) {
            this.label = Utils.checkNotNull(label, "label");
            return this;
        }

        public Builder required(@Nullable Boolean required) {
            this.required = required;
            return this;
        }

        /**
         * A form field schema that can be recursive - the array type variant contains an array of
         * RecursiveFormField items.
         */
        public Builder itemType(@Nonnull RecursiveFormField itemType) {
            this.itemType = Utils.checkNotNull(itemType, "itemType");
            return this;
        }

        public RecursiveFormFieldArray build() {
            return new RecursiveFormFieldArray(label, required, itemType);
        }

        private static final LazySingletonValue<String> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>("type", "\"array\"", new TypeReference<String>() {});
    }
}
