/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.shared;

import java.lang.IllegalArgumentException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import org.openapis.openapi.utils.GenericTypeIdResolver;

public class StepTypeIdResolver extends GenericTypeIdResolver<Step> {

    public StepTypeIdResolver() {
        super(UnknownStep.class);
        initializeTypeMap();
    }

    private void initializeTypeMap() {
        registerType("note", AssetNoteStep.class);
        registerType("output", AssetOutputStep.class);
    }

    @Override
    public String idFromValue(Object value) {
        if (value == null) {
            return null;
        }

        // Handle known types by checking if they implement the discriminator method
        if (value instanceof Step) {
            Step discriminated = (Step) value;
            return discriminated.type();
        }

        throw new IllegalArgumentException(
                "Unknown value type: " + value.getClass().getName());
    }

    @Override
    public String getDescForKnownTypeIds() {
        return "Step type resolver";
    }
}
