/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class Test2Request {
    /**
     * A simple object that uses all our supported primitive types and enums and has optional properties.
     *
     * <p><a href="https://speakeasy.com">A link to the external docs.</a>
     */
    @JsonProperty("obj")
    private ExhaustiveObject obj;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private Type type;

    @JsonCreator
    public Test2Request(@JsonProperty("obj") @Nonnull ExhaustiveObject obj, @JsonProperty("type") @Nullable Type type) {
        this.obj = Optional.ofNullable(obj).orElseThrow(() -> new IllegalArgumentException("obj cannot be null"));
        this.type = type;
    }

    public Test2Request(@Nonnull ExhaustiveObject obj) {
        this(obj, null);
    }

    /**
     * A simple object that uses all our supported primitive types and enums and has optional properties.
     *
     * <p><a href="https://speakeasy.com">A link to the external docs.</a>
     */
    public ExhaustiveObject obj() {
        return this.obj;
    }

    public Optional<Type> type() {
        return Optional.ofNullable(this.type);
    }

    public static Builder builder() {
        return new Builder();
    }

    /**
     * A simple object that uses all our supported primitive types and enums and has optional properties.
     *
     * <p><a href="https://speakeasy.com">A link to the external docs.</a>
     */
    public Test2Request withObj(@Nonnull ExhaustiveObject obj) {
        this.obj = Utils.checkNotNull(obj, "obj");
        return this;
    }

    public Test2Request withType(@Nullable Type type) {
        this.type = type;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Test2Request other = (Test2Request) o;
        return Utils.enhancedDeepEquals(this.obj, other.obj) && Utils.enhancedDeepEquals(this.type, other.type);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(obj, type);
    }

    @Override
    public String toString() {
        return Utils.toString(Test2Request.class, "obj", obj, "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private ExhaustiveObject obj;

        private Type type;

        private Builder() {
            // force use of static builder() method
        }

        /**
         * A simple object that uses all our supported primitive types and enums and has optional properties.
         *
         * <p><a href="https://speakeasy.com">A link to the external docs.</a>
         */
        public Builder obj(@Nonnull ExhaustiveObject obj) {
            this.obj = Utils.checkNotNull(obj, "obj");
            return this;
        }

        public Builder type(@Nullable Type type) {
            this.type = type;
            return this;
        }

        public Test2Request build() {
            return new Test2Request(obj, type);
        }
    }
}
