/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.shared;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.databind.annotation.JsonTypeIdResolver;
import java.lang.String;

/**
 * VariantRecord
 *
 * <p>A discriminated union with $-prefixed keys and x-speakeasy-discriminator overrides
 */
@JsonTypeInfo(
        use = Id.CUSTOM,
        property = "type",
        include = As.EXISTING_PROPERTY,
        visible = true,
        defaultImpl = UnknownVariantRecord.class)
@JsonTypeIdResolver(VariantRecordTypeIdResolver.class)
public interface VariantRecord {

    String type();
}
