
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.OpenAPI
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System;
    using UnityEngine;
    
    /// <summary>
    /// Escalation configuration with string-encoded integer expiration
    /// </summary>
    [Serializable]
    public class Escalation
    {

        [SerializeField]
        [JsonProperty("enabled")]
        public bool Enabled { get; set; } = default!;

        /// <summary>
        /// Expiration in seconds, encoded as a string in the API response
        /// </summary>
        [SerializeField]
        [JsonProperty("expiration")]
        public string Expiration { get; set; } = default!;

        [SerializeField]
        [JsonProperty("fallbackApprovers")]
        public List<string> FallbackApprovers { get; set; } = default!;
    }
}