
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.OpenAPI
{
    using Speakeasy.OpenAPI.Utils;
    using System;
    using UnityEngine;
    
    [Serializable]
    public class ListTest1Request
    {

        [SerializeField]
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=page")]
        public long Page { get; set; } = default!;

        [SerializeField]
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=queryParam1")]
        public string? QueryParam1 { get; set; }

        /// <summary>
        /// An <a href="https://enum.com">enum</a> &quot;query parameter&quot;<br/>
        /// 
        /// <remarks>
        /// that is not easily described in a single line.<br/>
        /// <br/>
        /// **Available Values:**<br/>
        /// | Value | Description |<br/>
        /// |-------|-------------|<br/>
        /// | 0     | No data     |<br/>
        /// | 1     | Partial     |<br/>
        /// | 2     | Complete    |
        /// </remarks>
        /// </summary>
        [SerializeField]
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=queryParam2")]
        public QueryParam2 QueryParam2 { get; set; } = default!;

        [SerializeField]
        [SpeakeasyMetadata("header:style=simple,explode=false,name=headerParam1")]
        public string HeaderParam1 { get; set; } = default!;
    }
}