// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetUnionErrorsRequest struct {
	Page int64 `queryParam:"style=form,explode=true,name=page"`
}

func (o *GetUnionErrorsRequest) GetPage() int64 {
	if o == nil {
		return 0
	}
	return o.Page
}

// GetUnionErrorsResponseBody - OK
type GetUnionErrorsResponseBody struct {
	Pages []string `json:"pages"`
}

func (o *GetUnionErrorsResponseBody) GetPages() []string {
	if o == nil {
		return []string{}
	}
	return o.Pages
}

type GetUnionErrorsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *GetUnionErrorsResponseBody

	Next func() (*GetUnionErrorsResponse, error)
}

func (o *GetUnionErrorsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetUnionErrorsResponse) GetObject() *GetUnionErrorsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
