// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/internal/sdk/models/components"
)

type URLValidationStressTestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (u *URLValidationStressTestResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}
