//@ts-ignore
const supportedFeatures = {
  core: "3.31.6",
  flattening: "2.82.1",
  globalSecurity: "2.82.16",
  methodSecurity: "2.82.8",
  globalServerURLs: "2.83.1",
  methodServerURLs: "2.82.2",
  globals: "2.82.2",
  enums: "2.83.0",
  openEnums: "0.1.3",
  allowReserved: "0.2.0",
  openDiscriminatedUnions: "0.1.0",
  serverIDs: "2.81.2",
  nameOverrides: "2.81.4",
  includes: "2.81.1",
  docs: "0.13.3",
  examples: "2.82.6",
  groups: "2.81.3",
  deprecations: "2.81.1",
  retries: "2.83.2",
  defaultEnabledRetries: "0.1.0",
  pagination: "2.83.2",
  inputOutputModels: "2.82.1",
  ignores: "2.81.1",
  typeOverrides: "2.81.1",
  errors: "2.86.3",
  acceptHeaders: "2.81.2",
  multiLevelTagging: "2.87.3",
  devContainers: "2.90.1",
  bigint: "0.0.3",
  decimal: "0.1.2",
  unions: "2.86.5",
  sliceUnions: "0.0.1",
  downloadStreams: "0.1.1",
  additionalProperties: "0.1.4",
  constsAndDefaults: "0.1.14",
  serverEvents: "0.2.4",
  serverEventsSentinels: "0.1.0",
  tests: "0.17.7",
  urlBasedPagination: "2.83.2",
  responseFormat: "0.3.0",
  oauth2ClientCredentials: "1.1.6",
  oauth2Password: "0.1.4",
  webhooks: "1.5.1",
  webhookHandlers: "0.1.0",
  callbacks: "1.0.1",
  hiddenGlobals: "0.1.0",
  errorUnions: "0.1.1",
  stringNumberFormats: "0.2.0",
  methodArguments: "0.1.2",
  sdkHooks: "0.4.0",
  additionalDependencies: "0.1.0",
  nullables: "0.1.1",
  globalSecurityFlattening: "0.1.1",
  globalSecurityCallbacks: "0.1.0",
  operationTimeout: "0.2.1",
  deepObjectParams: "0.1.0",
  envVarSecurityUsage: "0.1.2",
  envVarGlobals: "0.1.1",
  customSecuritySchemes: "0.1.2",
  uploadStreams: "0.1.1",
  mockServer: "0.1.4",
  enumUnions: "0.1.0",
  reactQueryHooks: "0.3.0",
  customCodeRegions: "0.1.1",
  mcpServer: "0.9.4",
  jsonlResponses: "0.2.1",
  examplesDirectory: "0.2.1",
  modelNamespaces: "0.1.1",
  methodSignatures: "0.1.2",
  publicExports: "0.1.4",
};

//@ts-ignore
const implementedReadmeSections = [
  "installation",
  "usage",
  "operations",
  "dev-containers",
  "global-parameters",
  "errors",
  "eventstream",
  "http-client",
  "pagination",
  "retries",
  "security",
  "server",
  "file-upload",
];

//@ts-ignore
function isFeatureSupported(feature: string): boolean {
  return feature in supportedFeatures;
}

//@ts-ignore
function isFeatureEnabled(
  feature: string,
  config: Record<string, any>,
): boolean {
  switch (feature) {
    case "envVarSecurityUsage":
      return config["EnvVarPrefix"] !== undefined;
    default:
      return false;
  }
}

//@ts-ignore
function allSupportedFeatures(): string[] {
  const allFeatures = Object.keys(supportedFeatures);
  return allFeatures.filter((feature) => !isFeatureIgnored(feature));
}

//@ts-ignore
function isFeatureIgnored(feature: string): boolean {
  return [
    "disallowCircularRefs",
    "tagBasedOrdering",
    "sets",
    "getRequestBodies",
  ].includes(feature);
}

//@ts-ignore
function isReadmeSectionImplemented(id: string): boolean {
  return implementedReadmeSections.includes(id);
}

//@ts-ignore
function isReadmeSectionIgnored(id: string): boolean {
  return false;
}

//@ts-ignore
function getStaticallyUsedFeatures(): string[] {
  return ["sdkHooks", "additionalDependencies", "globalSecurityCallbacks"];
}

//@ts-ignore
function getFeatureVersion(feature: string): string {
  return supportedFeatures[feature];
}

//@ts-ignore
function isTestSkipped(test: string): boolean {
  return [
    "event-stream-timeout-still-bounds-slow-stream",
    "event-stream-with-timeout-streams-to-completion",
    "smart-union-nullable-collection-item",
    "smart-union-wrapped-complex-fields",
    "servers-select-global-server-by-name-valid-using-builder",
    "auth-global-security-flattening-callback",
    "method-trace", // TypeError: 'TRACE' HTTP method is unsupported.
    "servers-server-with-invalid-protocol-template",
    "servers-server-with-protocol-template",
    "unions-extra-json-properties",
    "unions-nested-enums-form",
    "unions-nested-enums-multipart",
    "unions-optional-union-map",
    "unions-mixed-union-types",
    "union-enum-nested-in-array-in-union",
    "flattening-component-body-and-param-no-conflict-flatten-requests",
    "flattening-component-body-and-param-conflict-flatten-requests",
    "flattening-inline-body-and-param-conflict-flatten-requests",
    "flattening-inline-body-and-param-no-conflict-flatten-requests",
    "flattening-conflicting-params-flatten-requests",
    "flattening-required-body-all-optional-flatten-requests",
    "pagination-cursor-response-envelope",
    "pagination-cursor-non-numeric-with-limit",
    "pagination-limit-offset-page-params-const",
    "errors-additional-properties",
    "x-ndjson-stream-data-async-envelope-http-responses",
    "x-ndjson-stream-data-async-chunks-envelope-http-responses",
    "jsonl-stream-data-async-envelope-http-responses",
    "retries-retry-connection-errors-reject",
    "retries-retry-connection-errors-reset",
    "servers-select-global-server-by-id-default-using-builder",
    "servers-select-global-server-by-name-broken-using-builder",
    "servers-select-global-server-by-name-default-using-builder",
    "servers-select-global-server-by-name-with-templates-broken-using-builder",
    "servers-select-global-server-by-name-with-templates-defaults-using-builder",
    "servers-select-global-server-by-name-with-templates-valid-using-builder",
    "servers-select-global-server-by-id-valid-using-builder",
    "servers-select-global-server-by-id-invalid-using-builder",
    "servers-select-global-server-by-id-broken-using-builder",
    "custom-code-region-model-method-with-imports",
    "parameters-open-enum",
    "parameters-form-query-params-unions",
    "parameters-ordering-body-first",
    "parameters-ordering-parameters-first",
    "parameters-ordering-with-legacy-flattening-order",
    "parameters-ordering-using-optional-request-body-body-first",
    "parameters-ordering-using-optional-request-body-parameters-first",
    "parameters-ordering-using-optional-request-body-with-legacy-flattening-order",
    "cancellation-token-cancelled-before-request",
    "cancellation-token-cancelled-during-request",
    "cancellation-token-cancelled-inside-hook",
    "cancellation-token-no-cancellation",
    "customclient-request-parameters-retained-legacy",
    "unions-strongly-typed-nullable-one-of-post",
    "unions-one-of-boolean-and-string-enum-with-response-boolean",
    "unions-one-of-boolean-and-string-enum-with-response-enum",
    "object-with-optional-false-nullable-false-field-absent",
    "object-with-optional-false-nullable-false-field-null",
    "object-with-optional-false-nullable-false-full",
    "object-with-optional-false-nullable-true-field-null",
    "object-with-optional-false-nullable-true-full",
    "object-with-optional-nullable-field-absent",
    "object-with-optional-nullable-field-null",
    "object-with-optional-nullable-full",
    "object-with-optional-true-nullable-false-field-absent",
    "object-with-optional-true-nullable-false-field-null",
    "object-with-optional-true-nullable-false-full",
    "object-with-optional-false-nullable-true-field-absent",
    "transform-jq-request-response",
    "polling-delay-seconds-override",
    "polling-delay-seconds",
    "polling-failure-criteria-response-body-nested",
    "polling-failure-criteria-response-body-optional",
    "polling-failure-criteria-response-body-regex",
    "polling-failure-criteria-response-body",
    "polling-failure-criteria-status-code-regex",
    "polling-failure-criteria-status-code",
    "polling-interval-seconds-override",
    "polling-interval-seconds",
    "polling-limit-count-override",
    "polling-limit-count",
    "polling-success-criteria-response-body-nested",
    "polling-success-criteria-response-body-optional",
    "polling-success-criteria-response-body-regex",
    "polling-success-criteria-response-body",
    "polling-success-criteria-status-code-error-known",
    "polling-success-criteria-status-code-error-regex",
    "polling-success-criteria-status-code-error-unknown",
    "polling-success-criteria-status-code",
    "polling-success-criteria-status-code-regex",
    "union-enum-array-deserialization",
    "unions-discriminated-multiple-memberships",
    "timeout-ms-override-allows-completion",
    "timeout-ms-override-is-respected",
    "request-bodies-complex-number-types-optional-unpopulated",
    "request-bodies-complex-number-types-required-missing",
    "flattening-nullable-body-with-required-param-ordering",
    "pagination-limit-offset-nullable",
    "auth-global-security-flattening-env-var-fallback",
    "unions-strongly-typed-one-of-discriminated-post",
    "raw-response-helpers-strip-internal-header",
    "unions-typed-object-one-of-post-body-less-throws",
    "request-bodies-put-multipart-file-bytesio",
    "request-bodies-put-multipart-file-handle",
    "request-bodies-put-multipart-file-stringio",
    "collections-map-input-accepts-non-dict-mapping",
    "collections-parameter-annotations-advertise-iterables",
    "collections-parameters-accept-iterables",
    "collections-parameters-accept-iterables-direct",
    "errors-error-body-validation-disabled",
    "errors-error-body-validation-enabled",
    "errors-response-body-validation-disabled",
    "errors-custom-error-inheritance",
    "errors-response-body-validation-enabled",
    "errors-optional-nullable-error-message",
    "errors-optional-nullable-error-message-nested",
    "retries-status-codes-override",
    "retries-status-codes-override-global",
    "retries-status-codes-override-default",
    "errors-response-body-validation-lenient",
    "hooks-access-operation-metadata",
    "request-bodies-duration-format",
    "request-bodies-uuid-format",
    "smart-union-nested-union-vs-nested-union",
    "request-bodies-put-multipart-optional-nullable",
    "request-bodies-post-form-optional-nullable",
    "request-bodies-post-json-optional-nullable",
    "smart-union-nullable-union-nullable-fields",
    "request-bodies-post-form-optional-nullable-json-shared",
    "request-bodies-put-multipart-optional-nullable-json-shared",
    "request-bodies-post-json-optional-nullable-body-and-param",
    "pagination-limit-offset-page-body-optional-nullable",
    "pagination-cursor-nullable-results",
    "retries-binary-request-body",
    "retries-header-http-date-beyond-max-interval",
    "retries-header-rate-limit-reset",
    "errors-error-body-validation-lenient",
    "errors-response-body-validation-lenient-non-json",
    "errors-response-body-validation-lenient-union-variant",
    "event-stream-malformed-frame-lenient",
    "event-stream-malformed-frame-strict",
    "optional-nullable-array-params-null-and-unset",
    "optional-nullable-array-params-set",
    "optional-nullable-deep-object-param",
    "optional-nullable-special-header-params",
    "optional-nullable-urlencoded-body",
    "agent-mode-does-not-leak-between-invocations",
    "catalog-lists-values",
    "catalog-rejects-positional-argument",
    "catalog-structured-output",
    "cli-exit-code-bare-intent",
    "cli-exit-code-connection-and-agent-block",
    "cli-exit-code-mapping-tables",
    "cli-exit-code-reason-first",
    "cli-exit-code-root-unknown-message",
    "cli-exit-code-single-envelope",
    "cli-exit-code-success-and-discovery",
    "cli-exit-codes-rendering-modes",
    "client-credentials-dry-run-token-and-api",
    "clierrors-agent-mode-explicitly-disabled",
    "clierrors-agent-mode-from-environment",
    "clierrors-agent-mode-matrix",
    "clierrors-api-error-not-double-wrapped",
    "clierrors-declared-hints-fire",
    "clierrors-flag-values-not-rendering-flags",
    "clierrors-invalid-values-do-not-stop-preparse",
    "clierrors-json-output-envelope",
    "clierrors-plain-mode-classified",
    "clierrors-typed-reasons",
    "error-taxonomy-declared-rules-and-ordering",
    "error-taxonomy-every-closed-type-has-a-hint",
    "error-taxonomy-fallback-message-omits-raw-body",
    "error-taxonomy-hint-precedence-and-dedupe",
    "error-taxonomy-jq-uses-structured-envelope",
    "error-taxonomy-odd-bodies-use-fallback-envelope",
    "error-taxonomy-odd-reflection-fields-do-not-panic",
    "error-taxonomy-origin-semantics",
    "error-taxonomy-pretty-http-status-without-reason",
    "error-taxonomy-pretty-json-agent-parity",
    "error-taxonomy-pretty-residual-details",
    "error-taxonomy-reserved-keys-and-rendered-classification",
    "event-stream-connection-refused-stays-connection-error",
    "event-stream-decode-failure-is-protocol-error",
    "event-stream-decode-failure-without-json-error-type",
    "event-stream-error-event-agent-mode",
    "event-stream-error-event-agent-mode-fallback",
    "event-stream-error-event-exits-non-zero",
    "event-stream-error-event-pretty",
    "event-stream-numbers-keep-precision",
    "event-stream-server-error-mentioning-decode-is-not-protocol-error",
    "event-stream-timeout-still-bounds-slow-stream",
    "event-stream-undiscriminated-error-shaped-variant-is-data",
    "event-stream-union-events-render-wire-shape",
    "intent-dispatch-resolves-stdin-once",
    "intent-dispatch-select-matrix",
    "intent-interactive-piped-body-skips-prompts",
    "intent-route-dispatch-agent-envelope",
    "intent-route-dispatch-bare-help",
    "intent-route-dispatch-body-evidence",
    "intent-route-dispatch-conflicting-evidence",
    "intent-route-dispatch-default-required",
    "intent-route-dispatch-flag-paths",
    "intent-route-dispatch-help-usage",
    "intent-route-dispatch-interactive-plan",
    "intent-route-dispatch-override-once",
    "intents-both-body-surfaces-merged",
    "intents-discriminated-partial-body",
    "intents-foreign-selector-agent-envelope",
    "intents-foreign-selector-usage-error",
    "intents-non-object-body-falls-through",
    "intents-partial-body-keeps-presets",
    "intents-partial-body-user-keys-win",
    "intents-preset-from-args",
    "intents-preset-merge-matrix",
    "intents-undeclared-nested-group-order",
    "pre-request-connection-classifier-typed-table",
    "pre-request-discriminated-root-union-messages",
    "pre-request-dry-run-unresolvable-host",
    "pre-request-generated-required-union-paths-and-optionality",
    "pre-request-generated-required-union-positive-echoes",
    "pre-request-real-connection-failures",
    "pre-request-silent-stdin-times-out-on-root-union",
    "pre-request-validation-envelope-matrix",
    "request-bodies-complex-number-types-bigint-overflow",
    "request-shape-body-agent-variant",
    "request-shape-body-and-whole-body-flag-rejected",
    "request-shape-body-both-selectors-rejected",
    "request-shape-body-default-selector-merges",
    "request-shape-body-null-optional-key-allowed",
    "request-shape-body-typo-key-rejected",
    "request-shape-expanded-body-typo-key-lenient-warning",
    "request-shape-expanded-body-typo-key-rejected",
    "request-shape-intent-bare-usage",
    "request-shape-intent-empty-stdin-usage",
    "request-shape-intent-flag-and-body-conflict",
    "request-shape-intent-flag-merged-into-body",
    "request-shape-intent-positional-and-body-conflict",
    "request-shape-intent-positional-merged-into-body",
    "request-shape-intent-positional-merged-into-whole-body-flag",
    "request-shape-intent-stdin-runs-request",
    "request-shape-intent-stdin-typo-key-rejected",
    "request-shape-intent-stdin-with-positional",
    "request-shape-intent-synthesized-body",
    "request-shape-intent-zero-value-flag-merged",
    "request-shape-nested-union-agent-selector-no-default",
    "request-shape-nested-union-body-default-selector-merges",
    "request-shape-nested-union-own-flag-default-selector-merges",
    "request-shape-nested-union-stdin-default-selector-merges",
    "request-shape-open-schema-keeps-unknown-keys",
    "request-shape-stdin-typo-key-rejected",
    "request-shape-whole-body-flag-typo-key-rejected",
    "request-shape-whole-body-flag-wins-over-stdin",
    "security-ranking-both-flags",
    "security-ranking-env-only",
    "security-ranking-env-tie",
    "security-ranking-flag-beats-env",
    "security-ranking-operation-restriction",
    "security-ranking-pick-matrix",
    "security-ranking-source-rank",
    "event-stream-with-operation-timeout-streams-to-completion",
    "jsonl-stream-timeout-still-bounds-slow-stream",
    "jsonl-stream-with-timeout-streams-to-completion",
    "optional-nullable-object-property-params",
  ].includes(test);
}

//@ts-ignore
function getAutoGeneratedHeader(
  generatedId: string,
  config: Record<string, any>,
): string {
  let header = `/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.`;
  if (generatedId) {
    header += `\n * @generated-id: ${generatedId}`;
  }
  if (config.GeneratedLicense === "agpl") {
    header +=
      "\n * Generated under the AGPL-3.0-only license." +
      "\n * SPDX-License-Identifier: AGPL-3.0-only";
  }
  header += `\n */\n\n`;
  return header;
}

// @ts-ignore
function collectGlobalsAndServersModels(): boolean {
  return true;
}
