/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as foo from "../foo/index.js";
import { namespaceTestsSingleFooCreateSingleNamespaceFooPet } from "../funcs/namespaceTestsSingleFooCreateSingleNamespaceFooPet.js";
import { namespaceTestsSingleFooGetSingleNamespaceFooPet } from "../funcs/namespaceTestsSingleFooGetSingleNamespaceFooPet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { APIPromise, unwrapAsAPIPromise } from "../types/async.js";

export class SingleFoo extends ClientSDK {
  /**
   * Get Single Namespace Foo Pet
   *
   * @remarks
   * This endpoint tests using a single component from the foo namespace.
   * No import aliasing should be needed since there's no conflict within this group.
   */
  getSingleNamespaceFooPet(
    options?: Omit<RequestOptions, "extraBody">,
  ): APIPromise<foo.Pet> {
    return unwrapAsAPIPromise(namespaceTestsSingleFooGetSingleNamespaceFooPet(
      this,
      options,
    ));
  }

  /**
   * Create Single Namespace Foo Pet
   *
   * @remarks
   * This endpoint tests creating a component in the foo namespace.
   * No import aliasing should be needed since there's no conflict within this group.
   */
  createSingleNamespaceFooPet(
    request: foo.Pet,
    options?: RequestOptions,
  ): APIPromise<foo.Pet> {
    return unwrapAsAPIPromise(
      namespaceTestsSingleFooCreateSingleNamespaceFooPet(
        this,
        request,
        options,
      ),
    );
  }
}
