// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package foo

import (
	"encoding/json"
	"errors"
	"example.com/openapi-go-sdk/internal/utils"
	"fmt"
)

type AnimalType string

const (
	AnimalTypeDog     AnimalType = "dog"
	AnimalTypeCat     AnimalType = "cat"
	AnimalTypeUnknown AnimalType = "UNKNOWN"
)

// Animal - A discriminated union of animal types in the foo namespace
type Animal struct {
	Dog        *Dog            `queryParam:"inline" union:"member"`
	Cat        *Cat            `queryParam:"inline" union:"member"`
	UnknownRaw json.RawMessage `json:"-" union:"unknown"`

	Type AnimalType
}

type AnimalMember interface {
	Dog | Cat
}

func NewAnimal[T AnimalMember](val T) Animal {
	switch v := any(val).(type) {
	case Dog:
		typ := AnimalTypeDog
		typStr := DogAnimalType(typ)
		v.AnimalType = typStr
		return Animal{
			Dog:  &v,
			Type: typ,
		}
	case Cat:
		typ := AnimalTypeCat
		typStr := CatAnimalType(typ)
		v.AnimalType = typStr
		return Animal{
			Cat:  &v,
			Type: typ,
		}
	}
	panic(fmt.Sprintf("unreachable: %T is not a member of union Animal", val))
}
func NewAnimalUnknown(raw json.RawMessage) Animal {
	return Animal{
		UnknownRaw: raw,
		Type:       AnimalTypeUnknown,
	}
}

func (u Animal) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Animal) IsUnknown() bool {
	return u.Type == AnimalTypeUnknown
}

func (u *Animal) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = Animal{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	type discriminator struct {
		AnimalType string `json:"animalType"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnimalTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnimalTypeUnknown
		return nil
	}

	switch dis.AnimalType {
	case "dog":
		dog := new(Dog)
		if err := utils.UnmarshalJSON(data, &dog, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AnimalType == dog) type Dog within Animal: %w", string(data), err)
		}

		u.Dog = dog
		u.Type = AnimalTypeDog
		return nil
	case "cat":
		cat := new(Cat)
		if err := utils.UnmarshalJSON(data, &cat, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (AnimalType == cat) type Cat within Animal: %w", string(data), err)
		}

		u.Cat = cat
		u.Type = AnimalTypeCat
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AnimalTypeUnknown
		return nil
	}

}

func (u Animal) MarshalJSON() ([]byte, error) {
	if u.Dog != nil {
		return utils.MarshalJSON(u.Dog, "", true)
	}

	if u.Cat != nil {
		return utils.MarshalJSON(u.Cat, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Animal: all fields are null")
}
