// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/internal/utils"
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/models/shared"
	"net/http"
)

type GetUnionErrorsRequest struct {
	Page int64 `queryParam:"style=form,explode=true,name=page"`
}

func (g *GetUnionErrorsRequest) GetPage() int64 {
	if g == nil {
		return 0
	}
	return g.Page
}

type GetUnionErrorsClientErrorResponseBodyType string

const (
	GetUnionErrorsClientErrorResponseBodyTypeTag1 GetUnionErrorsClientErrorResponseBodyType = "tag1"
	GetUnionErrorsClientErrorResponseBodyTypeTag2 GetUnionErrorsClientErrorResponseBodyType = "tag2"
)

// GetUnionErrorsClientErrorResponseBody - Something went wrong
type GetUnionErrorsClientErrorResponseBody struct {
	TaggedError1 *shared.TaggedError1 `queryParam:"inline" union:"member"`
	TaggedError2 *shared.TaggedError2 `queryParam:"inline" union:"member"`

	Type GetUnionErrorsClientErrorResponseBodyType
}

func CreateGetUnionErrorsClientErrorResponseBodyTag1(tag1 shared.TaggedError1) GetUnionErrorsClientErrorResponseBody {
	typ := GetUnionErrorsClientErrorResponseBodyTypeTag1

	typStr := shared.Tag(typ)
	tag1.Tag = typStr

	return GetUnionErrorsClientErrorResponseBody{
		TaggedError1: &tag1,
		Type:         typ,
	}
}

func CreateGetUnionErrorsClientErrorResponseBodyTag2(tag2 shared.TaggedError2) GetUnionErrorsClientErrorResponseBody {
	typ := GetUnionErrorsClientErrorResponseBodyTypeTag2

	return GetUnionErrorsClientErrorResponseBody{
		TaggedError2: &tag2,
		Type:         typ,
	}
}

func (u *GetUnionErrorsClientErrorResponseBody) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Tag string `json:"tag"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Tag {
	case "tag1":
		taggedError1 := new(shared.TaggedError1)
		if err := utils.UnmarshalJSON(data, &taggedError1, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Tag == tag1) type shared.TaggedError1 within GetUnionErrorsClientErrorResponseBody: %w", string(data), err)
		}

		u.TaggedError1 = taggedError1
		u.Type = GetUnionErrorsClientErrorResponseBodyTypeTag1
		return nil
	case "tag2":
		taggedError2 := new(shared.TaggedError2)
		if err := utils.UnmarshalJSON(data, &taggedError2, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Tag == tag2) type shared.TaggedError2 within GetUnionErrorsClientErrorResponseBody: %w", string(data), err)
		}

		u.TaggedError2 = taggedError2
		u.Type = GetUnionErrorsClientErrorResponseBodyTypeTag2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetUnionErrorsClientErrorResponseBody", string(data))
}

func (u GetUnionErrorsClientErrorResponseBody) MarshalJSON() ([]byte, error) {
	if u.TaggedError1 != nil {
		return utils.MarshalJSON(u.TaggedError1, "", true)
	}

	if u.TaggedError2 != nil {
		return utils.MarshalJSON(u.TaggedError2, "", true)
	}

	return nil, errors.New("could not marshal union type GetUnionErrorsClientErrorResponseBody: all fields are null")
}

type GetUnionErrorsInternalServerErrorResponseBodyType string

const (
	GetUnionErrorsInternalServerErrorResponseBodyTypeErrorType1 GetUnionErrorsInternalServerErrorResponseBodyType = "ErrorType1"
	GetUnionErrorsInternalServerErrorResponseBodyTypeErrorType2 GetUnionErrorsInternalServerErrorResponseBodyType = "ErrorType2"
)

// GetUnionErrorsInternalServerErrorResponseBody - Internal Server Error
type GetUnionErrorsInternalServerErrorResponseBody struct {
	ErrorType1 *shared.ErrorType1 `queryParam:"inline" union:"member"`
	ErrorType2 *shared.ErrorType2 `queryParam:"inline" union:"member"`

	Type GetUnionErrorsInternalServerErrorResponseBodyType
}

func CreateGetUnionErrorsInternalServerErrorResponseBodyErrorType1(errorType1 shared.ErrorType1) GetUnionErrorsInternalServerErrorResponseBody {
	typ := GetUnionErrorsInternalServerErrorResponseBodyTypeErrorType1

	return GetUnionErrorsInternalServerErrorResponseBody{
		ErrorType1: &errorType1,
		Type:       typ,
	}
}

func CreateGetUnionErrorsInternalServerErrorResponseBodyErrorType2(errorType2 shared.ErrorType2) GetUnionErrorsInternalServerErrorResponseBody {
	typ := GetUnionErrorsInternalServerErrorResponseBodyTypeErrorType2

	return GetUnionErrorsInternalServerErrorResponseBody{
		ErrorType2: &errorType2,
		Type:       typ,
	}
}

func (u *GetUnionErrorsInternalServerErrorResponseBody) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var errorType1 shared.ErrorType1 = shared.ErrorType1{}
	if err := utils.UnmarshalJSON(data, &errorType1, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GetUnionErrorsInternalServerErrorResponseBodyTypeErrorType1,
			Value: &errorType1,
		})
	}

	var errorType2 shared.ErrorType2 = shared.ErrorType2{}
	if err := utils.UnmarshalJSON(data, &errorType2, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  GetUnionErrorsInternalServerErrorResponseBodyTypeErrorType2,
			Value: &errorType2,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetUnionErrorsInternalServerErrorResponseBody", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetUnionErrorsInternalServerErrorResponseBody", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(GetUnionErrorsInternalServerErrorResponseBodyType)
	switch best.Type {
	case GetUnionErrorsInternalServerErrorResponseBodyTypeErrorType1:
		u.ErrorType1 = best.Value.(*shared.ErrorType1)
		return nil
	case GetUnionErrorsInternalServerErrorResponseBodyTypeErrorType2:
		u.ErrorType2 = best.Value.(*shared.ErrorType2)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for GetUnionErrorsInternalServerErrorResponseBody", string(data))
}

func (u GetUnionErrorsInternalServerErrorResponseBody) MarshalJSON() ([]byte, error) {
	if u.ErrorType1 != nil {
		return utils.MarshalJSON(u.ErrorType1, "", true)
	}

	if u.ErrorType2 != nil {
		return utils.MarshalJSON(u.ErrorType2, "", true)
	}

	return nil, errors.New("could not marshal union type GetUnionErrorsInternalServerErrorResponseBody: all fields are null")
}

// GetUnionErrorsResponseBody - OK
type GetUnionErrorsResponseBody struct {
	Pages []string `json:"pages"`
}

func (g *GetUnionErrorsResponseBody) GetPages() []string {
	if g == nil {
		return []string{}
	}
	return g.Pages
}

type GetUnionErrorsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TwoHundredApplicationJSONObject *GetUnionErrorsResponseBody
	// Not Found
	Error *shared.Error
	// Something went wrong
	FourXXApplicationJSONOneOf *GetUnionErrorsClientErrorResponseBody
	// Internal Server Error
	FiveHundredApplicationJSONOneOf *GetUnionErrorsInternalServerErrorResponseBody

	Next func() (*GetUnionErrorsResponse, error)
}

func (g *GetUnionErrorsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetUnionErrorsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetUnionErrorsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetUnionErrorsResponse) GetTwoHundredApplicationJSONObject() *GetUnionErrorsResponseBody {
	if g == nil {
		return nil
	}
	return g.TwoHundredApplicationJSONObject
}

func (g *GetUnionErrorsResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}

func (g *GetUnionErrorsResponse) GetFourXXApplicationJSONOneOf() *GetUnionErrorsClientErrorResponseBody {
	if g == nil {
		return nil
	}
	return g.FourXXApplicationJSONOneOf
}

func (g *GetUnionErrorsResponse) GetFourXXApplicationJSONOneOfTag1() *shared.TaggedError1 {
	if v := g.GetFourXXApplicationJSONOneOf(); v != nil {
		return v.TaggedError1
	}
	return nil
}

func (g *GetUnionErrorsResponse) GetFourXXApplicationJSONOneOfTag2() *shared.TaggedError2 {
	if v := g.GetFourXXApplicationJSONOneOf(); v != nil {
		return v.TaggedError2
	}
	return nil
}

func (g *GetUnionErrorsResponse) GetFiveHundredApplicationJSONOneOf() *GetUnionErrorsInternalServerErrorResponseBody {
	if g == nil {
		return nil
	}
	return g.FiveHundredApplicationJSONOneOf
}
