//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Speakeasy.OpenAPI
{
    using Speakeasy.OpenAPI;
    using Speakeasy.OpenAPI.Utils;
    using System;

    public interface INamespaceTests
    {
        public IConflicts Conflicts { get; }

        public ISingleFoo SingleFoo { get; }

        public ISingleBar SingleBar { get; }

        public ITypes Types { get; }
    }

    public class NamespaceTests : INamespaceTests
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        /// <summary>
        /// Conflicts SubSDK.
        /// <see cref="IConflicts"/>
        /// </summary>
        public IConflicts Conflicts { get; private set; }

        /// <summary>
        /// SingleFoo SubSDK.
        /// <see cref="ISingleFoo"/>
        /// </summary>
        public ISingleFoo SingleFoo { get; private set; }

        /// <summary>
        /// SingleBar SubSDK.
        /// <see cref="ISingleBar"/>
        /// </summary>
        public ISingleBar SingleBar { get; private set; }

        /// <summary>
        /// Types SubSDK.
        /// <see cref="ITypes"/>
        /// </summary>
        public ITypes Types { get; private set; }

        public NamespaceTests(SDKConfig config)
        {
            SDKConfiguration = config;
            Conflicts = new Conflicts(SDKConfiguration);
            SingleFoo = new SingleFoo(SDKConfiguration);
            SingleBar = new SingleBar(SDKConfiguration);
            Types = new Types(SDKConfiguration);
        }
    }
}