//@ts-ignore
const supportedFeatures = {
  core: "1.8.15",
  getRequestBodies: "0.0.1",
  flattening: "0.0.1",
  globalSecurity: "0.2.9",
  methodSecurity: "0.1.4",
  globalServerURLs: "0.1.1",
  methodServerURLs: "0.0.3",
  globals: "0.1.1",
  enums: "0.1.1",
  serverIDs: "0.1.1",
  nameOverrides: "0.0.4",
  includes: "0.0.1",
  examples: "0.0.8",
  groups: "0.0.3",
  deprecations: "0.0.2",
  inputOutputModels: "0.2.0",
  ignores: "0.0.1",
  typeOverrides: "0.0.1",
  bigint: "0.1.0",
  decimal: "0.1.0",
  multiLevelTagging: "0.1.0",
  downloadStreams: "0.0.2",
  pagination: "0.2.2",
  docs: "0.4.3",
  webhooks: "1.0.0",
  callbacks: "1.0.0",
  unions: "0.0.7",
  errors: "0.2.0",
  additionalProperties: "0.0.2",
  modelNamespaces: "0.1.1",
};

//@ts-ignore
const implementedReadmeSections = [
  "installation",
  "usage",
  "operations",
  "global-parameters",
  "errors",
  "http-client",
  "security",
  "server",
];

//@ts-ignore
function isFeatureSupported(feature: string): boolean {
  return feature in supportedFeatures;
}

//@ts-ignore
function allSupportedFeatures(): string[] {
  const allFeatures = Object.keys(supportedFeatures);
  return allFeatures.filter((feature) => !isFeatureIgnored(feature));
}

//@ts-ignore
function isFeatureIgnored(feature: string): boolean {
  return [
    "disallowCircularRefs",
    "tagBasedOrdering",
    "sets",
    "reactQueryHooks",
  ].includes(feature);
}

//@ts-ignore
function isReadmeSectionImplemented(id: string): boolean {
  return implementedReadmeSections.includes(id);
}

//@ts-ignore
function isReadmeSectionIgnored(id: string): boolean {
  return false;
}

//@ts-ignore
function getStaticallyUsedFeatures(): string[] {
  return [];
}

//@ts-ignore
function getFeatureVersion(feature: string): string {
  return supportedFeatures[feature];
}

//@ts-ignore
function isTestSkipped(test: string): boolean {
  return [
    "event-stream-timeout-still-bounds-slow-stream",
    "event-stream-with-timeout-streams-to-completion",
    "smart-union-nullable-collection-item",
    "smart-union-wrapped-complex-fields",
    "auth-basic-auth-flattened-global",
    "auth-basic-auth-flattened-hoisted",
    "auth-basic-auth-operation-optional",
    "auth-basic-http-global-option",
    "auth-global-security-fields-ordering",
    "auth-global-security-option-fields-ordering",
    "auth-hoisted-security-access-token-first",
    "auth-hoisted-security-api-key-first",
    "auth-hoisted-security-basic-http-only",
    "auth-hoisted-security-invalid-field",
    "auth-hoisted-security-invalid-option",
    "auth-hoisted-security-option-access-token-first",
    "auth-hoisted-security-option-api-key-first",
    "auth-hoisted-security-option-basic-http-only",
    "auth-hoisted-security-access-token-only",
    "servers-select-global-server-by-name-valid-using-builder",
    "collections-containing-null",
    "custom-code-region-sdk-method-with-imports",
    "custom-code-region-sub-sdk-method-with-imports",
    "customclient-request-parameters-retained",
    "event-stream-chat-sentinel-event",
    "event-stream-chat-skip-sentinel",
    "event-stream-different-data-schemas",
    "event-stream-json-data",
    "event-stream-multiline-data",
    "event-stream-rich-events",
    "event-stream-text-data",
    "event-stream-stay-open-break-early",
    "event-stream-stay-open-sentinel",
    "event-stream-with-abort-signal",
    "event-stream-wpt-compliance",
    "event-stream-optional-data-field",
    "errors-union-of-errors",
    "errors-union-of-errors-discriminated",
    "errors-additional-properties",
    "globals-header-keeps-custom-client-headers",
    "globals-hidden-post",
    "globals-optional-hidden-path-parameter-path-required",
    "globals-optional-hidden-path-parameter-operation-required",
    "globals-optional-path-parameter-path-required",
    "globals-optional-path-parameter-operation-required",
    "headers-override-request-headers",
    "headers-empty-response-body-with-headers",
    "headers-error-response-headers-none",
    "headers-error-response-headers-optional",
    "headers-response-headers-none",
    "headers-response-headers-optional",
    "headers-empty-response-body-with-headers-flat",
    "headers-response-body-with-headers-flat",
    "hooks-authorization-header-modification",
    "hooks-client-credentials-no-scopes",
    "hooks-client-credentials-success",
    "hooks-client-credentials-success-alt-token-url",
    "hooks-client-credentials-success-global-server",
    "hooks-client-credentials-option-success",
    "hooks-client-credentials-option-success-alt-token-url",
    "hooks-client-credentials-basic-success",
    "hooks-client-credentials-basic-success-alt-token-url",
    "hooks-client-credentials-basic-success-global-server",
    "open-enums-round-trip",
    "open-enums-round-trip-string-union",
    "pagination-url",
    "pagination-with-retries",
    "pagination-body-wrapped-request",
    "pagination-body-flattened-with-security",
    "pagination-body-flattened-optional-security",
    "pagination-ambiguous-input",
    "pagination-wrapped-optional-body",
    "pagination-limit-offset-default-offset-body",
    "pagination-limit-offset-default-offset-params",
    "pagination-limit-offset-nil-offset-params",
    "pagination-limit-offset-nil-page-params",
    "pagination-limit-offset-nullable",
    "pagination-limit-offset-zero-page-params",
    "pagination-limit-offset-page-params-flat",
    "pagination-limit-offset-union-output-page-params",
    "pagination-limit-offset-union-output-page-params-flat",
    "pagination-cursor-response-envelope",
    "pagination-cursor-non-numeric-with-limit",
    "pagination-cursor-params-snake",
    "pagination-cursor-snake",
    "pagination-limit-offset-params-snake",
    "pagination-limit-offset-snake",
    "pagination-simple-object-snake",
    "pagination-cursor-non-numeric-empty-string",
    "pagination-limit-offset-page-params-const",
    "pagination-params-wrapped-request",
    "parameters-const-query-params",
    "parameters-deep-object-query-params-deep-object",
    "parameters-form-query-params-camel-object",
    "parameters-path-encoding",
    "parameters-query-encoding",
    "parameters-header-params-nil",
    "request-bodies-wildcard-no-content-type",
    "request-bodies-complex-number-types",
    "request-bodies-defaults-and-consts",
    "request-bodies-deprecated-request-body-ref",
    "request-bodies-get-inferred-optional-request-wrapper",
    "request-bodies-post-application-json-array-camel-case",
    "request-bodies-post-application-json-array-object-camel-case",
    "request-bodies-post-application-json-array-of-array-camel-case",
    "request-bodies-post-application-json-array-of-map-camel-case",
    "request-bodies-post-application-json-deep-camel-case",
    "request-bodies-post-application-json-map-camel-case",
    "request-bodies-post-application-json-map-object-camel-case",
    "request-bodies-post-application-json-map-of-array-camel-case",
    "request-bodies-post-application-json-map-of-map-camel-case",
    "request-bodies-put-different-file-name",
    "request-bodies-put-multipart-file-streaming",
    "request-bodies-put-bytes-streaming",
    "request-bodies-read-only-union",
    "request-bodies-form-encoded-string-array",
    "request-bodies-read-write-only-union",
    "request-bodies-write-only-union",
    "request-bodies-file-upload-extract-content-type",
    "response-bodies-accept-header-default",
    "response-bodies-accept-header-override",
    "response-bodies-decimal-string",
    "response-bodies-overridden-field-names",
    "response-bodies2xx-json-object-all-optional-properties",
    "retries-connect-error",
    "retries-global-config-disable",
    "retries-global-config-success",
    "retries-global-config-timeout",
    "retries-header",
    "retries-request-timeout",
    "retries-succeeds",
    "retries-succeeds-with-body",
    "retries-timeout",
    "servers-override-global-server-url",
    "servers-override-operation-server-url",
    "test-hooks",
    "test-hooks-after-response",
    "test-hooks-before-create-request",
    "test-hooks-error",
    "unions-collections-one-of-post",
    "unions-union-map",
    "unions-extra-json-properties",
    "unions-nested-enums-form",
    "unions-nested-enums-multipart",
    "unions-array-of-discriminated-unions",
    "unions-array-of-discriminated-unions-map",
    "unions-nested-array-of-discriminated-unions",
    "auth-custom-security-scheme-app-id",
    "auth-custom-security-option-app-id",
    "flattening-component-body-and-param-no-conflict-flatten-requests",
    "flattening-component-body-and-param-conflict-flatten-requests",
    "flattening-inline-body-and-param-conflict-flatten-requests",
    "flattening-inline-body-and-param-no-conflict-flatten-requests",
    "flattening-conflicting-params-flatten-requests",
    "flattening-required-body-all-optional-flatten-requests",
    "hooks-access-retry-config",
    "hooks-terminate-retry-loop",
    "hooks-trigger-retries",
    "webhooks-consume",
    "webhooks-consume-custom-security",
    "webhooks-consume-bad-data",
    "webhooks-consume-bad-signature",
    "hooks-oauth2-password-bad-credentials",
    "hooks-oauth2-password-operation-scope",
    "hooks-oauth2-password-operation-security-option",
    "hooks-oauth2-password-token-renewal",
    "hooks-oauth2-password-with-credentials",
    "hooks-oauth2-password-with-token",
    "hooks-oauth2-password-not-required",
    "hooks-available-oauth2-scopes",
    "auth-operation-level-oauth2",
    "no-servers",
    "relative-servers",
    "jsonl-stream-data-async-envelope-http-responses",
    "jsonl-stream-data-chunks-envelope-http-responses",
    "jsonl-stream-data-flat-responses",
    "jsonl-stream-data-async-chunks-flat-response",
    "jsonl-stream-data-envelope-http-responses",
    "jsonl-stream-data-async-flat-response",
    "jsonl-stream-data-chunks-flat-response",
    "x-ndjson-stream-data-envelope-http-responses",
    "x-ndjson-stream-data-async-envelope-http-responses",
    "x-ndjson-stream-data-chunks-envelope-http-responses",
    "x-ndjson-stream-data-async-chunks-envelope-http-responses",
    "unions-optional-union-map",
    "unions-mixed-union-types",
    "union-enum-nested-in-array-in-union",
    "servers-select-global-server-by-id-default-using-builder",
    "servers-select-global-server-by-name-broken-using-builder",
    "servers-select-global-server-by-name-default-using-builder",
    "servers-select-global-server-by-name-with-templates-broken-using-builder",
    "servers-select-global-server-by-name-with-templates-defaults-using-builder",
    "servers-select-global-server-by-name-with-templates-valid-using-builder",
    "servers-select-global-server-by-id-valid-using-builder",
    "servers-select-global-server-by-id-invalid-using-builder",
    "servers-select-global-server-by-id-broken-using-builder",
    "custom-code-region-model-method-with-imports",
    "parameters-open-enum",
    "hooks-client-credentials-lowercase-bearer",
    "parameters-form-query-params-unions",
    "parameters-ordering-body-first",
    "parameters-ordering-parameters-first",
    "parameters-ordering-with-legacy-flattening-order",
    "parameters-ordering-using-optional-request-body-body-first",
    "parameters-ordering-using-optional-request-body-parameters-first",
    "parameters-ordering-using-optional-request-body-with-legacy-flattening-order",
    "parameters-allow-empty-value",
    "redirects-are-followed",
    "cancellation-token-cancelled-before-request",
    "cancellation-token-cancelled-during-request",
    "cancellation-token-cancelled-inside-hook",
    "cancellation-token-no-cancellation",
    "customclient-request-parameters-retained-legacy",
    "unions-strongly-typed-nullable-one-of-post",
    "unions-one-of-boolean-and-string-enum-with-response-boolean",
    "unions-one-of-boolean-and-string-enum-with-response-enum",
    "unions-nested-discriminated-union",
    "unions-conflicting-discriminator-mapping-key",
    "object-with-optional-false-nullable-false-field-absent",
    "object-with-optional-false-nullable-false-field-null",
    "object-with-optional-false-nullable-false-full",
    "object-with-optional-false-nullable-true-field-null",
    "object-with-optional-false-nullable-true-full",
    "object-with-optional-nullable-field-absent",
    "object-with-optional-nullable-field-null",
    "object-with-optional-nullable-full",
    "object-with-optional-true-nullable-false-field-absent",
    "object-with-optional-true-nullable-false-field-null",
    "object-with-optional-true-nullable-false-full",
    "object-with-optional-false-nullable-true-field-absent",
    "auth-custom-security-scheme-only",
    "transform-jq-request-response",
    "polling-delay-seconds-override",
    "polling-delay-seconds",
    "polling-failure-criteria-response-body-nested",
    "polling-failure-criteria-response-body-optional",
    "polling-failure-criteria-response-body-regex",
    "polling-failure-criteria-response-body",
    "polling-failure-criteria-status-code-regex",
    "polling-failure-criteria-status-code",
    "polling-interval-seconds-override",
    "polling-interval-seconds",
    "polling-limit-count-override",
    "polling-limit-count",
    "polling-success-criteria-response-body-nested",
    "polling-success-criteria-response-body-optional",
    "polling-success-criteria-response-body-regex",
    "polling-success-criteria-response-body",
    "polling-success-criteria-status-code-error-known",
    "polling-success-criteria-status-code-error-regex",
    "polling-success-criteria-status-code-error-unknown",
    "polling-success-criteria-status-code-regex",
    "polling-success-criteria-status-code",
    "globals-operation-params-only",
    "globals-kebab-case-param-get",
    "smart-union-nested-union",
    "unions-discriminated-open-enum",
    "open-enums-response-usage",
    "smart-union-any-field-type",
    "smart-union-array-fields",
    "smart-union-const-field-discrimination",
    "smart-union-nested-structs",
    "smart-union-optional-pointer-fields",
    "smart-union-optional-pointer-structs",
    "smart-union-prefers-fewer-unmatched-fields",
    "smart-union-preserves-order-on-tie",
    "smart-union-selects-more-matched-fields",
    "smart-union-three-way-field-discrimination",
    "smart-union-nested-union-vs-flat-struct",
    "smart-union-union-vs-union",
    "union-enum-array-deserialization",
    "custom-client-http-proxy",
    "open-union-embedded",
    "open-union-known-variant",
    "open-union-smart-union-interop",
    "open-union-invalid-payload",
    "open-union-known-disc-invalid-schema",
    "open-union-missing-discriminator",
    "open-union-unknown-discriminator",
    "event-stream-union-with-standalone-comments",
    "unions-const-discriminator",
    "unions-discriminated-multiple-memberships",
    "event-stream-mixed-data",
    "response-bodies-empty-object-freeform",
    "event-stream-chat-heartbeat-skips-dataless",
    "pagination-cursor-nullable-limit",
    "timeout-ms-override-allows-completion",
    "timeout-ms-override-is-respected",
    "auth-hoisted-op-basic-auth",
    "request-bodies-complex-number-types-nullable-null",
    "request-bodies-complex-number-types-nullable-set",
    "request-bodies-complex-number-types-optional-populated",
    "request-bodies-complex-number-types-optional-unpopulated",
    "request-bodies-complex-number-types-required-missing",
    "flattening-nullable-body-with-required-param-ordering",
    "errors-status-get-error-x-speakeasy-errors-default",
    "errors-status-get-error-x-speakeasy-errors-none",
    "unions-circular-reference-recursive-one-of",
    "retries-timeout-fresh-signal",
    "auth-global-security-flattening-env-var-fallback",
    "request-bodies-base64-input-mode-file-shared-component",
    "request-bodies-base64-input-mode-file-split-components",
    "event-stream-chat-json",
    "unions-strongly-typed-one-of-discriminated-post",
    "event-stream-sse-overload-json-response",
    "event-stream-sse-overload-streaming-response",
    "raw-response-helpers-strip-internal-header",
    "unions-typed-object-one-of-post-body-less-throws",
    "request-bodies-put-multipart-file-bytesio",
    "request-bodies-put-multipart-file-handle",
    "request-bodies-put-multipart-file-stringio",
    "request-extras-extra-body-merged",
    "request-extras-extra-body-overrides",
    "request-extras-extra-body-rejects-non-json",
    "request-extras-extra-query-appended",
    "request-extras-extra-query-merged",
    "request-extras-extra-query-nullish-arrays",
    "request-extras-extra-query-object-json",
    "request-extras-extra-query-overrides",
    "request-extras-extra-query-preserves-server-url-query",
    "request-extras-extra-query-security-overrides",
    "collections-map-input-accepts-non-dict-mapping",
    "collections-parameter-annotations-advertise-iterables",
    "collections-parameters-accept-iterables",
    "collections-parameters-accept-iterables-direct",
    "pagination-cursor-deep-nested-outputs",
    "pagination-cursor-deep-nested-outputs-iterator",
    "event-stream-large-event-small-chunks",
    "event-stream-split-boundaries",
    "request-bodies-base64-file-input-idempotent",
    "retries-attempt-count-backoff",
    "retries-attempt-count-zero",
    "errors-error-body-validation-disabled",
    "errors-error-body-validation-enabled",
    "errors-response-body-validation-disabled",
    "errors-custom-error-inheritance",
    "errors-response-body-validation-enabled",
    "errors-schema-validation-disabled",
    "errors-schema-validation-enabled",
    "errors-optional-nullable-error-message",
    "errors-optional-nullable-error-message-nested",
    "retries-status-codes-override",
    "retries-status-codes-override-global",
    "retries-status-codes-override-default",
    "errors-response-body-validation-lenient",
    "hooks-access-operation-metadata",
    "request-bodies-duration-format",
    "request-bodies-uuid-format",
    "react-query-builders-key-distinct-bodies",
    "react-query-key-includes-parameters-and-request-body",
    "react-query-key-includes-request-body",
    "react-query-key-opt-in-infers-query-type",
    "smart-union-nested-union-vs-nested-union",
    "request-bodies-put-multipart-optional-nullable",
    "request-bodies-post-form-optional-nullable",
    "request-bodies-post-json-optional-nullable",
    "smart-union-nullable-union-nullable-fields",
    "request-bodies-post-form-optional-nullable-json-shared",
    "request-bodies-put-multipart-optional-nullable-json-shared",
    "request-bodies-post-json-optional-nullable-body-and-param",
    "pagination-limit-offset-page-body-nullable",
    "pagination-limit-offset-page-body-optional-nullable",
    "pagination-cursor-nullable-results",
    "retries-binary-request-body",
    "retries-header-http-date-beyond-max-interval",
    "retries-header-rate-limit-reset",
    "errors-error-body-validation-lenient",
    "errors-response-body-validation-lenient-non-json",
    "errors-response-body-validation-lenient-union-variant",
    "event-stream-malformed-frame-lenient",
    "event-stream-malformed-frame-strict",
    "agent-mode-does-not-leak-between-invocations",
    "catalog-lists-values",
    "catalog-rejects-positional-argument",
    "catalog-structured-output",
    "cli-exit-code-bare-intent",
    "cli-exit-code-connection-and-agent-block",
    "cli-exit-code-mapping-tables",
    "cli-exit-code-reason-first",
    "cli-exit-code-root-unknown-message",
    "cli-exit-code-single-envelope",
    "cli-exit-code-success-and-discovery",
    "cli-exit-codes-rendering-modes",
    "client-credentials-dry-run-token-and-api",
    "clierrors-agent-mode-explicitly-disabled",
    "clierrors-agent-mode-from-environment",
    "clierrors-agent-mode-matrix",
    "clierrors-api-error-not-double-wrapped",
    "clierrors-declared-hints-fire",
    "clierrors-flag-values-not-rendering-flags",
    "clierrors-invalid-values-do-not-stop-preparse",
    "clierrors-json-output-envelope",
    "clierrors-plain-mode-classified",
    "clierrors-typed-reasons",
    "error-taxonomy-declared-rules-and-ordering",
    "error-taxonomy-every-closed-type-has-a-hint",
    "error-taxonomy-fallback-message-omits-raw-body",
    "error-taxonomy-hint-precedence-and-dedupe",
    "error-taxonomy-jq-uses-structured-envelope",
    "error-taxonomy-odd-bodies-use-fallback-envelope",
    "error-taxonomy-odd-reflection-fields-do-not-panic",
    "error-taxonomy-origin-semantics",
    "error-taxonomy-pretty-http-status-without-reason",
    "error-taxonomy-pretty-json-agent-parity",
    "error-taxonomy-pretty-residual-details",
    "error-taxonomy-reserved-keys-and-rendered-classification",
    "event-stream-connection-refused-stays-connection-error",
    "event-stream-decode-failure-is-protocol-error",
    "event-stream-decode-failure-without-json-error-type",
    "event-stream-error-event-agent-mode",
    "event-stream-error-event-agent-mode-fallback",
    "event-stream-error-event-exits-non-zero",
    "event-stream-error-event-pretty",
    "event-stream-numbers-keep-precision",
    "event-stream-server-error-mentioning-decode-is-not-protocol-error",
    "event-stream-timeout-still-bounds-slow-stream",
    "event-stream-undiscriminated-error-shaped-variant-is-data",
    "event-stream-union-events-render-wire-shape",
    "hooks-custom-user-agent",
    "intent-dispatch-resolves-stdin-once",
    "intent-dispatch-select-matrix",
    "intent-interactive-piped-body-skips-prompts",
    "intent-route-dispatch-agent-envelope",
    "intent-route-dispatch-bare-help",
    "intent-route-dispatch-body-evidence",
    "intent-route-dispatch-conflicting-evidence",
    "intent-route-dispatch-default-required",
    "intent-route-dispatch-flag-paths",
    "intent-route-dispatch-help-usage",
    "intent-route-dispatch-interactive-plan",
    "intent-route-dispatch-override-once",
    "intents-both-body-surfaces-merged",
    "intents-discriminated-partial-body",
    "intents-foreign-selector-agent-envelope",
    "intents-foreign-selector-usage-error",
    "intents-non-object-body-falls-through",
    "intents-partial-body-keeps-presets",
    "intents-partial-body-user-keys-win",
    "intents-preset-from-args",
    "intents-preset-merge-matrix",
    "intents-undeclared-nested-group-order",
    "pre-request-connection-classifier-typed-table",
    "pre-request-discriminated-root-union-messages",
    "pre-request-dry-run-unresolvable-host",
    "pre-request-generated-required-union-paths-and-optionality",
    "pre-request-generated-required-union-positive-echoes",
    "pre-request-real-connection-failures",
    "pre-request-silent-stdin-times-out-on-root-union",
    "pre-request-validation-envelope-matrix",
    "request-bodies-complex-number-types-bigint-overflow",
    "request-shape-body-agent-variant",
    "request-shape-body-and-whole-body-flag-rejected",
    "request-shape-body-both-selectors-rejected",
    "request-shape-body-default-selector-merges",
    "request-shape-body-null-optional-key-allowed",
    "request-shape-body-typo-key-rejected",
    "request-shape-expanded-body-typo-key-lenient-warning",
    "request-shape-expanded-body-typo-key-rejected",
    "request-shape-intent-bare-usage",
    "request-shape-intent-empty-stdin-usage",
    "request-shape-intent-flag-and-body-conflict",
    "request-shape-intent-flag-merged-into-body",
    "request-shape-intent-positional-and-body-conflict",
    "request-shape-intent-positional-merged-into-body",
    "request-shape-intent-positional-merged-into-whole-body-flag",
    "request-shape-intent-stdin-runs-request",
    "request-shape-intent-stdin-typo-key-rejected",
    "request-shape-intent-stdin-with-positional",
    "request-shape-intent-synthesized-body",
    "request-shape-intent-zero-value-flag-merged",
    "request-shape-nested-union-agent-selector-no-default",
    "request-shape-nested-union-body-default-selector-merges",
    "request-shape-nested-union-own-flag-default-selector-merges",
    "request-shape-nested-union-stdin-default-selector-merges",
    "request-shape-open-schema-keeps-unknown-keys",
    "request-shape-stdin-typo-key-rejected",
    "request-shape-whole-body-flag-typo-key-rejected",
    "request-shape-whole-body-flag-wins-over-stdin",
    "security-ranking-both-flags",
    "security-ranking-env-only",
    "security-ranking-env-tie",
    "security-ranking-flag-beats-env",
    "security-ranking-operation-restriction",
    "security-ranking-pick-matrix",
    "security-ranking-source-rank",
    "event-stream-with-operation-timeout-streams-to-completion",
    "jsonl-stream-timeout-still-bounds-slow-stream",
    "jsonl-stream-with-timeout-streams-to-completion",
    "open-union-strict-request-validation",
  ].includes(test);
}

//@ts-ignore
function getAutoGeneratedHeader(
  generatedId: string,
  config: Record<string, any>,
): string {
  let header = `
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//`;
  if (generatedId) {
    header += `\n// @generated-id: ${generatedId}`;
  }
  if (config.GeneratedLicense === "agpl") {
    header +=
      "\n// Generated under the AGPL-3.0-only license." +
      "\n// SPDX-License-Identifier: AGPL-3.0-only";
  }
  header += `
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
`;
  return header;
}
