// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

// Package output — streaming support (SSE EventStream, JSONL/NDJSON).
// This file is generated only when at least one operation has a streaming response.
package output

import (
	"encoding/json"
	"errors"
	"reflect"
	"strings"

	"github.com/spf13/cobra"

	"openapi/internal/flagutil"
)

// StreamResult iterates a streaming response (SSE EventStream or JSONL/NDJSON
// JsonLStream) and outputs each event incrementally. streamFieldName is the Go
// field name on the response envelope that holds the stream (e.g., "EventStream",
// "Object"). The function uses reflection to call Next()/Value()/Err()/Close()
// on the stream field, handling both EventStream (Value() *T) and JsonLStream
// (Value() (T, error)) signatures.
func StreamResult(cmd *cobra.Command, res interface{}, streamFieldName string) error {
	if flagutil.DidDryRunRequest(cmd) {
		return nil
	}
	ctx := cmd.Context()
	out := cmd.OutOrStdout()
	format := resolveOutputFormat(cmd)
	colorFlag, _ := flagutil.GetStringFlag(cmd, "color")
	colorize := ShouldColorize(colorFlag)
	jqExpr, _ := flagutil.GetStringFlag(cmd, "jq")
	jqRaw := jqRawOutput(cmd)

	// Extract the stream field from the response envelope via reflection
	v := reflect.ValueOf(res)
	if v.Kind() == reflect.Ptr {
		if v.IsNil() {
			return nil
		}
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		// Fallback: not a struct envelope — output as regular result
		return Result(cmd, res)
	}
	streamVal := v.FieldByName(streamFieldName)
	if !streamVal.IsValid() {
		// Fallback: stream field not found — output as regular result
		return Result(cmd, res)
	}
	// Guard IsNil: only call on nillable kinds. Fall back to Result() for
	// mixed-content operations where non-stream content may still exist.
	if isNillable(streamVal) && streamVal.IsNil() {
		return Result(cmd, res)
	}

	// Validate streaming interface: must have Next and Value methods
	nextMethod := streamVal.MethodByName("Next")
	valueMethod := streamVal.MethodByName("Value")
	errMethod := streamVal.MethodByName("Err")
	closeMethod := streamVal.MethodByName("Close")
	if !nextMethod.IsValid() || !valueMethod.IsValid() {
		// Fallback: not a streaming type — output as regular result
		return Result(cmd, res)
	}

	if closeMethod.IsValid() {
		defer closeMethod.Call(nil)
	}

	projector := newStreamProjector(cmd)

	// Projected output already written must end with its terminating
	// newline before any error is rendered. The primary error keeps the
	// exit classification; a failed finish is joined rather than swallowed.
	finishJoin := func(primary error) error {
		if projector != nil {
			if finishErr := projector.finish(out); finishErr != nil {
				return errors.Join(primary, finishErr)
			}
		}
		return primary
	}

	first := true
	for {
		// Check for context cancellation (Ctrl+C)
		select {
		case <-ctx.Done():
			return finishJoin(ctx.Err())
		default:
		}

		// Call Next() bool
		nextResults := nextMethod.Call(nil)
		if !nextResults[0].Bool() {
			break
		}

		// Call Value() — handles both:
		//   EventStream: Value() *T (1 return value)
		//   JsonLStream: Value() (T, error) (2 return values)
		valueResults := valueMethod.Call(nil)
		var item interface{}
		if len(valueResults) == 2 {
			// JsonLStream: check error — route through Error() for JSON formatting
			if !valueResults[1].IsNil() {
				return finishJoin(Error(cmd, valueResults[1].Interface().(error)))
			}
			item = valueResults[0].Interface()
		} else {
			// EventStream: dereference pointer if needed
			val := valueResults[0]
			if val.Kind() == reflect.Ptr && !val.IsNil() {
				item = val.Elem().Interface()
			} else if val.Kind() == reflect.Ptr && val.IsNil() {
				continue // skip nil events
			} else {
				item = val.Interface()
			}
		}

		if len(valueResults) == 1 {
			if body, isErr := streamErrorEvent(item); isErr {
				return finishJoin(Error(cmd, &StreamEventError{Body: string(body)}))
			}
		}

		if projector != nil {
			if err := projector.emit(out, item); err != nil {
				return finishJoin(err)
			}
		} else if err := outputOneItem(out, item, format, jqExpr, colorize, jqRaw, first); err != nil {
			return err
		}
		first = false
	}

	// Check for stream errors — route through Error() for consistent
	// --output-format json behavior
	if errMethod.IsValid() {
		errResults := errMethod.Call(nil)
		if len(errResults) > 0 && !errResults[0].IsNil() {
			return finishJoin(Error(cmd, errResults[0].Interface().(error)))
		}
	}

	if projector != nil {
		return projector.finish(out)
	}
	return nil
}

func streamErrorEvent(item interface{}) (json.RawMessage, bool) {
	u, ok := errorUnionValue(reflect.ValueOf(item))
	if !ok {
		return nil, false
	}
	data, err := marshalJSON(u.Interface())
	if err != nil {
		return nil, false
	}
	return data, true
}

func errorUnionValue(v reflect.Value) (reflect.Value, bool) {
	v = derefValue(v)
	if v.Kind() != reflect.Struct {
		return reflect.Value{}, false
	}
	if isUnionStruct(v.Type()) {
		if unionNamesErrorVariant(v) {
			return v, true
		}
		return reflect.Value{}, false
	}
	data := derefValue(v.FieldByName("Data"))
	if data.Kind() == reflect.Struct && isUnionStruct(data.Type()) && unionNamesErrorVariant(data) {
		return data, true
	}
	return reflect.Value{}, false
}

func derefValue(v reflect.Value) reflect.Value {
	for v.IsValid() && (v.Kind() == reflect.Ptr || v.Kind() == reflect.Interface) {
		if v.IsNil() {
			return reflect.Value{}
		}
		v = v.Elem()
	}
	return v
}

func isUnionStruct(t reflect.Type) bool {
	for i := 0; i < t.NumField(); i++ {
		if t.Field(i).Tag.Get("union") == "member" {
			return true
		}
	}
	return false
}

func unionNamesErrorVariant(u reflect.Value) bool {
	typeField := u.FieldByName("Type")
	return typeField.IsValid() && typeField.Kind() == reflect.String && isErrorDiscriminator(typeField.String())
}

// Case-sensitive: undiscriminated unions put PascalCase variant names ("ErrorEvent") in Type.
func isErrorDiscriminator(value string) bool {
	if value == "error" {
		return true
	}
	return strings.HasSuffix(value, ".error") || strings.HasSuffix(value, "_error") || strings.HasSuffix(value, "-error")
}

// isNillable returns true if IsNil() can be safely called on v.
func isNillable(v reflect.Value) bool {
	switch v.Kind() {
	case reflect.Ptr, reflect.Interface, reflect.Map, reflect.Slice, reflect.Func, reflect.Chan:
		return true
	}
	return false
}
