/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.baz;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * Pet
 *
 * <p>A pet in the baz namespace with completely different schema
 */
public class Pet {

    @JsonProperty("petId")
    private long petId;

    @JsonProperty("petName")
    private String petName;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("adoptedAt")
    private OffsetDateTime adoptedAt;

    @JsonCreator
    public Pet(
            @JsonProperty("petId") long petId,
            @JsonProperty("petName") @Nonnull String petName,
            @JsonProperty("adoptedAt") @Nullable OffsetDateTime adoptedAt) {
        this.petId = petId;
        this.petName =
                Optional.ofNullable(petName).orElseThrow(() -> new IllegalArgumentException("petName cannot be null"));
        this.adoptedAt = adoptedAt;
    }

    public Pet(long petId, @Nonnull String petName) {
        this(petId, petName, null);
    }

    public long petId() {
        return this.petId;
    }

    public String petName() {
        return this.petName;
    }

    public Optional<OffsetDateTime> adoptedAt() {
        return Optional.ofNullable(this.adoptedAt);
    }

    public static Builder builder() {
        return new Builder();
    }

    public Pet withPetId(long petId) {
        this.petId = petId;
        return this;
    }

    public Pet withPetName(@Nonnull String petName) {
        this.petName = Utils.checkNotNull(petName, "petName");
        return this;
    }

    public Pet withAdoptedAt(@Nullable OffsetDateTime adoptedAt) {
        this.adoptedAt = adoptedAt;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Pet other = (Pet) o;
        return Utils.enhancedDeepEquals(this.petId, other.petId)
                && Utils.enhancedDeepEquals(this.petName, other.petName)
                && Utils.enhancedDeepEquals(this.adoptedAt, other.adoptedAt);
    }

    @Override
    public int hashCode() {
        return Utils.enhancedHash(petId, petName, adoptedAt);
    }

    @Override
    public String toString() {
        return Utils.toString(Pet.class, "petId", petId, "petName", petName, "adoptedAt", adoptedAt);
    }

    @SuppressWarnings("UnusedReturnValue")
    public static final class Builder {

        private long petId;

        private String petName;

        private OffsetDateTime adoptedAt;

        private Builder() {
            // force use of static builder() method
        }

        public Builder petId(long petId) {
            this.petId = petId;
            return this;
        }

        public Builder petName(@Nonnull String petName) {
            this.petName = Utils.checkNotNull(petName, "petName");
            return this;
        }

        public Builder adoptedAt(@Nullable OffsetDateTime adoptedAt) {
            this.adoptedAt = adoptedAt;
            return this;
        }

        public Pet build() {
            return new Pet(petId, petName, adoptedAt);
        }
    }
}
