// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// Escalation configuration with string-encoded integer expiration
type Escalation struct {
	Enabled bool `json:"enabled"`
	// Expiration in seconds, encoded as a string in the API response
	Expiration        string   `json:"expiration"`
	FallbackApprovers []string `json:"fallbackApprovers"`
}

func (e *Escalation) GetEnabled() bool {
	if e == nil {
		return false
	}
	return e.Enabled
}

func (e *Escalation) GetExpiration() string {
	if e == nil {
		return ""
	}
	return e.Expiration
}

func (e *Escalation) GetFallbackApprovers() []string {
	if e == nil {
		return []string{}
	}
	return e.FallbackApprovers
}
