// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/internal/utils"
)

// DiscriminatedUnionItemB - Test case - exact match (both discriminator key and model name match). Has 'type_varying_field' as class type (defined properties) to test shared field names with different types across variants.
type DiscriminatedUnionItemB struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_  string `const:"item_b" json:"type"`
	ValueB string `json:"value_b"`
	// Schema with defined properties (becomes class type). Used to test shared field names with structurally different types across discriminated union variants.
	TypeVaryingField *DiscriminatedUnionClassTypeVaryingField `json:"type_varying_field,omitempty"`
}

func (d DiscriminatedUnionItemB) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DiscriminatedUnionItemB) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DiscriminatedUnionItemB) GetType() string {
	return "item_b"
}

func (d *DiscriminatedUnionItemB) GetValueB() string {
	if d == nil {
		return ""
	}
	return d.ValueB
}

func (d *DiscriminatedUnionItemB) GetTypeVaryingField() *DiscriminatedUnionClassTypeVaryingField {
	if d == nil {
		return nil
	}
	return d.TypeVaryingField
}
