// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ImportMultipleIDResponse struct {
	Param1              *string `json:"param1,omitempty"`
	Param2              *string `json:"param2,omitempty"`
	RequestBodyProperty *string `json:"requestBodyProperty,omitempty"`
}

func (i *ImportMultipleIDResponse) GetParam1() *string {
	if i == nil {
		return nil
	}
	return i.Param1
}

func (i *ImportMultipleIDResponse) GetParam2() *string {
	if i == nil {
		return nil
	}
	return i.Param2
}

func (i *ImportMultipleIDResponse) GetRequestBodyProperty() *string {
	if i == nil {
		return nil
	}
	return i.RequestBodyProperty
}
