// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OASMinitemsResponse struct {
	ID *string `json:"id,omitempty"`
	// list oneOf request and response minItems (union of 1 and 2)
	ListOneofRequestAndResponse []string `json:"list_oneof_request_and_response,omitempty"`
	// list oneOf request only minItems (union of 1 and 2)
	ListOneofRequest []string `json:"list_oneof_request,omitempty"`
	// list oneOf response only minItems (union of 1 and 2)
	ListOneofResponse []string `json:"list_oneof_response,omitempty"`
	// list request and response minItems (both 12)
	ListRequestAndResponse []string `json:"list_request_and_response,omitempty"`
	// list request only minItems (1)
	ListRequest []string `json:"list_request,omitempty"`
	// list response only minItems (2)
	ListResponse []string `json:"list_response,omitempty"`
	// list request and response minItems (both 11) and maxItems (both 12)
	ListWithMaxitems []string `json:"list_with_maxitems,omitempty"`
	// set oneOf request and response minItems (union of 1 and 2)
	SetOneofRequestAndResponse []string `json:"set_oneof_request_and_response,omitempty"`
	// set oneOf request only minItems (union of 1 and 2)
	SetOneofRequest []string `json:"set_oneof_request,omitempty"`
	// set oneOf response only minItems (union of 1 and 2)
	SetOneofResponse []string `json:"set_oneof_response,omitempty"`
	// set request and response minItems (both 12)
	SetRequestAndResponse []string `json:"set_request_and_response,omitempty"`
	// set request only minItems (1)
	SetRequest []string `json:"set_request,omitempty"`
	// set response only minItems (2)
	SetResponse []string `json:"set_response,omitempty"`
	// set request and response minItems (both 11) and minItems (both 12)
	SetWithMinitems []string `json:"set_with_minitems,omitempty"`
}

func (o *OASMinitemsResponse) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OASMinitemsResponse) GetListOneofRequestAndResponse() []string {
	if o == nil {
		return nil
	}
	return o.ListOneofRequestAndResponse
}

func (o *OASMinitemsResponse) GetListOneofRequest() []string {
	if o == nil {
		return nil
	}
	return o.ListOneofRequest
}

func (o *OASMinitemsResponse) GetListOneofResponse() []string {
	if o == nil {
		return nil
	}
	return o.ListOneofResponse
}

func (o *OASMinitemsResponse) GetListRequestAndResponse() []string {
	if o == nil {
		return nil
	}
	return o.ListRequestAndResponse
}

func (o *OASMinitemsResponse) GetListRequest() []string {
	if o == nil {
		return nil
	}
	return o.ListRequest
}

func (o *OASMinitemsResponse) GetListResponse() []string {
	if o == nil {
		return nil
	}
	return o.ListResponse
}

func (o *OASMinitemsResponse) GetListWithMaxitems() []string {
	if o == nil {
		return nil
	}
	return o.ListWithMaxitems
}

func (o *OASMinitemsResponse) GetSetOneofRequestAndResponse() []string {
	if o == nil {
		return nil
	}
	return o.SetOneofRequestAndResponse
}

func (o *OASMinitemsResponse) GetSetOneofRequest() []string {
	if o == nil {
		return nil
	}
	return o.SetOneofRequest
}

func (o *OASMinitemsResponse) GetSetOneofResponse() []string {
	if o == nil {
		return nil
	}
	return o.SetOneofResponse
}

func (o *OASMinitemsResponse) GetSetRequestAndResponse() []string {
	if o == nil {
		return nil
	}
	return o.SetRequestAndResponse
}

func (o *OASMinitemsResponse) GetSetRequest() []string {
	if o == nil {
		return nil
	}
	return o.SetRequest
}

func (o *OASMinitemsResponse) GetSetResponse() []string {
	if o == nil {
		return nil
	}
	return o.SetResponse
}

func (o *OASMinitemsResponse) GetSetWithMinitems() []string {
	if o == nil {
		return nil
	}
	return o.SetWithMinitems
}
