// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OASMinlengthResponse struct {
	ID *string `json:"id,omitempty"`
	// oneOf request and response minLengths (union of 1 and 2)
	OneofRequestAndResponse *string `json:"oneof_request_and_response,omitempty"`
	// oneOf request only minLengths (union of 1 and 2)
	OneofRequest *string `json:"oneof_request,omitempty"`
	// oneOf response only minLengths (union of 1 and 2)
	OneofResponse *string `json:"oneof_response,omitempty"`
	// request and response minLength (both 12)
	RequestAndResponse *string `json:"request_and_response,omitempty"`
	// request only minLength (1)
	Request *string `json:"request,omitempty"`
	// response only minLength (2)
	Response *string `json:"response,omitempty"`
}

func (o *OASMinlengthResponse) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OASMinlengthResponse) GetOneofRequestAndResponse() *string {
	if o == nil {
		return nil
	}
	return o.OneofRequestAndResponse
}

func (o *OASMinlengthResponse) GetOneofRequest() *string {
	if o == nil {
		return nil
	}
	return o.OneofRequest
}

func (o *OASMinlengthResponse) GetOneofResponse() *string {
	if o == nil {
		return nil
	}
	return o.OneofResponse
}

func (o *OASMinlengthResponse) GetRequestAndResponse() *string {
	if o == nil {
		return nil
	}
	return o.RequestAndResponse
}

func (o *OASMinlengthResponse) GetRequest() *string {
	if o == nil {
		return nil
	}
	return o.Request
}

func (o *OASMinlengthResponse) GetResponse() *string {
	if o == nil {
		return nil
	}
	return o.Response
}
