// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OASMinimumRequest struct {
	// float32 oneOf request and response minimums (union of 1.1 and 2.2)
	Float32OneofRequestAndResponse *float32 `json:"float32_oneof_request_and_response,omitempty"`
	// float32 oneOf request only minimums (union of 1.1 and 2.2)
	Float32OneofRequest *float32 `json:"float32_oneof_request,omitempty"`
	// float32 oneOf response only minimums (union of 1.1 and 2.2)
	Float32OneofResponse *float32 `json:"float32_oneof_response,omitempty"`
	// float32 request and response minimum (both 12.12)
	Float32RequestAndResponse *float32 `json:"float32_request_and_response,omitempty"`
	// float32 request only minimum (1.1)
	Float32Request *float32 `json:"float32_request,omitempty"`
	// float32 response only minimum (2.2)
	Float32Response *float32 `json:"float32_response,omitempty"`
	// float32 request and response minimum (both 11.11) and maximum (both 12.12)
	Float32WithMaximum *float32 `json:"float32_with_maximum,omitempty"`
	// float64 oneOf request and response minimums (union of 1.1 and 2.2)
	Float64OneofRequestAndResponse *float64 `json:"float64_oneof_request_and_response,omitempty"`
	// float64 oneOf request only minimums (union of 1.1 and 2.2)
	Float64OneofRequest *float64 `json:"float64_oneof_request,omitempty"`
	// float64 oneOf response only minimums (union of 1.1 and 2.2)
	Float64OneofResponse *float64 `json:"float64_oneof_response,omitempty"`
	// float64 request and response minimum (both 12.12)
	Float64RequestAndResponse *float64 `json:"float64_request_and_response,omitempty"`
	// float64 request only minimum (1.1)
	Float64Request *float64 `json:"float64_request,omitempty"`
	// float64 response only minimum (2.2)
	Float64Response *float64 `json:"float64_response,omitempty"`
	// float64 request and response minimum (both 11.11) and maximum (both 12.12)
	Float64WithMaximum *float64 `json:"float64_with_maximum,omitempty"`
	// integer oneOf request and response minimums (union of 1 and 2)
	IntegerOneofRequestAndResponse *int64 `json:"integer_oneof_request_and_response,omitempty"`
	// integer oneOf request only minimums (union of 1 and 2)
	IntegerOneofRequest *int64 `json:"integer_oneof_request,omitempty"`
	// integer oneOf response only minimums (union of 1 and 2)
	IntegerOneofResponse *int64 `json:"integer_oneof_response,omitempty"`
	// integer request and response minimum (both 12)
	IntegerRequestAndResponse *int64 `json:"integer_request_and_response,omitempty"`
	// integer request only minimum (1)
	IntegerRequest *int64 `json:"integer_request,omitempty"`
	// integer response only minimum (2)
	IntegerResponse *int64 `json:"integer_response,omitempty"`
	// integer request and response minimum (both 11) and maximum (both 12)
	IntegerWithMaximum *int64 `json:"integer_with_maximum,omitempty"`
	// int32 oneOf request and response minimums (union of 1 and 2)
	Int32OneofRequestAndResponse *int `json:"int32_oneof_request_and_response,omitempty"`
	// int32 oneOf request only minimums (union of 1 and 2)
	Int32OneofRequest *int `json:"int32_oneof_request,omitempty"`
	// int32 oneOf response only minimums (union of 1 and 2)
	Int32OneofResponse *int `json:"int32_oneof_response,omitempty"`
	// int32 request and response minimum (both 12)
	Int32RequestAndResponse *int `json:"int32_request_and_response,omitempty"`
	// int32 request only minimum (1)
	Int32Request *int `json:"int32_request,omitempty"`
	// int32 response only minimum (2)
	Int32Response *int `json:"int32_response,omitempty"`
	// int32 request and response minimum (both 11) and maximum (both 12)
	Int32WithMaximum *int `json:"int32_with_maximum,omitempty"`
	// int64 oneOf request and response minimums (union of 1 and 2)
	Int64OneofRequestAndResponse *int64 `json:"int64_oneof_request_and_response,omitempty"`
	// int64 oneOf request only minimums (union of 1 and 2)
	Int64OneofRequest *int64 `json:"int64_oneof_request,omitempty"`
	// int64 oneOf response only minimums (union of 1 and 2)
	Int64OneofResponse *int64 `json:"int64_oneof_response,omitempty"`
	// int64 request and response minimum (both 12)
	Int64RequestAndResponse *int64 `json:"int64_request_and_response,omitempty"`
	// int64 request only minimum (1)
	Int64Request *int64 `json:"int64_request,omitempty"`
	// int64 response only minimum (2)
	Int64Response *int64 `json:"int64_response,omitempty"`
	// int64 request and response minimum (both 11) and maximum (both 12)
	Int64WithMaximum *int64 `json:"int64_with_maximum,omitempty"`
	// number oneOf request and response minimums (union of 1.1 and 2.2)
	NumberOneofRequestAndResponse *float64 `json:"number_oneof_request_and_response,omitempty"`
	// number oneOf request only minimums (union of 1.1 and 2.2)
	NumberOneofRequest *float64 `json:"number_oneof_request,omitempty"`
	// number oneOf response only minimums (union of 1.1 and 2.2)
	NumberOneofResponse *float64 `json:"number_oneof_response,omitempty"`
	// number request and response minimum (both 12.12)
	NumberRequestAndResponse *float64 `json:"number_request_and_response,omitempty"`
	// number request only minimum (1.1)
	NumberRequest *float64 `json:"number_request,omitempty"`
	// number response only minimum (2.2)
	NumberResponse *float64 `json:"number_response,omitempty"`
	// number request and response minimum (both 11.11) and maximum (both 12.12)
	NumberWithMaximum *float64 `json:"number_with_maximum,omitempty"`
}

func (o *OASMinimumRequest) GetFloat32OneofRequestAndResponse() *float32 {
	if o == nil {
		return nil
	}
	return o.Float32OneofRequestAndResponse
}

func (o *OASMinimumRequest) GetFloat32OneofRequest() *float32 {
	if o == nil {
		return nil
	}
	return o.Float32OneofRequest
}

func (o *OASMinimumRequest) GetFloat32OneofResponse() *float32 {
	if o == nil {
		return nil
	}
	return o.Float32OneofResponse
}

func (o *OASMinimumRequest) GetFloat32RequestAndResponse() *float32 {
	if o == nil {
		return nil
	}
	return o.Float32RequestAndResponse
}

func (o *OASMinimumRequest) GetFloat32Request() *float32 {
	if o == nil {
		return nil
	}
	return o.Float32Request
}

func (o *OASMinimumRequest) GetFloat32Response() *float32 {
	if o == nil {
		return nil
	}
	return o.Float32Response
}

func (o *OASMinimumRequest) GetFloat32WithMaximum() *float32 {
	if o == nil {
		return nil
	}
	return o.Float32WithMaximum
}

func (o *OASMinimumRequest) GetFloat64OneofRequestAndResponse() *float64 {
	if o == nil {
		return nil
	}
	return o.Float64OneofRequestAndResponse
}

func (o *OASMinimumRequest) GetFloat64OneofRequest() *float64 {
	if o == nil {
		return nil
	}
	return o.Float64OneofRequest
}

func (o *OASMinimumRequest) GetFloat64OneofResponse() *float64 {
	if o == nil {
		return nil
	}
	return o.Float64OneofResponse
}

func (o *OASMinimumRequest) GetFloat64RequestAndResponse() *float64 {
	if o == nil {
		return nil
	}
	return o.Float64RequestAndResponse
}

func (o *OASMinimumRequest) GetFloat64Request() *float64 {
	if o == nil {
		return nil
	}
	return o.Float64Request
}

func (o *OASMinimumRequest) GetFloat64Response() *float64 {
	if o == nil {
		return nil
	}
	return o.Float64Response
}

func (o *OASMinimumRequest) GetFloat64WithMaximum() *float64 {
	if o == nil {
		return nil
	}
	return o.Float64WithMaximum
}

func (o *OASMinimumRequest) GetIntegerOneofRequestAndResponse() *int64 {
	if o == nil {
		return nil
	}
	return o.IntegerOneofRequestAndResponse
}

func (o *OASMinimumRequest) GetIntegerOneofRequest() *int64 {
	if o == nil {
		return nil
	}
	return o.IntegerOneofRequest
}

func (o *OASMinimumRequest) GetIntegerOneofResponse() *int64 {
	if o == nil {
		return nil
	}
	return o.IntegerOneofResponse
}

func (o *OASMinimumRequest) GetIntegerRequestAndResponse() *int64 {
	if o == nil {
		return nil
	}
	return o.IntegerRequestAndResponse
}

func (o *OASMinimumRequest) GetIntegerRequest() *int64 {
	if o == nil {
		return nil
	}
	return o.IntegerRequest
}

func (o *OASMinimumRequest) GetIntegerResponse() *int64 {
	if o == nil {
		return nil
	}
	return o.IntegerResponse
}

func (o *OASMinimumRequest) GetIntegerWithMaximum() *int64 {
	if o == nil {
		return nil
	}
	return o.IntegerWithMaximum
}

func (o *OASMinimumRequest) GetInt32OneofRequestAndResponse() *int {
	if o == nil {
		return nil
	}
	return o.Int32OneofRequestAndResponse
}

func (o *OASMinimumRequest) GetInt32OneofRequest() *int {
	if o == nil {
		return nil
	}
	return o.Int32OneofRequest
}

func (o *OASMinimumRequest) GetInt32OneofResponse() *int {
	if o == nil {
		return nil
	}
	return o.Int32OneofResponse
}

func (o *OASMinimumRequest) GetInt32RequestAndResponse() *int {
	if o == nil {
		return nil
	}
	return o.Int32RequestAndResponse
}

func (o *OASMinimumRequest) GetInt32Request() *int {
	if o == nil {
		return nil
	}
	return o.Int32Request
}

func (o *OASMinimumRequest) GetInt32Response() *int {
	if o == nil {
		return nil
	}
	return o.Int32Response
}

func (o *OASMinimumRequest) GetInt32WithMaximum() *int {
	if o == nil {
		return nil
	}
	return o.Int32WithMaximum
}

func (o *OASMinimumRequest) GetInt64OneofRequestAndResponse() *int64 {
	if o == nil {
		return nil
	}
	return o.Int64OneofRequestAndResponse
}

func (o *OASMinimumRequest) GetInt64OneofRequest() *int64 {
	if o == nil {
		return nil
	}
	return o.Int64OneofRequest
}

func (o *OASMinimumRequest) GetInt64OneofResponse() *int64 {
	if o == nil {
		return nil
	}
	return o.Int64OneofResponse
}

func (o *OASMinimumRequest) GetInt64RequestAndResponse() *int64 {
	if o == nil {
		return nil
	}
	return o.Int64RequestAndResponse
}

func (o *OASMinimumRequest) GetInt64Request() *int64 {
	if o == nil {
		return nil
	}
	return o.Int64Request
}

func (o *OASMinimumRequest) GetInt64Response() *int64 {
	if o == nil {
		return nil
	}
	return o.Int64Response
}

func (o *OASMinimumRequest) GetInt64WithMaximum() *int64 {
	if o == nil {
		return nil
	}
	return o.Int64WithMaximum
}

func (o *OASMinimumRequest) GetNumberOneofRequestAndResponse() *float64 {
	if o == nil {
		return nil
	}
	return o.NumberOneofRequestAndResponse
}

func (o *OASMinimumRequest) GetNumberOneofRequest() *float64 {
	if o == nil {
		return nil
	}
	return o.NumberOneofRequest
}

func (o *OASMinimumRequest) GetNumberOneofResponse() *float64 {
	if o == nil {
		return nil
	}
	return o.NumberOneofResponse
}

func (o *OASMinimumRequest) GetNumberRequestAndResponse() *float64 {
	if o == nil {
		return nil
	}
	return o.NumberRequestAndResponse
}

func (o *OASMinimumRequest) GetNumberRequest() *float64 {
	if o == nil {
		return nil
	}
	return o.NumberRequest
}

func (o *OASMinimumRequest) GetNumberResponse() *float64 {
	if o == nil {
		return nil
	}
	return o.NumberResponse
}

func (o *OASMinimumRequest) GetNumberWithMaximum() *float64 {
	if o == nil {
		return nil
	}
	return o.NumberWithMaximum
}
