// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/internal/utils"
)

type OASOneOfDiscriminatorObjectNumber struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	discriminator string   `const:"number" json:"discriminator"`
	ObjectNumber  *float64 `json:"object_number,omitempty"`
}

func (o OASOneOfDiscriminatorObjectNumber) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OASOneOfDiscriminatorObjectNumber) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OASOneOfDiscriminatorObjectNumber) GetDiscriminator() string {
	return "number"
}

func (o *OASOneOfDiscriminatorObjectNumber) GetObjectNumber() *float64 {
	if o == nil {
		return nil
	}
	return o.ObjectNumber
}
