// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/hashicorp/terraform-provider-testing/internal/sdk/internal/utils"
)

type OASOneOfDiscriminatorObjectAllOf struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	discriminator string   `const:"allOf" json:"discriminator"`
	ObjectString  *string  `json:"object_string,omitempty"`
	ObjectNumber  *float64 `json:"object_number,omitempty"`
}

func (o OASOneOfDiscriminatorObjectAllOf) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OASOneOfDiscriminatorObjectAllOf) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OASOneOfDiscriminatorObjectAllOf) GetDiscriminator() string {
	return "allOf"
}

func (o *OASOneOfDiscriminatorObjectAllOf) GetObjectString() *string {
	if o == nil {
		return nil
	}
	return o.ObjectString
}

func (o *OASOneOfDiscriminatorObjectAllOf) GetObjectNumber() *float64 {
	if o == nil {
		return nil
	}
	return o.ObjectNumber
}
