// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ParametersDeepObjectResponse struct {
	ID *string `json:"id,omitempty"`
}

func (p *ParametersDeepObjectResponse) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}
