// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ParametersDeepObjectLevel3 struct {
	BooleanLevel3    *bool    `queryParam:"name=boolean_level_3"`
	IntegerLevel3    *int64   `queryParam:"name=integer_level_3"`
	ListStringLevel3 []string `queryParam:"name=list_string_level_3"`
	StringLevel3     *string  `queryParam:"name=string_level_3"`
}

func (p *ParametersDeepObjectLevel3) GetBooleanLevel3() *bool {
	if p == nil {
		return nil
	}
	return p.BooleanLevel3
}

func (p *ParametersDeepObjectLevel3) GetIntegerLevel3() *int64 {
	if p == nil {
		return nil
	}
	return p.IntegerLevel3
}

func (p *ParametersDeepObjectLevel3) GetListStringLevel3() []string {
	if p == nil {
		return nil
	}
	return p.ListStringLevel3
}

func (p *ParametersDeepObjectLevel3) GetStringLevel3() *string {
	if p == nil {
		return nil
	}
	return p.StringLevel3
}

// #region class-body-parametersdeepobjectlevel3
// #endregion class-body-parametersdeepobjectlevel3
