// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SchemeOperationCustom struct {
	// Custom operation security scheme key
	CustomOperationKey string `json:"custom_operation_key" security:"name=custom_operation_key"`
	// Custom operation security scheme secret
	CustomOperationSecret string `json:"custom_operation_secret" security:"name=custom_operation_secret"`
}

func (s *SchemeOperationCustom) GetCustomOperationKey() string {
	if s == nil {
		return ""
	}
	return s.CustomOperationKey
}

func (s *SchemeOperationCustom) GetCustomOperationSecret() string {
	if s == nil {
		return ""
	}
	return s.CustomOperationSecret
}
