// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Security struct {
	APIKey            *string                  `security:"scheme,type=apiKey,subtype=header,name=X-Api-Key"`
	Basic             *SchemeBasic             `security:"scheme,type=http,subtype=basic"`
	Bearer            *string                  `security:"scheme,type=http,subtype=bearer,name=Authorization"`
	ClientCredentials *SchemeClientCredentials `security:"scheme,type=oauth2,subtype=client_credentials"`
	Custom            *SchemeCustom            `security:"scheme,type=http,subtype=custom"`
}

func (s *Security) GetAPIKey() *string {
	if s == nil {
		return nil
	}
	return s.APIKey
}

func (s *Security) GetBasic() *SchemeBasic {
	if s == nil {
		return nil
	}
	return s.Basic
}

func (s *Security) GetBearer() *string {
	if s == nil {
		return nil
	}
	return s.Bearer
}

func (s *Security) GetClientCredentials() *SchemeClientCredentials {
	if s == nil {
		return nil
	}
	return s.ClientCredentials
}

func (s *Security) GetCustom() *SchemeCustom {
	if s == nil {
		return nil
	}
	return s.Custom
}
