// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SetNestedInline struct {
	InlineString *string `json:"inline_string,omitempty"`
}

func (s *SetNestedInline) GetInlineString() *string {
	if s == nil {
		return nil
	}
	return s.InlineString
}
