// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type XEntityOperationCloseMultipleOpClose1Request struct {
	StringRequestAndResponse *string `json:"string_request_and_response,omitempty"`
}

func (x *XEntityOperationCloseMultipleOpClose1Request) GetStringRequestAndResponse() *string {
	if x == nil {
		return nil
	}
	return x.StringRequestAndResponse
}

// #region class-body-xentityoperationclosemultipleopclose1request
// #endregion class-body-xentityoperationclosemultipleopclose1request
