// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type XSoftDeletePropertyRequest struct {
	// Non x-speakeasy-soft-delete-property that should remain configurable.
	NonSoftDeletePropertyRequestOnly *string `json:"non_soft_delete_property_request_only,omitempty"`
	// Non x-speakeasy-soft-delete-property that should remain configurable.
	NonSoftDeletePropertyRequestAndResponse *string `json:"non_soft_delete_property_request_and_response,omitempty"`
}

func (x *XSoftDeletePropertyRequest) GetNonSoftDeletePropertyRequestOnly() *string {
	if x == nil {
		return nil
	}
	return x.NonSoftDeletePropertyRequestOnly
}

func (x *XSoftDeletePropertyRequest) GetNonSoftDeletePropertyRequestAndResponse() *string {
	if x == nil {
		return nil
	}
	return x.NonSoftDeletePropertyRequestAndResponse
}
