// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type XWrappedAttributeRequest struct {
	NonWrappedString *string `json:"non_wrapped_string,omitempty"`
}

func (x *XWrappedAttributeRequest) GetNonWrappedString() *string {
	if x == nil {
		return nil
	}
	return x.NonWrappedString
}
