// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Aloof struct {
	Bool *bool  `json:"bool,omitzero"`
	Int  *int64 `json:"int,omitzero"`
}

func (a *Aloof) GetBool() *bool {
	if a == nil {
		return nil
	}
	return a.Bool
}

func (a *Aloof) GetInt() *int64 {
	if a == nil {
		return nil
	}
	return a.Int
}
