// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"openapi/internal/sdk/optionalnullable"
	"openapi/internal/sdk/sdkinternal/utils"
	"openapi/internal/sdk/types"
)

type Test2Response struct {
	Test2 optionalnullable.OptionalNullable[string] `json:"test2,omitzero"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	someConst *string `const:"someConstValue" json:"someConst,omitzero"`
	// A required but nullable field to verify error accessor type matching for nullable-only fields
	RequiredNullableField *string `json:"requiredNullableField"`
}

func (t Test2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Test2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Test2Response) GetTest2() optionalnullable.OptionalNullable[string] {
	if t == nil {
		return nil
	}
	return t.Test2
}

func (t *Test2Response) GetSomeConst() *string {
	return types.Pointer("someConstValue")
}

func (t *Test2Response) GetRequiredNullableField() *string {
	if t == nil {
		return nil
	}
	return t.RequiredNullableField
}

// #region class-body-test2response
// #endregion class-body-test2response
