// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

//go:build !windows

package tests

import (
	"bytes"
	"context"
	"io"
	"os"
	"strings"
	"syscall"
	"testing"
	"time"

	"github.com/creack/pty"
	"github.com/spf13/cobra"
	"github.com/stretchr/testify/require"

	"openapi/internal/config"
	"openapi/internal/output"
)

func newProgressTestCommand(t *testing.T, ctx context.Context) (*cobra.Command, int, *os.File) {
	t.Helper()

	master, slave, err := pty.Open()
	require.NoError(t, err)
	fd := int(master.Fd())
	require.NoError(t, syscall.SetNonblock(fd, true))
	t.Setenv("TERM", "xterm-256color")
	config.Reset()
	output.ResetAgentMode()
	output.ResetPreparsedRendering()
	t.Cleanup(config.Reset)
	t.Cleanup(output.ResetAgentMode)
	t.Cleanup(output.ResetPreparsedRendering)
	t.Cleanup(func() {
		_ = master.Close()
		_ = slave.Close()
	})

	root := &cobra.Command{Use: "fixture"}
	root.PersistentFlags().String("output-format", "pretty", "")
	root.PersistentFlags().String("jq", "", "")
	root.PersistentFlags().Bool("agent-mode", false, "")
	root.PersistentFlags().Bool("debug", false, "")
	root.PersistentFlags().Bool("dry-run", false, "")
	root.PersistentFlags().Bool("interactive", false, "")
	root.PersistentFlags().Bool("no-interactive", false, "")
	cmd := &cobra.Command{Use: "request"}
	root.AddCommand(cmd)
	cmd.SetOut(slave)
	cmd.SetErr(slave)
	cmd.SetContext(ctx)
	_ = cmd.InheritedFlags()
	return cmd, fd, slave
}

func readProgressOutput(fd int, wait time.Duration) string {
	deadline := time.Now().Add(wait)
	var out bytes.Buffer
	buf := make([]byte, 256)
	for time.Now().Before(deadline) {
		n, err := syscall.Read(fd, buf)
		if n > 0 {
			_, _ = out.Write(buf[:n])
		}
		if err != nil && err != syscall.EAGAIN && err != syscall.EINTR {
			break
		}
		time.Sleep(time.Millisecond)
	}
	return out.String()
}

func TestRequestProgressWaitsBeforeRenderingAndClearsOnStop(t *testing.T) {
	cmd, master, _ := newProgressTestCommand(t, context.Background())
	stop := output.StartRequestProgress(cmd)

	time.Sleep(100 * time.Millisecond)
	require.Empty(t, readProgressOutput(master, 20*time.Millisecond))

	time.Sleep(200 * time.Millisecond)
	visible := readProgressOutput(master, 50*time.Millisecond)
	require.Contains(t, visible, "fixture request")
	require.True(t, strings.ContainsAny(visible, "|/-\\"), "progress should use an ASCII animation frame")

	stop()
	cleared := readProgressOutput(master, 50*time.Millisecond)
	require.Contains(t, cleared, "\r\x1b[2K")

	stop()
	require.Empty(t, readProgressOutput(master, 20*time.Millisecond))
}

func TestRequestProgressFastCompletionIsSilent(t *testing.T) {
	cmd, master, _ := newProgressTestCommand(t, context.Background())
	stop := output.StartRequestProgress(cmd)
	stop()
	require.Empty(t, readProgressOutput(master, 300*time.Millisecond))
}

func TestRequestProgressClearsBeforeRequestError(t *testing.T) {
	cmd, master, _ := newProgressTestCommand(t, context.Background())
	stop := output.StartRequestProgress(cmd)
	time.Sleep(300 * time.Millisecond)
	stop()
	_, err := io.WriteString(cmd.ErrOrStderr(), "request failed\n")
	require.NoError(t, err)

	got := readProgressOutput(master, 100*time.Millisecond)
	clearAt := bytes.LastIndex([]byte(got), []byte("\r\x1b[2K"))
	errorAt := bytes.Index([]byte(got), []byte("request failed"))
	require.NotEqual(t, -1, clearAt)
	require.NotEqual(t, -1, errorAt)
	require.Less(t, clearAt, errorAt)
}

func TestRequestProgressContextCancellationClears(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cmd, master, _ := newProgressTestCommand(t, ctx)
	stop := output.StartRequestProgress(cmd)
	time.Sleep(300 * time.Millisecond)
	cancel()

	got := readProgressOutput(master, time.Second)
	require.Contains(t, got, "\r\x1b[2K")
	stop()
}

func TestRequestProgressSuppressionFlags(t *testing.T) {
	for name, set := range map[string]func(*cobra.Command) error{

		"machine output": func(cmd *cobra.Command) error {
			return cmd.InheritedFlags().Set("output-format", "json")
		},
		"jq": func(cmd *cobra.Command) error {
			return cmd.InheritedFlags().Set("jq", ".")
		},
		"agent mode": func(cmd *cobra.Command) error {
			return cmd.InheritedFlags().Set("agent-mode", "true")
		},
		"debug": func(cmd *cobra.Command) error {
			return cmd.InheritedFlags().Set("debug", "true")
		},
		"dry run": func(cmd *cobra.Command) error {
			return cmd.InheritedFlags().Set("dry-run", "true")
		},
		"no interactive": func(cmd *cobra.Command) error {
			return cmd.InheritedFlags().Set("no-interactive", "true")
		},
		"explicit interactive false": func(cmd *cobra.Command) error {
			return cmd.InheritedFlags().Set("interactive", "false")
		},
	} {
		t.Run(name, func(t *testing.T) {
			cmd, master, _ := newProgressTestCommand(t, context.Background())
			require.NoError(t, set(cmd))
			stop := output.StartRequestProgress(cmd)
			time.Sleep(300 * time.Millisecond)
			stop()
			require.Empty(t, readProgressOutput(master, 50*time.Millisecond))
		})
	}
}

func TestRequestProgressDumbTerminalIsSilent(t *testing.T) {
	cmd, master, _ := newProgressTestCommand(t, context.Background())
	t.Setenv("TERM", "dumb")
	stop := output.StartRequestProgress(cmd)
	time.Sleep(300 * time.Millisecond)
	stop()
	require.Empty(t, readProgressOutput(master, 50*time.Millisecond))
}

func TestRequestProgressRedirectedWriterIsSilent(t *testing.T) {
	t.Run("stderr redirected", func(t *testing.T) {
		cmd, master, _ := newProgressTestCommand(t, context.Background())
		var redirected bytes.Buffer
		cmd.SetErr(&redirected)
		stop := output.StartRequestProgress(cmd)
		time.Sleep(300 * time.Millisecond)
		stop()
		require.Empty(t, readProgressOutput(master, 50*time.Millisecond))
		require.Empty(t, redirected.String())
	})
	t.Run("stdout redirected", func(t *testing.T) {
		cmd, master, slave := newProgressTestCommand(t, context.Background())
		var redirected bytes.Buffer
		cmd.SetOut(&redirected)
		stop := output.StartRequestProgress(cmd)
		time.Sleep(300 * time.Millisecond)
		stop()
		require.Empty(t, readProgressOutput(master, 50*time.Millisecond))
		require.Empty(t, redirected.String())
		_ = slave.Close()
	})
}
func TestRequestProgressDefaultInteractiveFalseDoesNotSuppress(t *testing.T) {
	cmd, master, _ := newProgressTestCommand(t, context.Background())
	stop := output.StartRequestProgress(cmd)
	time.Sleep(300 * time.Millisecond)
	stop()
	require.Contains(t, readProgressOutput(master, 50*time.Millisecond), "fixture request")
}
