// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package webhooks

import (
	"encoding/json"
	"fmt"
	"net/http"
)

type PaymentUpdatedType string

const (
	PaymentUpdatedTypePaymentUpdated PaymentUpdatedType = "payment.updated"
)

func (e PaymentUpdatedType) ToPointer() *PaymentUpdatedType {
	return &e
}
func (e *PaymentUpdatedType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "payment.updated":
		*e = PaymentUpdatedType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentUpdatedType: %v", v)
	}
}

type PaymentUpdatedRequest struct {
	// Payment amount
	Amount string             `json:"amount"`
	Type   PaymentUpdatedType `json:"type"`
}

func (p *PaymentUpdatedRequest) GetAmount() string {
	if p == nil {
		return ""
	}
	return p.Amount
}

func (p *PaymentUpdatedRequest) GetType() PaymentUpdatedType {
	if p == nil {
		return PaymentUpdatedType("")
	}
	return p.Type
}

type PaymentUpdatedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PaymentUpdatedResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PaymentUpdatedResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PaymentUpdatedResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}
