// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

type OptionalInlineObjectResponseOnlyUnion struct {
	OptionalInlineObjectResponseOnly1 *OptionalInlineObjectResponseOnly1 `queryParam:"inline" tfsdk:"optional_inline_object_response_only1"`
	OptionalInlineObjectResponseOnly2 *OptionalInlineObjectResponseOnly2 `queryParam:"inline" tfsdk:"optional_inline_object_response_only2"`
}
