// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type SetSetOneofNumberString struct {
	Number types.Float64 `queryParam:"inline" tfsdk:"number"`
	Str    types.String  `queryParam:"inline" tfsdk:"str"`
}
