//@ts-ignore
const supportedFeatures = {
  core: "0.2.14",
  globalSecurity: "0.1.4",
  methodSecurity: "0.1.3",
  globalServerURLs: "0.1.2",
  methodServerURLs: "0.1.1",
  globals: "0.1.0",
  enums: "0.1.0",
  serverIDs: "0.1.0",
  nameOverrides: "0.1.2",
  includes: "0.1.0",
  docs: "0.3.3",
  examples: "0.1.3",
  groups: "0.1.1",
  ignores: "0.1.0",
  typeOverrides: "0.1.0",
  errors: "0.2.0",
  acceptHeaders: "0.1.0",
  multiLevelTagging: "0.1.0",
  bigint: "0.1.0",
  decimal: "0.1.0",
  constsAndDefaults: "0.1.2",
  oauth2ClientCredentials: "0.1.5",
  hiddenGlobals: "0.1.0",
  getRequestBodies: "0.1.0",
  modelNamespaces: "0.1.0",
};

const ignoredFeatures = [
  "downloadStreams",
  "additionalProperties",
  "urlBasedPagination",
  "webhooks",
  "responseFormat",
  "flattening",
  "inputOutputModels",
  "deprecations",
  "retries",
  "pagination",
  "devContainers",
  "tests",
  "serverEvents",
  "callbacks",
  "unions",
  "disallowCircularRefs",
  "tagBasedOrdering",
  "sets",
  "globalSecurityCallbacks",
  "additionalDependencies",
  "globalSecurityFlattening",
  "intellisenseMarkdownSupport",
  "sdkHooks",
  "tests",
  "uploadStreams",
  "urlBasedPagination",
  "reactQueryHooks",
];

//@ts-ignore
function isFeatureSupported(feature: string): boolean {
  return feature in supportedFeatures;
}

//@ts-ignore
function allSupportedFeatures(): string[] {
  const allFeatures = Object.keys(supportedFeatures);
  return allFeatures.filter((feature) => !isFeatureIgnored(feature));
}

//@ts-ignore
function isFeatureIgnored(feature: string): boolean {
  return ignoredFeatures.includes(feature);
}

//@ts-ignore
function getStaticallyUsedFeatures(): string[] {
  return [];
}

//@ts-ignore
function isTestSkipped(test: string): boolean {
  return false;
}

//@ts-ignore
function getFeatureVersion(feature: string): string {
  const version = supportedFeatures[feature];
  if (!version) {
    throw new Error(`Feature ${feature} is not supported in Postman`);
  }
  return version;
}

//@ts-ignore
function getAutoGeneratedHeader(
  generatedId: string,
  config: Record<string, any>,
): string {
  return "";
}
