// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package singlebar

import (
	"github.com/spf13/cobra"
	"openapi/internal/usage"
)

func InitSingleBarRoot(parent *cobra.Command) error {
	var SingleBarCmd = &cobra.Command{
		Use:         "single-bar",
		Short:       "Operations for single-bar",
		Long:        "Operations for single-bar",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"speakeasy_cli_group": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"sb"},
	}

	if err := initGetSingleNamespaceBarPetCmd(SingleBarCmd); err != nil {
		return err
	}

	parent.AddCommand(SingleBarCmd)
	return nil
}
