/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  Pet as Foo_Pet,
  Pet$zodSchema as Foo_Pet$zodSchema,
} from "./foo/pet.js";

export type CreateSingleNamespaceFooPetResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Pet?: Foo_Pet | undefined;
};

export const CreateSingleNamespaceFooPetResponse$zodSchema: z.ZodType<
  CreateSingleNamespaceFooPetResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  Pet: Foo_Pet$zodSchema.optional().describe("Created"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
});
