/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/httpclienterrors.js";
import * as models from "../models/index.js";
import { ResponseValidationError } from "../models/responsevalidationerror.js";
import { SDKBaseError } from "../models/sdkbaseerror.js";
import { SDKValidationError } from "../models/sdkvalidationerror.js";
import { useSDKContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";
import {
  buildGetDuplicateExportCollisionQuery,
  GetDuplicateExportCollisionQueryData,
  prefetchGetDuplicateExportCollision,
  queryKeyGetDuplicateExportCollision,
} from "./getDuplicateExportCollision.core.js";
export {
  buildGetDuplicateExportCollisionQuery,
  type GetDuplicateExportCollisionQueryData,
  prefetchGetDuplicateExportCollision,
  queryKeyGetDuplicateExportCollision,
};

export type GetDuplicateExportCollisionQueryError =
  | models.RequestTimeoutError
  | SDKBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Tests that a spec-defined error type colliding with a built-in SDK error name does not cause TS2308
 */
export function useGetDuplicateExportCollision(
  options?: QueryHookOptions<
    GetDuplicateExportCollisionQueryData,
    GetDuplicateExportCollisionQueryError
  >,
): UseQueryResult<
  GetDuplicateExportCollisionQueryData,
  GetDuplicateExportCollisionQueryError
> {
  const client = useSDKContext();
  return useQuery({
    ...buildGetDuplicateExportCollisionQuery(
      client,
      options,
    ),
    ...options,
  });
}

/**
 * Tests that a spec-defined error type colliding with a built-in SDK error name does not cause TS2308
 */
export function useGetDuplicateExportCollisionSuspense(
  options?: SuspenseQueryHookOptions<
    GetDuplicateExportCollisionQueryData,
    GetDuplicateExportCollisionQueryError
  >,
): UseSuspenseQueryResult<
  GetDuplicateExportCollisionQueryData,
  GetDuplicateExportCollisionQueryError
> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildGetDuplicateExportCollisionQuery(
      client,
      options,
    ),
    ...options,
  });
}

export function setGetDuplicateExportCollisionData(
  client: QueryClient,
  data: GetDuplicateExportCollisionQueryData,
): GetDuplicateExportCollisionQueryData | undefined {
  const key = queryKeyGetDuplicateExportCollision();

  return client.setQueryData<GetDuplicateExportCollisionQueryData>(key, data);
}

export function invalidateAllGetDuplicateExportCollision(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["openapi", "getDuplicateExportCollision"],
  });
}
