/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/httpclienterrors.js";
import { ResponseValidationError } from "../models/responsevalidationerror.js";
import { SDKBaseError } from "../models/sdkbaseerror.js";
import { SDKValidationError } from "../models/sdkvalidationerror.js";
import { useSDKContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";
import {
  buildNamespaceTestsConflictsGetNamespaceConflictQuery,
  NamespaceTestsConflictsGetNamespaceConflictQueryData,
  prefetchNamespaceTestsConflictsGetNamespaceConflict,
  queryKeyNamespaceTestsConflictsGetNamespaceConflict,
} from "./namespaceTestsConflictsGetNamespaceConflict.core.js";
export {
  buildNamespaceTestsConflictsGetNamespaceConflictQuery,
  type NamespaceTestsConflictsGetNamespaceConflictQueryData,
  prefetchNamespaceTestsConflictsGetNamespaceConflict,
  queryKeyNamespaceTestsConflictsGetNamespaceConflict,
};

export type NamespaceTestsConflictsGetNamespaceConflictQueryError =
  | SDKBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get Namespace Conflict Test
 *
 * @remarks
 * This endpoint tests the x-speakeasy-model-namespace extension by returning
 * a model that references two different Pet types from different namespaces.
 * The SDK should properly import and alias both Pet types.
 */
export function useNamespaceTestsConflictsGetNamespaceConflict(
  options?: QueryHookOptions<
    NamespaceTestsConflictsGetNamespaceConflictQueryData,
    NamespaceTestsConflictsGetNamespaceConflictQueryError
  >,
): UseQueryResult<
  NamespaceTestsConflictsGetNamespaceConflictQueryData,
  NamespaceTestsConflictsGetNamespaceConflictQueryError
> {
  const client = useSDKContext();
  return useQuery({
    ...buildNamespaceTestsConflictsGetNamespaceConflictQuery(
      client,
      options,
    ),
    ...options,
  });
}

/**
 * Get Namespace Conflict Test
 *
 * @remarks
 * This endpoint tests the x-speakeasy-model-namespace extension by returning
 * a model that references two different Pet types from different namespaces.
 * The SDK should properly import and alias both Pet types.
 */
export function useNamespaceTestsConflictsGetNamespaceConflictSuspense(
  options?: SuspenseQueryHookOptions<
    NamespaceTestsConflictsGetNamespaceConflictQueryData,
    NamespaceTestsConflictsGetNamespaceConflictQueryError
  >,
): UseSuspenseQueryResult<
  NamespaceTestsConflictsGetNamespaceConflictQueryData,
  NamespaceTestsConflictsGetNamespaceConflictQueryError
> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildNamespaceTestsConflictsGetNamespaceConflictQuery(
      client,
      options,
    ),
    ...options,
  });
}

export function setNamespaceTestsConflictsGetNamespaceConflictData(
  client: QueryClient,
  data: NamespaceTestsConflictsGetNamespaceConflictQueryData,
): NamespaceTestsConflictsGetNamespaceConflictQueryData | undefined {
  const key = queryKeyNamespaceTestsConflictsGetNamespaceConflict();

  return client.setQueryData<
    NamespaceTestsConflictsGetNamespaceConflictQueryData
  >(key, data);
}

export function invalidateAllNamespaceTestsConflictsGetNamespaceConflict(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["openapi", "conflicts", "getNamespaceConflict"],
  });
}
