/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/httpclienterrors.js";
import { ResponseValidationError } from "../models/responsevalidationerror.js";
import { SDKBaseError } from "../models/sdkbaseerror.js";
import { SDKValidationError } from "../models/sdkvalidationerror.js";
import { useSDKContext } from "./_context.js";
import { QueryHookOptions, SuspenseQueryHookOptions } from "./_types.js";
import {
  buildNamespaceTestsTypesGetNamespaceOrganizationQuery,
  NamespaceTestsTypesGetNamespaceOrganizationQueryData,
  prefetchNamespaceTestsTypesGetNamespaceOrganization,
  queryKeyNamespaceTestsTypesGetNamespaceOrganization,
} from "./namespaceTestsTypesGetNamespaceOrganization.core.js";
export {
  buildNamespaceTestsTypesGetNamespaceOrganizationQuery,
  type NamespaceTestsTypesGetNamespaceOrganizationQueryData,
  prefetchNamespaceTestsTypesGetNamespaceOrganization,
  queryKeyNamespaceTestsTypesGetNamespaceOrganization,
};

export type NamespaceTestsTypesGetNamespaceOrganizationQueryError =
  | SDKBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get Namespace Organization (Nested Inline Schemas)
 *
 * @remarks
 * This endpoint tests nested inline object schemas in a custom namespace.
 * The organization model contains nested address and department types that
 * should inherit the foo namespace.
 */
export function useNamespaceTestsTypesGetNamespaceOrganization(
  options?: QueryHookOptions<
    NamespaceTestsTypesGetNamespaceOrganizationQueryData,
    NamespaceTestsTypesGetNamespaceOrganizationQueryError
  >,
): UseQueryResult<
  NamespaceTestsTypesGetNamespaceOrganizationQueryData,
  NamespaceTestsTypesGetNamespaceOrganizationQueryError
> {
  const client = useSDKContext();
  return useQuery({
    ...buildNamespaceTestsTypesGetNamespaceOrganizationQuery(
      client,
      options,
    ),
    ...options,
  });
}

/**
 * Get Namespace Organization (Nested Inline Schemas)
 *
 * @remarks
 * This endpoint tests nested inline object schemas in a custom namespace.
 * The organization model contains nested address and department types that
 * should inherit the foo namespace.
 */
export function useNamespaceTestsTypesGetNamespaceOrganizationSuspense(
  options?: SuspenseQueryHookOptions<
    NamespaceTestsTypesGetNamespaceOrganizationQueryData,
    NamespaceTestsTypesGetNamespaceOrganizationQueryError
  >,
): UseSuspenseQueryResult<
  NamespaceTestsTypesGetNamespaceOrganizationQueryData,
  NamespaceTestsTypesGetNamespaceOrganizationQueryError
> {
  const client = useSDKContext();
  return useSuspenseQuery({
    ...buildNamespaceTestsTypesGetNamespaceOrganizationQuery(
      client,
      options,
    ),
    ...options,
  });
}

export function setNamespaceTestsTypesGetNamespaceOrganizationData(
  client: QueryClient,
  data: NamespaceTestsTypesGetNamespaceOrganizationQueryData,
): NamespaceTestsTypesGetNamespaceOrganizationQueryData | undefined {
  const key = queryKeyNamespaceTestsTypesGetNamespaceOrganization();

  return client.setQueryData<
    NamespaceTestsTypesGetNamespaceOrganizationQueryData
  >(key, data);
}

export function invalidateAllNamespaceTestsTypesGetNamespaceOrganization(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["openapi", "types", "getNamespaceOrganization"],
  });
}
