/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { SDKCore } from "../core.js";
import { renderAsset, RenderAssetAcceptEnum } from "../funcs/renderAsset.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/httpclienterrors.js";
import * as models from "../models/index.js";
import { ResponseValidationError } from "../models/responsevalidationerror.js";
import { SDKBaseError } from "../models/sdkbaseerror.js";
import { SDKValidationError } from "../models/sdkvalidationerror.js";
import { unwrapAsync } from "../types/fp.js";
import { useSDKContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export { RenderAssetAcceptEnum } from "../funcs/renderAsset.js";

export type RenderAssetMutationVariables = {
  request: models.RenderAssetRequest;
  options?: RequestOptions & { acceptHeaderOverride?: RenderAssetAcceptEnum };
};

export type RenderAssetMutationData = models.RenderAssetResponse;

export type RenderAssetMutationError =
  | SDKBaseError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Render Asset
 *
 * @remarks
 * Render a media asset from a text prompt.
 */
export function useRenderAssetMutation(
  options?: MutationHookOptions<
    RenderAssetMutationData,
    RenderAssetMutationError,
    RenderAssetMutationVariables
  >,
): UseMutationResult<
  RenderAssetMutationData,
  RenderAssetMutationError,
  RenderAssetMutationVariables
> {
  const client = useSDKContext();
  return useMutation({
    ...buildRenderAssetMutation(client, options),
    ...options,
  });
}

export function mutationKeyRenderAsset(): MutationKey {
  return ["openapi", "renderAsset"];
}

export function buildRenderAssetMutation(
  client$: SDKCore,
  hookOptions?: RequestOptions & {
    acceptHeaderOverride?: RenderAssetAcceptEnum;
  },
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: RenderAssetMutationVariables,
  ) => Promise<RenderAssetMutationData>;
} {
  return {
    mutationKey: mutationKeyRenderAsset(),
    mutationFn: function renderAssetMutationFn({
      request,
      options,
    }): Promise<RenderAssetMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(renderAsset(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
