// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/usage"
	"strings"
)

func InitIntentRender(parent *cobra.Command) error {
	cmd := &cobra.Command{
		Use:     "render [prompt]",
		Short:   "Render an image asset to a file",
		Long:    "Render an image from a text prompt and write it to a file; stdout\ncarries the file path. Full request control: \"cli render-asset\".\n\nArguments:\n  <prompt>  Text prompt to render",
		Example: "  cli render \"a lighthouse at sunset\"",
		Args:    cobra.ArbitraryArgs,
		RunE:    runIntentRenderCmd,
		Annotations: map[string]string{
			"speakeasy_operation":            "renderAsset",
			flagutil.AnnotationWholeBodyFlag: "body",
			"speakeasy_strict_body_keys":     "true",
			"speakeasy_artifact":             "{\"pointer\":[{\"field\":\"steps\"},{\"wild\":true},{\"field\":\"content\"},{\"wild\":true}],\"kind\":\"image\",\"defaultPath\":\"render-{timestamp}-{rand}.{ext}\"}",
		},
	}
	flagutil.RegisterFlags(cmd, renderAssetCmdMeta)
	flagutil.SetMetaPromptOptional(cmd, renderAssetCmdMeta, false)
	flagutil.ClearBodyRequirements(cmd, renderAssetCmdMeta, "")
	_ = flagutil.OverridePromptRequirement(cmd, "prompt", false, false)
	cmd.Flags().String("body", "", "Request body as JSON (advanced; replaces intent arguments). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	if err := flagutil.AnnotateBodyFields(cmd, renderAssetCmdMeta, "", "body"); err != nil {
		return fmt.Errorf("annotate body fields for intent render: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	if err := interactive.Declare(cmd, interactive.CommandSpec{Args: []interactive.ArgSpec{
		{
			Name: "prompt", Summary: "Text prompt to render",
			Required: true, Variadic: true,
			BodyKey:     "prompt",
			SatisfiedBy: []string{"prompt", "body"},
		},
	}}); err != nil {
		return fmt.Errorf("declare interactive arguments for intent render: %w", err)
	}
	cmd.Flags().String("out", "", "Write the image to this file (or into this directory). Default: ./render-{timestamp}-{rand}.{ext}")
	_ = flagutil.AnnotatePromptFlag(cmd, "out", flagutil.PromptFlagSpec{
		PromptDirect: true,
		Label:        "Output file",
		Kind:         "string",
	})
	cmd.Flags().Bool("raw-response", false, "Print the raw API response instead of writing the image to a file")
	for _, sibling := range parent.Commands() {
		if sibling.Name() == cmd.Name() || sibling.HasAlias(cmd.Name()) {
			return fmt.Errorf("intent command %q collides with the name or alias of an existing %q command; rename the declared command", "render", sibling.Name())
		}
	}
	parent.AddCommand(cmd)
	return nil
}

var intentRenderPreset = flagutil.PresetMerge{
	Command: "render",
	Preset:  "{\"output_modalities\":[\"image\"]}",
	Escape:  "cli render-asset",
}

func runIntentRenderCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "renderAsset")
	}
	if flagutil.FlagChanged(cmd, "raw-response") && flagutil.FlagChanged(cmd, "out") {
		return flagutil.WithCLIValidation(fmt.Errorf("--raw-response prints the raw API response and cannot be combined with --out"))
	}
	bodySurfaces := []string{"body"}
	for _, surface := range bodySurfaces {
		if flagutil.FlagChanged(cmd, surface) {
			if err := flagutil.ResolveBodyFlag(cmd, surface); err != nil {
				return err
			}
		}
	}
	suppliedBodyFlag := ""
	if flagutil.FlagChanged(cmd, "body") {
		suppliedBodyFlag = "body"
	}
	bodySupplied := suppliedBodyFlag != ""
	if !bodySupplied {
		attached, err := flagutil.AttachStdinBody(cmd, "body")
		if err != nil {
			return err
		}
		bodySupplied = attached
	}
	if hint := flagutil.SpacedBoolValueHint(cmd, args); hint != "" && !client.IsJSONDryRun(cmd) && !output.IsMachineMode(cmd) {
		fmt.Fprintln(cmd.ErrOrStderr(), hint)
	}
	if bodySupplied {
		if flagutil.FlagChanged(cmd, "prompt") {
			if v, _ := flagutil.GetStringFlag(cmd, "prompt"); v == "" {
				return flagutil.WithCLIValidation(fmt.Errorf("--prompt must not be empty"))
			}
		}
		if len(args) > 0 {
			if err := flagutil.MergeInputIntoBody(cmd, suppliedBodyFlag, "prompt", "the <prompt> argument", strings.Join(args, " ")); err != nil {
				return flagutil.WithCLIValidation(err)
			}
		}
	}
	if len(args) == 0 && !bodySupplied && !flagutil.FlagChanged(cmd, "prompt") && !flagutil.FlagChanged(cmd, "body") {
		return output.UsageHelpError(cmd, fmt.Errorf("%s", "missing required argument <prompt> (or pass a full request with --body)"))
	}
	if !bodySupplied {
		body := map[string]any{}
		if err := json.Unmarshal([]byte(intentRenderPreset.Preset), &body); err != nil {
			return err
		}
		if len(args) == 0 && !flagutil.FlagChanged(cmd, "prompt") {
			return flagutil.WithCLIValidation(fmt.Errorf("missing required argument (or pass a full request with --body)"))
		}
		// An explicitly empty backing-flag value must not stand in for the
		// required positional — nor override a supplied one at the request
		// layer — and bypass required-string validation.
		if flagutil.FlagChanged(cmd, "prompt") {
			if v, _ := flagutil.GetStringFlag(cmd, "prompt"); v == "" {
				return flagutil.WithCLIValidation(fmt.Errorf("--prompt must not be empty"))
			}
		}
		if len(args) > 0 {
			body["prompt"] = strings.Join(args, " ")
		}
		encoded, err := json.Marshal(body)
		if err != nil {
			return err
		}
		if err := cmd.Flags().Set("body", string(encoded)); err != nil {
			return err
		}
	} else {
		for _, surface := range bodySurfaces {
			if !flagutil.FlagChanged(cmd, surface) {
				continue
			}
			raw, _ := flagutil.GetStringFlag(cmd, surface)
			merged, err := flagutil.MergePresetBody(raw, intentRenderPreset)
			if err != nil {
				return err
			}
			if err := cmd.Flags().Set(surface, merged); err != nil {
				return err
			}
		}
	}
	return runRenderAssetCmd(cmd, nil)
}
