// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"fmt"
	"github.com/spf13/cobra"
	"openapi/internal/client"
	"openapi/internal/flagutil"
	"openapi/internal/output"
	"openapi/internal/sdk"
	"openapi/internal/sdk/models/operations"
	"openapi/internal/usage"
)

var renderAssetCmdMeta = []flagutil.FlagMeta{
	{FlagName: "prompt", Shorthand: "p", FieldPath: "Prompt", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "output-modalities", FieldPath: "OutputModalities", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "list of values"},
}

// initRenderAssetCmd initializes the render-asset command.
func initRenderAssetCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "render-asset",
		Short:   "Render Asset",
		Long:    "Render a media asset from a text prompt.",
		Example: "  cli render-asset --prompt <value>",
		Args:    cobra.NoArgs,
		RunE:    runRenderAssetCmd,
		Aliases: []string{"ra"},
		Annotations: map[string]string{
			"speakeasy_operation": "renderAsset",
		},
	}
	flagutil.RegisterFlags(cmd, renderAssetCmdMeta)
	if err := flagutil.ValidateMeta[operations.RenderAssetRequest](renderAssetCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for render-asset: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin; @path reads a file, @- reads stdin to EOF. Use --schema to print the exact JSON Schema.")
	_ = flagutil.AnnotatePromptFlag(cmd, "body", flagutil.PromptFlagSpec{Kind: "json", BodyFlag: true})
	cmd.Annotations[flagutil.AnnotationWholeBodyFlag] = "body"
	if err := flagutil.AnnotateBodyFields(cmd, renderAssetCmdMeta, "", "body"); err != nil {
		return fmt.Errorf("annotate body fields for render-asset: %w", err)
	}
	cmd.Flags().Bool("schema", false, "Print the exact JSON Schema of the request body and exit")
	_ = flagutil.AnnotatePromptFlag(cmd, "schema", flagutil.PromptFlagSpec{Kind: "bool", DocSurface: true})
	parent.AddCommand(cmd)
	return nil
}

// runRenderAssetCmd executes the render-asset command.
func runRenderAssetCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if requested, _ := cmd.Flags().GetBool("schema"); requested {
		return usage.EmitBodySchema(cmd.OutOrStdout(), "renderAsset")
	}
	res, err := executeRenderAssetCmd(cmd, args, false)
	if err != nil {
		return err
	}
	if res == nil {
		return nil
	}
	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
func executeRenderAssetCmd(cmd *cobra.Command, args []string, asyncIntent bool) (*operations.RenderAssetResponse, error) {
	request, err := flagutil.BuildRequest[operations.RenderAssetRequest](cmd, renderAssetCmdMeta, "", "body")
	if err != nil {
		return nil, flagutil.WithCLIValidation(err)
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return nil, err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return nil, err
	}
	if client.IsDryRun(cmd) || asyncIntent {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return nil, err
	}
	if !client.IsDryRun(cmd) && !asyncIntent {
		res, err := s.RenderAsset(cmd.Context(), *request, sdkOpts...)
		if err != nil {
			return nil, output.Error(cmd, err)
		}
		if err := output.StreamResult(cmd, res, "AssetStream"); err != nil {
			return nil, err
		}
		return nil, nil
	}
	if asyncIntent || output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.RenderAsset(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return nil, output.Error(cmd, err)
	}
	return res, nil
}
