// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package cli

import (
	"context"
	"fmt"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"openapi/internal/cli/group"
	"openapi/internal/cli/namespacetests"
	"openapi/internal/cli/obsolete"
	"openapi/internal/cli/tag1"
	"openapi/internal/cli/testgroup"
	"openapi/internal/clierrors"
	"openapi/internal/config"
	"openapi/internal/explorer"
	"openapi/internal/flagutil"
	"openapi/internal/interactive"
	"openapi/internal/output"
	"openapi/internal/usage"
	"os"
	"strings"
)

var rootCmd *cobra.Command

// NewRootCommand creates and returns the root command.
// This is exported for testing purposes to allow in-process command execution.
func NewRootCommand() (*cobra.Command, error) {
	cobra.AddTemplateFunc("groupedFlagUsages", groupedFlagUsages)
	cobra.AddTemplateFunc("groupedGlobalFlagUsages", groupedGlobalFlagUsages)
	rootCmd := &cobra.Command{
		Use:           "cli",
		Short:         "SDK Review: A test document for reviewing the SDK.",
		Long:          "This document will show case as many of our features as possible in as little operations/models as possible.\nThis will then generate a SDK that we can more easily review than the test SDKs based on uber.yaml spec.",
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return nil
			}
			if err := flagutil.ValidateEnumFlag(cmd, "output-format", output.Formats); err != nil {
				return err
			}
			if err := flagutil.ValidateEnumFlag(cmd, "color", []string{"auto", "always", "never"}); err != nil {
				return err
			}
			if err := config.Init("cli", "CLI"); err != nil {
				return err
			}
			output.InitAgentMode(cmd)
			flagutil.SetStdinReadDeadline(output.IsAgentMode())
			return nil
		},
	}
	if err := tag1.InitTag1Root(rootCmd); err != nil {
		return nil, fmt.Errorf("init tag1: %w", err)
	}
	if err := obsolete.InitObsoleteRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init obsolete: %w", err)
	}
	if err := testgroup.InitTestGroupRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init test-group: %w", err)
	}
	if err := group.InitGroupRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init group: %w", err)
	}
	if err := namespacetests.InitNamespaceTestsRoot(rootCmd); err != nil {
		return nil, fmt.Errorf("init namespace-tests: %w", err)
	}
	if err := initOperationWithLeadingAndTrailingUnderscoresCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init operation-with-leading-and-trailing-underscores: %w", err)
	}
	if err := initPostFileCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init post-file: %w", err)
	}
	if err := initGetPolymorphismCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-polymorphism: %w", err)
	}
	if err := initGetUnionErrorsCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-union-errors: %w", err)
	}
	if err := initGetRequestBodyFlattenedAwayCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-request-body-flattened-away: %w", err)
	}
	if err := initGetFullyFlattenedRequestCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-fully-flattened-request: %w", err)
	}
	if err := initCreateWithUnionCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init create-with-union: %w", err)
	}
	if err := initTestEndpointCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init test-endpoint: %w", err)
	}
	if err := initCreateUserCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init create-user: %w", err)
	}
	if err := initGetUserCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-user: %w", err)
	}
	if err := initUpdateUserCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init update-user: %w", err)
	}
	if err := initDeleteUserCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init delete-user: %w", err)
	}
	if err := initLoginCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init login: %w", err)
	}
	if err := initValidateCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init validate: %w", err)
	}
	if err := initChatCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init chat: %w", err)
	}
	if err := initGetBinaryDefaultResponseCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-binary-default-response: %w", err)
	}
	if err := initTestEnumFormatsCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init test-enum-formats: %w", err)
	}
	if err := initBinaryAndStringUploadCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init binary-and-string-upload: %w", err)
	}
	if err := initGetErrorInUnionCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-error-in-union: %w", err)
	}
	if err := initGetDuplicateExportCollisionCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-duplicate-export-collision: %w", err)
	}
	if err := initGetNamedPrimitiveUnionCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-named-primitive-union: %w", err)
	}
	if err := initGetEmptyObjectErrorCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-empty-object-error: %w", err)
	}
	if err := initUrlValidationStressTestCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init url-validation-stress-test: %w", err)
	}
	if err := initParenthesesInPathAllowedCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init parentheses-in-path-allowed: %w", err)
	}
	if err := initGetNestedIntegerStringCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-nested-integer-string: %w", err)
	}
	if err := initRenderAssetCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init render-asset: %w", err)
	}
	if err := initGetAssetCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-asset: %w", err)
	}
	if err := initGetErrorOnlyExampleCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init get-error-only-example: %w", err)
	}
	if err := initConfigureCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init configure: %w", err)
	}
	if err := initWhoamiCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init whoami: %w", err)
	}
	if err := initVersionCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init version: %w", err)
	}
	if err := initAuthCmd(rootCmd); err != nil {
		return nil, fmt.Errorf("init auth: %w", err)
	}
	initExploreCmd(rootCmd)

	// Global output format flag
	rootCmd.PersistentFlags().StringP("output-format", "o", "pretty", "Specify the output format. Options: "+strings.Join(output.Formats, ", ")+".")

	// Color control flag
	rootCmd.PersistentFlags().String("color", "auto", "Control colored output: auto (color when output is a TTY), always, or never. Respects NO_COLOR and FORCE_COLOR env vars.")

	// jq filtering flag
	rootCmd.PersistentFlags().StringP("jq", "q", "", "Filter and transform output using a jq expression (e.g., '.name', '.items[] | .id')")
	rootCmd.PersistentFlags().Bool("raw-output", false, "Write --jq string results as raw text instead of JSON strings (like jq -r); non-string results stay JSON")

	// Global server URL flag
	rootCmd.PersistentFlags().String("server-url", "", "Override the default server URL")

	// Server selection flag (by index or name)
	rootCmd.PersistentFlags().String("server", "", "Select a server by index (for indexed servers) or name (for named servers)")

	// Custom header flag (repeatable: --header "Key: Value" --header "Key2: Value2")
	rootCmd.PersistentFlags().StringArrayP("header", "H", nil, "Set a custom HTTP request header (format: \"Key: Value\"). Can be specified multiple times.")

	// Response headers flag
	rootCmd.PersistentFlags().Bool("include-headers", false, "Include HTTP response headers in the output")

	// Request timeout (always available)
	rootCmd.PersistentFlags().String("timeout", "", "HTTP request timeout (e.g., 30s, 5m, 100ms)")
	rootCmd.PersistentFlags().Bool("interactive", false, "Prompt for missing inputs and open guided configure/auth forms (forms fall back to line prompts on stdin off-TTY)")
	rootCmd.PersistentFlags().Bool("no-interactive", false, "Disable all interactive features (auto-prompting, explorer auto-launch, TUI forms)")

	// Diagnostics flags
	rootCmd.PersistentFlags().Bool("usage", false, "Print the CLI Usage schema in KDL format")
	rootCmd.PersistentFlags().Bool("dry-run", false, "Preview API requests without sending them (no network, no OS keychain). Human preview on stderr; with -o json or --jq, one JSON object per request on stdout. Local mutation commands (auth login, auth logout and configure) make no request: they skip prompts and writes and report a no-op (stderr, or one JSON object on stdout in the machine form)")
	rootCmd.PersistentFlags().BoolP("debug", "d", false, "Log request and response diagnostics to stderr")

	// Agent mode — optimized output for AI coding agent consumption.
	rootCmd.PersistentFlags().Bool("agent-mode", false,
		"Enable structured errors and default TOON output for AI coding agents.")
	// Retry control flags
	// Defaults: exponential backoff, 500ms initial / 10s max interval, 1.5x exponent, 30s max elapsed time.
	rootCmd.PersistentFlags().Bool("no-retries", false, "Disable automatic retries (default: retries enabled with exponential backoff)")
	rootCmd.PersistentFlags().String("retry-max-elapsed-time", "", "Maximum total time for retries (e.g., 30s, 5m). Default: 30s")
	rootCmd.PersistentFlags().Bool("retry-connection-errors", false, "Retry on connection errors (EOF, reset, etc.)")
	rootCmd.PersistentFlags().String("retry-config", "", `Full retry config as JSON. Schema: {"strategy":"backoff","backoff":{"initialInterval":500,"maxInterval":10000,"exponent":1.5,"maxElapsedTime":30000},"retryConnectionErrors":false}. Times are in milliseconds.`)

	// Server template variable flags
	rootCmd.PersistentFlags().String("subdomain", "", "Server template variable: subdomain")
	_ = rootCmd.PersistentFlags().SetAnnotation("subdomain", "speakeasy:group", []string{"Server"})
	rootCmd.PersistentFlags().String("version", "", "Server template variable: version")
	_ = rootCmd.PersistentFlags().SetAnnotation("version", "speakeasy:group", []string{"Server"})
	rootCmd.PersistentFlags().String("host-name", "", "Server template variable: HostName")
	_ = rootCmd.PersistentFlags().SetAnnotation("host-name", "speakeasy:group", []string{"Server"})
	rootCmd.PersistentFlags().String("port", "", "Server template variable: PORT")
	_ = rootCmd.PersistentFlags().SetAnnotation("port", "speakeasy:group", []string{"Server"})

	// Global security flags
	rootCmd.PersistentFlags().String("username", "", "HTTP Basic username")
	_ = rootCmd.PersistentFlags().SetAnnotation("username", "speakeasy:group", []string{"Authentication"})
	rootCmd.PersistentFlags().String("password", "", "HTTP Basic password")
	_ = rootCmd.PersistentFlags().SetAnnotation("password", "speakeasy:group", []string{"Authentication"})
	rootCmd.PersistentFlags().String("bearer-auth", "", "HTTP Bearer")
	_ = rootCmd.PersistentFlags().SetAnnotation("bearer-auth", "speakeasy:group", []string{"Authentication"})
	rootCmd.PersistentFlags().String("my-api-key", "", "API Key")
	_ = rootCmd.PersistentFlags().SetAnnotation("my-api-key", "speakeasy:group", []string{"Authentication"})
	rootCmd.PersistentFlags().String("oauth2", "", "OAuth2 Authorization")
	_ = rootCmd.PersistentFlags().SetAnnotation("oauth2", "speakeasy:group", []string{"Authentication"})
	rootCmd.PersistentFlags().String("app-id", "", "Custom authentication credential")
	_ = rootCmd.PersistentFlags().SetAnnotation("app-id", "speakeasy:group", []string{"Authentication"})
	rootCmd.PersistentFlags().String("secret", "", "Custom authentication credential")
	_ = rootCmd.PersistentFlags().SetAnnotation("secret", "speakeasy:group", []string{"Authentication"})
	rootCmd.PersistentFlags().String("mobile-auth", "", "OAuth2 Password flow, a flow that is too\nlong to describe in a single line.")
	_ = rootCmd.PersistentFlags().SetAnnotation("mobile-auth", "speakeasy:group", []string{"Authentication"})
	rootCmd.PersistentFlags().String("client-id", "", "Client Credentials flow. client identifier")
	_ = rootCmd.PersistentFlags().SetAnnotation("client-id", "speakeasy:group", []string{"Authentication"})
	rootCmd.PersistentFlags().String("client-secret", "", "Client Credentials flow. client secret")
	_ = rootCmd.PersistentFlags().SetAnnotation("client-secret", "speakeasy:group", []string{"Authentication"})
	rootCmd.PersistentFlags().String("token-url", "", "Client Credentials flow. token URL")
	_ = rootCmd.PersistentFlags().SetAnnotation("token-url", "speakeasy:group", []string{"Authentication"})
	// Global parameter flags
	rootCmd.PersistentFlags().String("query-param1", "", "A long winded, multi-line description (env: CLI_QUERY_PARAM1)")
	_ = rootCmd.PersistentFlags().SetAnnotation("query-param1", "speakeasy:group", []string{"API Parameters"})
	rootCmd.PersistentFlags().String("deprecated-query-param1", "", "A deprecated description (env: CLI_DEPRECATED_QUERY_PARAM1)")
	_ = rootCmd.PersistentFlags().SetAnnotation("deprecated-query-param1", "speakeasy:group", []string{"API Parameters"})
	rootCmd.PersistentFlags().String("deprecated-query-param2", "", "Global deprecated-query-param2 parameter (env: CLI_DEPRECATED_QUERY_PARAM2)")
	_ = rootCmd.PersistentFlags().SetAnnotation("deprecated-query-param2", "speakeasy:group", []string{"API Parameters"})
	rootCmd.PersistentFlags().String("lone-query-param", "", "Global lone-query-param parameter (env: CLI_LONE_QUERY_PARAM)")
	_ = rootCmd.PersistentFlags().SetAnnotation("lone-query-param", "speakeasy:group", []string{"API Parameters"})

	// Annotate persistent flags for grouped help display
	for _, ga := range []struct{ flag, group string }{
		{"output-format", "Output"},
		{"color", "Output"},
		{"raw-output", "Output"},
		{"jq", "Output"},
		{"include-headers", "Output"},
		{"interactive", "Output"},
		{"no-interactive", "Output"},
		{"server-url", "Server"},
		{"server", "Server"},
		{"header", "Network"},
		{"timeout", "Network"},
		{"usage", "Diagnostics"},
		{"dry-run", "Diagnostics"},
		{"debug", "Diagnostics"},
		{"agent-mode", "Diagnostics"},
	} {
		_ = rootCmd.PersistentFlags().SetAnnotation(ga.flag, "speakeasy:group", []string{ga.group})
	}
	for _, flag := range []string{"no-retries", "retry-max-elapsed-time", "retry-connection-errors", "retry-config"} {
		_ = rootCmd.PersistentFlags().SetAnnotation(flag, "speakeasy:group", []string{"Network"})
	}

	rootCmd.SetUsageTemplate(groupedUsageTemplate())

	if err := initIntentCmds(rootCmd); err != nil {
		return nil, err
	}

	// Cobra creates its default help and completion commands lazily inside Execute.
	rootCmd.InitDefaultHelpCmd()
	rootCmd.InitDefaultCompletionCmd()
	applyDeclaredCommandOrder(rootCmd)
	interactive.Intercept(rootCmd)
	usage.Intercept(rootCmd)
	// Cobra validates Args before any PersistentPreRunE runs.
	output.InstallErrorHandling(rootCmd)

	return rootCmd, nil
}

func Execute() error {
	var err error
	rootCmd, err = NewRootCommand()
	if err != nil {
		return err
	}

	return ExecuteRoot(context.Background(), rootCmd, os.Args[1:])
}

func ExecuteRoot(ctx context.Context, root *cobra.Command, args []string) error {
	// Cobra aborts on an unknown command or flag before PersistentPreRunE runs.
	output.InitAgentMode(root)
	target, _, findErr := root.Find(args)
	if findErr != nil || target == nil {
		target = root
	}
	output.PreparseRenderingFlags(target, args)
	root.SetArgs(args)
	executed, err := root.ExecuteContextC(ctx)
	if executed == nil {
		executed = root
	}
	if err != nil && findErr != nil {
		err = flagutil.WithCLIValidation(err)
	}
	return output.CLIError(executed, err)
}

func initExploreCmd(parent *cobra.Command) {
	parent.AddCommand(&cobra.Command{
		Use:   "explore",
		Short: "Interactively browse and run commands",
		Long:  "Launch an interactive command explorer to browse available commands, view their descriptions and flags, and execute them.",
		RunE: func(cmd *cobra.Command, args []string) error {
			// Agent mode: print help instead of launching TUI.
			if output.IsAgentMode() {
				return cmd.Root().Help()
			}
			if err := interactive.Resolve(cmd).ValidateDirectExplore(); err != nil {
				return err
			}
			return runExplorer(cmd.Root())
		},
	})
}

func ExplorerHandoffArgs(root *cobra.Command, selectedArgs []string) []string {
	interactionFlag := "--interactive"
	if noInteractive, _ := root.PersistentFlags().GetBool("no-interactive"); noInteractive {
		interactionFlag = "--no-interactive"
	}
	handoffArgs := []string{interactionFlag}
	if dryRun, _ := root.PersistentFlags().GetBool("dry-run"); dryRun {
		handoffArgs = append(handoffArgs, "--dry-run")
	}
	if debug, _ := root.PersistentFlags().GetBool("debug"); debug {
		handoffArgs = append(handoffArgs, "--debug")
	}
	// Rendering flags given to the explore invocation apply to the selected
	// command: the fresh command tree re-parses argv (and resets the
	// preparsed rendering state), so they must travel with it. The
	// --name=value form keeps boolean flags from swallowing the next token.
	for _, name := range []string{"output-format", "jq", "raw-output", "color"} {
		if flag := root.PersistentFlags().Lookup(name); flag != nil && flag.Changed {
			handoffArgs = append(handoffArgs, "--"+name+"="+flag.Value.String())
		}
	}
	return append(handoffArgs, selectedArgs...)
}

// runExplorer launches the explorer TUI and handles command execution handoff.
func runExplorer(root *cobra.Command) error {
	selectedArgs, err := explorer.Run(root, Version)
	if err != nil {
		return err
	}
	if selectedArgs == nil {
		return nil // user quit
	}
	// Build a fresh command tree and execute the selected command
	freshRoot, err := NewRootCommand()
	if err != nil {
		return err
	}
	return ExecuteRoot(context.Background(), freshRoot, ExplorerHandoffArgs(root, selectedArgs))
}

// globalFlagGroupOrder defines the display order for flag groups in help output.
// Groups without any flags are skipped automatically.
var globalFlagGroupOrder = []string{"Output", "Authentication", "API Parameters", "Server", "Network", "Diagnostics"}

// groupedFlagUsages splits local flags into sections for help display.
// For operation commands (flags with "speakeasy:required"): Required/Optional sections.
// For the root command (flags with "speakeasy:group"): category-based sections.
// Falls back to a flat "Flags:" listing otherwise.
func groupedFlagUsages(flags *pflag.FlagSet) string {
	required := pflag.NewFlagSet("required", pflag.ContinueOnError)
	optional := pflag.NewFlagSet("optional", pflag.ContinueOnError)
	hasGroupAnnotation := false

	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if ann, ok := f.Annotations["speakeasy:required"]; ok && len(ann) > 0 && ann[0] == "true" {
			required.AddFlag(f)
		} else {
			optional.AddFlag(f)
		}
		if _, ok := f.Annotations["speakeasy:group"]; ok {
			hasGroupAnnotation = true
		}
	})

	// Operation commands: Required/Optional sections, with sub-groups when present
	if required.HasFlags() {
		var buf strings.Builder
		buf.WriteString("Required Flags:\n")
		buf.WriteString(required.FlagUsages())
		if optional.HasFlags() {
			if hasGroupAnnotation {
				buf.WriteString("\n")
				buf.WriteString(renderOperationGroups(optional))
			} else {
				buf.WriteString("\nOptional Flags:\n")
				buf.WriteString(optional.FlagUsages())
			}
		}
		return strings.TrimRight(buf.String(), "\n")
	}

	// Grouped flags (root command or operation with only optional grouped flags)
	if hasGroupAnnotation {
		// Check if any groups are in the global order (root-level groups like Output, Server)
		hasGlobalGroup := false
		flags.VisitAll(func(f *pflag.Flag) {
			if ann, ok := f.Annotations["speakeasy:group"]; ok && len(ann) > 0 {
				for _, g := range globalFlagGroupOrder {
					if ann[0] == g {
						hasGlobalGroup = true
					}
				}
			}
		})
		if hasGlobalGroup {
			return renderGroupedFlags(flags, "Flags")
		}
		// Operation-level groups (e.g., Address, Profile)
		return strings.TrimRight(renderOperationGroups(flags), "\n")
	}

	// Fallback: flat listing
	return "Flags:\n" + strings.TrimRight(flags.FlagUsages(), "\n")
}

// groupedGlobalFlagUsages splits inherited (global) flags into category sections
// based on the "speakeasy:group" annotation. Falls back to flat "Global Flags:".
func groupedGlobalFlagUsages(flags *pflag.FlagSet) string {
	hasGroupAnnotation := false
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if _, ok := f.Annotations["speakeasy:group"]; ok {
			hasGroupAnnotation = true
		}
	})

	if hasGroupAnnotation {
		return renderGroupedFlags(flags, "Global Flags")
	}

	return "Global Flags:\n" + strings.TrimRight(flags.FlagUsages(), "\n")
}

// renderOperationGroups renders optional operation flags grouped by their
// "speakeasy:group" annotation. Groups are shown alphabetically, with
// ungrouped flags under a generic "Optional Flags" header.
func renderOperationGroups(flags *pflag.FlagSet) string {
	groups := make(map[string]*pflag.FlagSet)
	groupOrder := []string{}
	groupOrders := make(map[string]int)
	ungrouped := pflag.NewFlagSet("ungrouped", pflag.ContinueOnError)

	parseOrder := func(raw string) (int, bool) {
		if raw == "" {
			return 0, false
		}
		sign, start := 1, 0
		if raw[0] == '-' {
			sign, start = -1, 1
		}
		if start == len(raw) {
			return 0, false
		}
		value := 0
		for i := start; i < len(raw); i++ {
			if raw[i] < '0' || raw[i] > '9' {
				return 0, false
			}
			value = value*10 + int(raw[i]-'0')
		}
		return sign * value, true
	}

	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if ann, ok := f.Annotations["speakeasy:group"]; ok && len(ann) > 0 {
			name := ann[0]
			if _, exists := groups[name]; !exists {
				groups[name] = pflag.NewFlagSet(name, pflag.ContinueOnError)
				groupOrder = append(groupOrder, name)
			}
			groups[name].AddFlag(f)
			if orderAnn, ok := f.Annotations["speakeasy:group-order"]; ok && len(orderAnn) > 0 {
				if order, valid := parseOrder(orderAnn[0]); valid {
					current, exists := groupOrders[name]
					if !exists || order < current {
						groupOrders[name] = order
					}
				}
			}
		} else {
			ungrouped.AddFlag(f)
		}
	})

	for i := 1; i < len(groupOrder); i++ {
		for j := i; j > 0; j-- {
			current, currentOrdered := groupOrders[groupOrder[j]]
			previous, previousOrdered := groupOrders[groupOrder[j-1]]
			if !currentOrdered || (previousOrdered && current >= previous) {
				break
			}
			groupOrder[j], groupOrder[j-1] = groupOrder[j-1], groupOrder[j]
		}
	}

	var buf strings.Builder

	// Show ungrouped optional flags first
	if ungrouped.HasFlags() {
		buf.WriteString("Optional Flags:\n")
		buf.WriteString(ungrouped.FlagUsages())
	}

	// Then show each group
	for _, name := range groupOrder {
		fs := groups[name]
		if !fs.HasFlags() {
			continue
		}
		buf.WriteString("\n" + name + " Flags:\n")
		buf.WriteString(fs.FlagUsages())
	}

	return buf.String()
}

// renderGroupedFlags groups flags by their "speakeasy:group" annotation,
// rendering each group as a separate section with a header. Flags without
// a group annotation are collected under the fallbackHeader section.
func renderGroupedFlags(flags *pflag.FlagSet, fallbackHeader string) string {
	groups := make(map[string]*pflag.FlagSet)
	for _, g := range globalFlagGroupOrder {
		groups[g] = pflag.NewFlagSet(g, pflag.ContinueOnError)
	}
	ungrouped := pflag.NewFlagSet("ungrouped", pflag.ContinueOnError)

	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		if ann, ok := f.Annotations["speakeasy:group"]; ok && len(ann) > 0 {
			if fs, exists := groups[ann[0]]; exists {
				fs.AddFlag(f)
				return
			}
		}
		ungrouped.AddFlag(f)
	})

	var buf strings.Builder
	first := true
	for _, name := range globalFlagGroupOrder {
		fs := groups[name]
		if !fs.HasFlags() {
			continue
		}
		if !first {
			buf.WriteString("\n")
		}
		buf.WriteString(name + ":\n")
		buf.WriteString(fs.FlagUsages())
		first = false
	}
	if ungrouped.HasFlags() {
		if !first {
			buf.WriteString("\n")
		}
		buf.WriteString(fallbackHeader + ":\n")
		buf.WriteString(ungrouped.FlagUsages())
	}
	return strings.TrimRight(buf.String(), "\n")
}

// groupedUsageTemplate returns Cobra's default usage template with the local
// and global Flags sections replaced to use grouped rendering.
// Built at runtime via strings.Replace to avoid template delimiter conflicts
// with the code generator's own template engine.
func groupedUsageTemplate() string {
	ob := string([]byte{'{', '{'})
	cb := string([]byte{'}', '}'})
	nl := string(rune(10))
	defaultTmpl := (&cobra.Command{}).UsageTemplate()

	// Replace local flags section
	oldLocal := "Flags:\n" + ob + ".LocalFlags.FlagUsages | trimTrailingWhitespaces" + cb
	replLocal := ob + "groupedFlagUsages .LocalFlags | trimTrailingWhitespaces" + cb
	result := strings.Replace(defaultTmpl, oldLocal, replLocal, 1)

	// Replace global flags section
	oldGlobal := "Global Flags:\n" + ob + ".InheritedFlags.FlagUsages | trimTrailingWhitespaces" + cb
	replGlobal := ob + "groupedGlobalFlagUsages .InheritedFlags | trimTrailingWhitespaces" + cb
	result = strings.Replace(result, oldGlobal, replGlobal, 1)

	oldFooter := "for more information about a command." + ob + "end" + cb
	replFooter := "for more information about a command." +
		ob + "if not .HasParent" + cb +
		"\n\nMachine interface: --usage (command tree as KDL) · --schema (request JSON Schema, on commands with a body) · --dry-run (request preview, no credentials) · --output-format json · --jq <expr>" +
		ob + "end" + cb + ob + "end" + cb
	result = strings.Replace(result, oldFooter, replFooter, 1)

	result = strings.TrimRight(result, nl) + nl + nl + clierrors.HelpFooter + nl

	return result
}
