/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorT, ErrorT$zodSchema } from "./error.js";

/**
 * OK
 */
export type GetErrorOnlyExampleResponseBody = {
  id: string;
  name: string;
  status?: string | undefined;
};

export const GetErrorOnlyExampleResponseBody$zodSchema: z.ZodType<
  GetErrorOnlyExampleResponseBody
> = z.object({
  id: z.string(),
  name: z.string(),
  status: z.string().optional(),
}).describe("OK");

export type GetErrorOnlyExampleResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetErrorOnlyExampleResponseBody | undefined;
  ErrorT?: ErrorT | undefined;
};

export const GetErrorOnlyExampleResponse$zodSchema: z.ZodType<
  GetErrorOnlyExampleResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  ErrorT: ErrorT$zodSchema.optional().describe("Not Found"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  object: z.lazy(() => GetErrorOnlyExampleResponseBody$zodSchema).optional()
    .describe("OK"),
});
