/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  NamespaceConflictTest,
  NamespaceConflictTest$zodSchema,
} from "./namespaceconflicttest.js";

export type GetNamespaceConflictResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  NamespaceConflictTest?: NamespaceConflictTest | undefined;
};

export const GetNamespaceConflictResponse$zodSchema: z.ZodType<
  GetNamespaceConflictResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  NamespaceConflictTest: NamespaceConflictTest$zodSchema.optional().describe(
    "OK",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
});
