/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UserPassAuth = { username: string; password: string };

export const UserPassAuth$zodSchema: z.ZodType<UserPassAuth> = z.object({
  password: z.string().describe("HTTP Basic password"),
  username: z.string().describe("HTTP Basic username"),
});

export type SecurityOption2 = { bearerAuth: string; MyApiKey: string };

export const SecurityOption2$zodSchema: z.ZodType<SecurityOption2> = z.object({
  MyApiKey: z.string().describe("API Key"),
  bearerAuth: z.string().describe("HTTP Bearer"),
});

export type SecurityOption3 = { oauth2: string };

export const SecurityOption3$zodSchema: z.ZodType<SecurityOption3> = z.object({
  oauth2: z.string().describe("OAuth2 Authorization"),
});

export type SecurityOption4 = { appId: string; secret: string };

export const SecurityOption4$zodSchema: z.ZodType<SecurityOption4> = z.object({
  appId: z.string(),
  secret: z.string(),
});

export type SecurityOption5 = { mobileAuth: string };

export const SecurityOption5$zodSchema: z.ZodType<SecurityOption5> = z.object({
  mobileAuth: z.string().describe(
    "OAuth2 Password flow, a flow that is too\nlong to describe in a single line.",
  ),
});

export type SecurityOption6 = { clientCredentials: string };

export const SecurityOption6$zodSchema: z.ZodType<SecurityOption6> = z.object({
  clientCredentials: z.string().describe("Client Credentials flow."),
});

export type MyApiKey = { MyApiKey: string };

export const MyApiKey$zodSchema: z.ZodType<MyApiKey> = z.object({
  MyApiKey: z.string().describe("API Key"),
});

export type Security = {
  UserPassAuth?: UserPassAuth | undefined;
  Option2?: SecurityOption2 | undefined;
  Option3?: SecurityOption3 | undefined;
  Option4?: SecurityOption4 | undefined;
  Option5?: SecurityOption5 | undefined;
  Option6?: SecurityOption6 | undefined;
  MyApiKey?: MyApiKey | undefined;
};

export const Security$zodSchema: z.ZodType<Security> = z.object({
  MyApiKey: z.lazy(() => MyApiKey$zodSchema).optional(),
  Option2: z.lazy(() => SecurityOption2$zodSchema).optional(),
  Option3: z.lazy(() => SecurityOption3$zodSchema).optional(),
  Option4: z.lazy(() => SecurityOption4$zodSchema).optional(),
  Option5: z.lazy(() => SecurityOption5$zodSchema).optional(),
  Option6: z.lazy(() => SecurityOption6$zodSchema).optional(),
  UserPassAuth: z.lazy(() => UserPassAuth$zodSchema).optional(),
});
